unit isb_Consts;

interface

const
  PORT_BOOTLOADER = 0;
  PORT_RTC = 2;
  PORT_CONFIG = 4;
  PORT_OUTPUT = 6;
  PORT_INPUT = 8;
  PORT_DCF77 = 10;
  PORT_TIMESWITCH	= 12;
  PORT_LOGIC = 14;
  PORT_KEYBOARD = 16;
  PORT_ADC = 18;



	EE_SIZE = 512;

	EE_WATCHDOG_CTRL = 0;
	EE_WATCHDOG_RESET_COUNTER = 1;

  EE_ERROR = 2;

	EE_NODE_ID0 = 3;
	EE_NODE_ID1 = 4;

	EE_FIRMWARE_ID0 = 5;
	EE_FIRMWARE_ID1 = 6;
	EE_FIRMWARE_ID2 = 7;
	EE_FIRMWARE_ID3 = 8;

	EE_SPI_CTRL = 9;

	EE_USART0_CTRL = 10;
	EE_USART0_BAUDRATE0 = 11;
	EE_USART0_BAUDRATE1 = 12;
	EE_USART0_BAUDRATE2 = 13;
	EE_USART0_BAUDRATE3 = 14;
	EE_USART1_CTRL = 15;
	EE_USART1_BAUDRATE0 = 16;
	EE_USART1_BAUDRATE1 = 17;
	EE_USART1_BAUDRATE2 = 18;
	EE_USART1_BAUDRATE3 = 19;

	EE_TWI_CTRL = 20;
	EE_TWI_SPEED = 21;
	EE_TWI_ADDRESS = 22;

	EE_CAN0_CTRL = 23;
	EE_CAN0_CFGSPI = 24;

	EE_CAN1_CTRL = 25;
	EE_CAN1_CFGSPI = 26;

	EE_CAN2_CTRL = 27;
	EE_CAN2_CFGSPI = 28;

	EE_LOADER_CTRL = 29;

	EE_RTC_CTRL = 30;

	EE_INPUT_CTRL = 31;
  EE_INPUT_00_CFG = 32;
  EE_INPUT_00_ADCCFG = 33;
  EE_INPUT_00_CTRL = 34;
  EE_INPUT_00_EVENTID0 = 35;
  EE_INPUT_00_EVENTID1 = 36;
  EE_INPUT_00_EVENTID = EE_INPUT_00_EVENTID0;
  EE_INPUT_01_CFG = 37;
  EE_INPUT_01_ADCCFG = 38;
  EE_INPUT_01_CTRL = 39;
  EE_INPUT_01_EVENTID0 = 40;
  EE_INPUT_01_EVENTID1 = 41;
  EE_INPUT_01_EVENTID = EE_INPUT_01_EVENTID0;
  EE_INPUT_02_CFG = 42;
  EE_INPUT_02_ADCCFG = 43;
  EE_INPUT_02_CTRL = 44;
  EE_INPUT_02_EVENTID0 = 45;
  EE_INPUT_02_EVENTID1 = 46;
  EE_INPUT_02_EVENTID = EE_INPUT_01_EVENTID0;

	EE_OUTPUT_CTRL = 28;

	EE_DCF77_CTRL = 30;

	EE_KEYBOARD_CTRL = 31;

	EE_ADC_CTRL = 32;

	EE_TIMESWITCH_CTRL = 33;

	EE_LOGIC_CTRL = 34;

	EE_PIN_START = 64;
	EE_PIN_END = 127;

	EE_MSG_START = 128;
	EE_MSG_END = 255;



  CONFIG_MODE_NORMAL = 0;
  CONFIG_MODE_CONFIG = 1;

  CONFIG_CMD_SWITCH_MODE_NORMAL	= 0;
  CONFIG_CMD_SWITCH_MODE_CONFIG	= 1;
  CONFIG_CMD_READ_SERIALID = 2;
  CONFIG_CMD_READ_BOOTLOADERID = 3;
  CONFIG_CMD_READ_HARDWAREID = 4;
  CONFIG_CMD_READ_INTERFACEID	= 5;
  CONFIG_CMD_READ_FIRMWAREID = 6;
  CONFIG_CMD_READ_BYTE = 7;
  CONFIG_CMD_WRITE_BYTE	= 8;
  CONFIG_CMD_READ_WORD = 9;
  CONFIG_CMD_WRITE_WORD	= 10;

//  CONFIG_EVENT_PING	= 1;

  CONFIG_ANSWER_ACK	= 0;
  CONFIG_ANSWER_NACK = 16;
  CONFIG_ANSWER_NACK_PASSWORD	= 32;
  CONFIG_ANSWER_NACK_DATALENGTH	= 48;
  CONFIG_ANSWER_NACK_MODE	= 64;
  CONFIG_ANSWER_NACK_COMMAND = 80;

  CONFIG_PASSWORD	= 65278;



  OUTPUT_CMD_INDEX_OFF = 0;
  OUTPUT_CMD_INDEX_ON	= 1;
  OUTPUT_CMD_INDEX_TOGGLE = 2;

  OUTPUT_ANSWER_ACK = 0;
  OUTPUT_ANSWER_NACK = 16;
  OUTPUT_ANSWER_NACK_DATALENGTH= 32;
  OUTPUT_ANSWER_NACK_COMMAND = 48;

implementation

end.
