#ifndef SERV_INPUT_CONFIG_H_
#define SERV_INPUT_CONFIG_H_

#define SERV_INPUT_COUNT 8

#define SERV_INPUT_IN0_PORT PORTB
#define SERV_INPUT_IN0_PIN  PB0
#define SERV_INPUT_IN0_DDR  DDRB




#endif /*SERV_INPUT_CONFIG_H_*/
