/**
 * @file		fw/fw_24/trunk/main.c
 *
 * @brief		Firmware.
 *
 * This file includes the Firmware.
 *
 * @author		© Patrick Amrhein <trick-at-isysbus-dot-org> 01.05.2010.
 *
 * @date		$Date$
 *
 * @version		$Rev$
 *
 * @note
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http:*www.gnu.org/licenses.
 */





#include <stdio.h>



#define USE_AVRLIB_ISB



#include <trunk/core/isb_fw_app.h>



const uint8_t Isb_Firmware_Code[4] = { 0x18, 0x00, 0x00, 0x00 };



#define ISB_INF_CAN0 TRUE
#if ISB_INF_CAN0 == TRUE
	#define ISB_INF_CAN0_CLOCK 4000000
	#define ISB_INF_CAN0_SPEED 50000
	#define ISB_INF_CAN0_SS PORTB_PIN4
	#define ISB_INF_CAN0_RS MCP2515_RX0BF
	#define ISB_INF_CAN0_INT INTERRUPT2
	#define ISB_INF_CAN0_MODE LIB_MCP2515_MODE_NORMAL
#endif /* ISB_INF_CAN0 == TRUE */



#define ISB_CH_MAX 4

#define ISB_CH_0 0
#if defined(ISB_CH_0)
	#define ISB_CH_0_EEADDR_CTRL 0x0000
	#define ISB_APP_DIGIN_0 0
	#define ISB_APP_DIGIN_0_CH 0
	#define ISB_APP_DIGIN_0_EEADDR_CFG0 0x0001
	#define ISB_APP_DIGIN_0_EEADDR_CFG1 0x0002
	#define ISB_APP_DIGIN_0_EEADDR_CFG2 0x0003
	#define ISB_APP_DIGIN_0_EEADDR_CFG3 0x0004
	#define ISB_APP_DIGIN_0_PIN0 B | 0 | PULLUP
	#define ISB_APP_DIGIN_0_OBJ_0_EEADDR_CTRL 0x0005
	#define ISB_APP_DIGIN_0_OBJ_0_EEADDR_TOV 0x0006
	#define ISB_APP_DIGIN_0_OBJ_0_EEADDR_INITVALUE 0x0007
	#define ISB_APP_DIGIN_0_OBJ_1_EEADDR_CTRL 0x000C
	#define ISB_APP_DIGIN_0_OBJ_1_EEADDR_TOV 0x000D
	#define ISB_APP_DIGIN_0_OBJ_1_EEADDR_INITVALUE 0x000E
	#define ISB_APP_DIGIN_0_OBJ_2_EEADDR_CTRL 0x0013
	#define ISB_APP_DIGIN_0_OBJ_2_EEADDR_TOV 0x0014
	#define ISB_APP_DIGIN_0_OBJ_2_EEADDR_INITVALUE 0x0015
	#define ISB_APP_DIGIN_0_OBJ_0 0
	#define ISB_OBJ_0 0
	#define ISB_OBJ_0_CH 0
	#define ISB_APP_DIGIN_0_OBJ_1 1
	#define ISB_OBJ_1 1
	#define ISB_OBJ_1_CH 0
	#define ISB_APP_DIGIN_0_OBJ_2 2
	#define ISB_OBJ_2 2
	#define ISB_OBJ_2_CH 0
	#define ISB_CH_0_EEADDR_CRC 0x001A
#endif /* ISB_CH_0 */

#define ISB_CH_1 1
#if defined(ISB_CH_1)
	#define ISB_CH_1_EEADDR_CTRL 0x001B
	#define ISB_APP_DIGIN_1 1
	#define ISB_APP_DIGIN_1_CH 1
	#define ISB_APP_DIGIN_1_EEADDR_CFG0 0x001C
	#define ISB_APP_DIGIN_1_EEADDR_CFG1 0x001D
	#define ISB_APP_DIGIN_1_EEADDR_CFG2 0x001E
	#define ISB_APP_DIGIN_1_EEADDR_CFG3 0x001F
	#define ISB_APP_DIGIN_1_PIN0 B | 1 | PULLUP
	#define ISB_APP_DIGIN_1_OBJ_0_EEADDR_CTRL 0x0020
	#define ISB_APP_DIGIN_1_OBJ_0_EEADDR_TOV 0x0021
	#define ISB_APP_DIGIN_1_OBJ_0_EEADDR_INITVALUE 0x0022
	#define ISB_APP_DIGIN_1_OBJ_1_EEADDR_CTRL 0x0027
	#define ISB_APP_DIGIN_1_OBJ_1_EEADDR_TOV 0x0028
	#define ISB_APP_DIGIN_1_OBJ_1_EEADDR_INITVALUE 0x0029
	#define ISB_APP_DIGIN_1_OBJ_2_EEADDR_CTRL 0x002E
	#define ISB_APP_DIGIN_1_OBJ_2_EEADDR_TOV 0x002F
	#define ISB_APP_DIGIN_1_OBJ_2_EEADDR_INITVALUE 0x0030
	#define ISB_APP_DIGIN_1_OBJ_0 3
	#define ISB_OBJ_3 3
	#define ISB_OBJ_3_CH 1
	#define ISB_APP_DIGIN_1_OBJ_1 4
	#define ISB_OBJ_4 4
	#define ISB_OBJ_4_CH 1
	#define ISB_APP_DIGIN_1_OBJ_2 5
	#define ISB_OBJ_5 5
	#define ISB_OBJ_5_CH 1
	#define ISB_CH_1_EEADDR_CRC 0x0035
#endif /* ISB_CH_1 */

#define ISB_CH_2 2
#if defined(ISB_CH_2)
	#define ISB_CH_2_EEADDR_CTRL 0x0036
	#define ISB_APP_DIGOUT_0 0
	#define ISB_APP_DIGOUT_0_CH 2
	#define ISB_APP_DIGOUT_0_PIN0 C | 6
	#define ISB_APP_DIGOUT_0_PIN1 B | 0 | PULLUP
	#define ISB_APP_DIGOUT_0_EEADDR_CFG0 0x0037
	#define ISB_APP_DIGOUT_0_OBJ_0_EEADDR_CTRL 0x0038
	#define ISB_APP_DIGOUT_0_OBJ_0_EEADDR_TOV 0x0039
	#define ISB_APP_DIGOUT_0_OBJ_0_EEADDR_INITVALUE 0x003A
	#define ISB_APP_DIGOUT_0_OBJ_0 6
	#define ISB_OBJ_6 6
	#define ISB_OBJ_6_CH 2
	#define ISB_APP_DIGOUT_0_EEADDR_CFG1 0x003F
	#define ISB_APP_DIGOUT_0_OBJ_1_EEADDR_CTRL 0x0040
	#define ISB_APP_DIGOUT_0_OBJ_1_EEADDR_TOV 0x0041
	#define ISB_APP_DIGOUT_0_OBJ_1_EEADDR_INITVALUE 0x0042
	#define ISB_APP_DIGOUT_0_OBJ_1 7
	#define ISB_OBJ_7 7
	#define ISB_OBJ_7_CH 2
	#define ISB_APP_DIGOUT_0_EEADDR_CFG2 0x0047
	#define ISB_APP_DIGOUT_0_OBJ_2_EEADDR_CTRL 0x0048
	#define ISB_APP_DIGOUT_0_OBJ_2_EEADDR_TOV 0x0049
	#define ISB_APP_DIGOUT_0_OBJ_2_EEADDR_INITVALUE 0x004A
	#define ISB_APP_DIGOUT_0_OBJ_2 8
	#define ISB_OBJ_8 8
	#define ISB_OBJ_8_CH 2
	#define ISB_APP_DIGOUT_0_EEADDR_CFG3 0x004F
	#define ISB_APP_DIGOUT_0_EEADDR_CFG4 0x0050
	#define ISB_APP_DIGOUT_0_EEADDR_CFG5 0x0051
	#define ISB_APP_DIGOUT_0_EEADDR_CFG6 0x0052
	#define ISB_APP_DIGOUT_0_EEADDR_CFG7 0x0053
	#define ISB_APP_DIGOUT_0_EEADDR_CFG8 0x0054
	#define ISB_APP_DIGOUT_0_EEADDR_CFG9 0x0055
	#define ISB_APP_DIGOUT_0_EEADDR_CFG10 0x0056
	#define ISB_APP_DIGOUT_0_OBJ_3_EEADDR_CTRL 0x0057
	#define ISB_APP_DIGOUT_0_OBJ_3_EEADDR_TOV 0x0058
	#define ISB_APP_DIGOUT_0_OBJ_3_EEADDR_INITVALUE 0x0059
	#define ISB_APP_DIGOUT_0_OBJ_3 9
	#define ISB_OBJ_9 9
	#define ISB_OBJ_9_CH 2
	#define ISB_CH_2_EEADDR_CRC 0x005E
#endif /* ISB_CH_2 */

#define ISB_CH_3 3
#if defined(ISB_CH_3)
	#define ISB_CH_3_EEADDR_CTRL 0x005F
	#define ISB_APP_DIGOUT_1 1
	#define ISB_APP_DIGOUT_1_CH 3
	#define ISB_APP_DIGOUT_1_PIN0 C | 7
	#define ISB_APP_DIGOUT_1_PIN1 B | 1 | PULLUP
	#define ISB_APP_DIGOUT_1_EEADDR_CFG0 0x0060
	#define ISB_APP_DIGOUT_1_OBJ_0_EEADDR_CTRL 0x0061
	#define ISB_APP_DIGOUT_1_OBJ_0_EEADDR_TOV 0x0062
	#define ISB_APP_DIGOUT_1_OBJ_0_EEADDR_INITVALUE 0x0063
	#define ISB_APP_DIGOUT_1_OBJ_0 10
	#define ISB_OBJ_10 10
	#define ISB_OBJ_10_CH 3
	#define ISB_APP_DIGOUT_1_EEADDR_CFG1 0x0068
	#define ISB_APP_DIGOUT_1_OBJ_1_EEADDR_CTRL 0x0069
	#define ISB_APP_DIGOUT_1_OBJ_1_EEADDR_TOV 0x006A
	#define ISB_APP_DIGOUT_1_OBJ_1_EEADDR_INITVALUE 0x006B
	#define ISB_APP_DIGOUT_1_OBJ_1 11
	#define ISB_OBJ_11 11
	#define ISB_OBJ_11_CH 3
	#define ISB_APP_DIGOUT_1_EEADDR_CFG2 0x0070
	#define ISB_APP_DIGOUT_1_OBJ_2_EEADDR_CTRL 0x0071
	#define ISB_APP_DIGOUT_1_OBJ_2_EEADDR_TOV 0x0072
	#define ISB_APP_DIGOUT_1_OBJ_2_EEADDR_INITVALUE 0x0073
	#define ISB_APP_DIGOUT_1_OBJ_2 12
	#define ISB_OBJ_12 12
	#define ISB_OBJ_12_CH 3
	#define ISB_APP_DIGOUT_1_EEADDR_CFG3 0x0078
	#define ISB_APP_DIGOUT_1_EEADDR_CFG4 0x0079
	#define ISB_APP_DIGOUT_1_EEADDR_CFG5 0x007A
	#define ISB_APP_DIGOUT_1_EEADDR_CFG6 0x007B
	#define ISB_APP_DIGOUT_1_EEADDR_CFG7 0x007C
	#define ISB_APP_DIGOUT_1_EEADDR_CFG8 0x007D
	#define ISB_APP_DIGOUT_1_EEADDR_CFG9 0x007E
	#define ISB_APP_DIGOUT_1_EEADDR_CFG10 0x007F
	#define ISB_APP_DIGOUT_1_OBJ_3_EEADDR_CTRL 0x0080
	#define ISB_APP_DIGOUT_1_OBJ_3_EEADDR_TOV 0x0081
	#define ISB_APP_DIGOUT_1_OBJ_3_EEADDR_INITVALUE 0x0082
	#define ISB_APP_DIGOUT_1_OBJ_3 13
	#define ISB_OBJ_13 13
	#define ISB_OBJ_13_CH 3
	#define ISB_CH_3_EEADDR_CRC 0x0087
#endif /* ISB_CH_3 */



#define ISB_APP_DIGIN_MAX 2
#define ISB_APP_DIGIN_EXECTIME 10
#define ISB_APP_DIGIN_SOURCE_FEATURE_PIN TRUE
#define ISB_APP_DIGIN_SOURCE_FEATURE_SLAVE_USART0 FALSE
#define ISB_APP_DIGIN_SOURCE_FEATURE_SLAVE_USART1 FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_SWITCH TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_SWITCH_FUNCTION_1SOUKLOR TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_SWITCH_FUNCTION_1SOUKLMR TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_SWITCH_FUNCTION_2SMUKLOR TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_SWITCH_FUNCTION_2SMUKLMR TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_DIMMER FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_DIMMER_FUNCTION_DUS FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_DIMMER_FUNCTION_ND FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_1TBKLLF FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_1TBKFLL FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_1TBNFS FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_1SBNF FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_2TBKLLF FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_2TBNF FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_2TBNFS FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_2TBNL FALSE

#define ISB_APP_DIGOUT_MAX 2
#define ISB_APP_DIGOUT_EXECTIME 10
#define ISB_APP_DIGOUT_DESTINATION_FEATURE_RELAIS TRUE
#define ISB_APP_DIGOUT_DESTINATION_FEATURE_SSR FALSE
#define ISB_APP_DIGOUT_DESTINATION_FEATURE_SLAVE_USART0 FALSE
#define ISB_APP_DIGOUT_DESTINATION_FEATURE_SLAVE_USART1 FALSE
#define ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION TRUE
#define ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION_AND TRUE
#define ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION_OR TRUE
#define ISB_APP_DIGOUT_FEATURE_TIMEFUNCTION TRUE
#define ISB_APP_DIGOUT_FEATURE_TIMEFUNCTION_POWERUPDELAY TRUE
#define ISB_APP_DIGOUT_FEATURE_TIMEFUNCTION_POWERDOWNDELAY TRUE
#define ISB_APP_DIGOUT_FEATURE_TIMEFUNCTION_STAIRCASEFUNCTION TRUE
#define ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION TRUE
#define ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION_BLOCKING TRUE
#define ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION_BONDAGE TRUE
#define ISB_APP_DIGOUT_FEATURE_RESULT TRUE

#define ISB_OBJ_MAX 14
#define ISB_OBJ_EXECTIME 10

#define ISB_GRP_MAX 14
#define ISB_GRP_EEADDR_START 0x0088



#include <trunk/core/isb_fw_app.c>
