# Auto-generated by EclipseNSIS Script Wizard
# 31.03.2010 19:38:55

Name "HomeControl"

# General Symbol Definitions
!define REGKEY "SOFTWARE\$(^Name)"
!ifndef VERSION
    !define VERSION 0.7.93
!endif
!ifndef BUILD
    !define BUILD 1
!endif
!define COMPANY isysbus.org
!define URL http://www.isysbus.org

# MultiUser Symbol Definitions
!define MULTIUSER_EXECUTIONLEVEL Standard
!define MULTIUSER_INSTALLMODE_COMMANDLINE
!define MULTIUSER_INSTALLMODE_INSTDIR HomeControl
!define MULTIUSER_INSTALLMODE_INSTDIR_REGISTRY_KEY "${REGKEY}"
!define MULTIUSER_INSTALLMODE_INSTDIR_REGISTRY_VALUE "Path"

# MUI Symbol Definitions
!define MUI_ICON resources\images\homecontrol.ico
!define MUI_FINISHPAGE_NOAUTOCLOSE
!define MUI_STARTMENUPAGE_REGISTRY_ROOT HKLM
!define MUI_STARTMENUPAGE_REGISTRY_KEY ${REGKEY}
!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME StartMenuGroup
!define MUI_STARTMENUPAGE_DEFAULTFOLDER iSysBus.org\HomeControl
!define MUI_UNFINISHPAGE_NOAUTOCLOSE

# Included files
!include MultiUser.nsh
!include Sections.nsh
!include MUI2.nsh

# Variables
Var StartMenuGroup

# Installer pages
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_COMPONENTS
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_STARTMENU Application $StartMenuGroup
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

# Installer languages
!insertmacro MUI_LANGUAGE German

# Installer attributes
OutFile release\${VERSION}\homecontrol_${VERSION}.exe
InstallDir HomeControl
CRCCheck on
XPStyle on
ShowInstDetails show
VIProductVersion ${VERSION}.${BUILD}
VIAddVersionKey ProductName "HomeControl"
VIAddVersionKey ProductVersion "${VERSION}"
VIAddVersionKey CompanyName "${COMPANY}"
VIAddVersionKey CompanyWebsite "${URL}"
VIAddVersionKey FileVersion "${VERSION}"
VIAddVersionKey FileDescription ""
VIAddVersionKey LegalCopyright ""
InstallDirRegKey HKLM "${REGKEY}" Path
ShowUninstDetails hide

!macro CREATE_SMGROUP_SHORTCUT NAME PATH
    Push "${NAME}"
    Push "${PATH}"
    Call CreateSMGroupShortcut
!macroend

# Installer sections
Section Main SEC0000
    SetOutPath $INSTDIR
    SetOverwrite on
    File release\${VERSION}\homecontrol.jar
    File release\${VERSION}\homecontrol.exe
    File release\${VERSION}\rxtxSerial.dll
    SetOutPath $INSTDIR\lib
    File release\${VERSION}\lib\RXTXcomm.jar
    File release\${VERSION}\lib\cambozola.jar
    File release\${VERSION}\lib\dom4j-1.6.1.jar
    File release\${VERSION}\lib\jaxen-1.1.1.jar
    File release\${VERSION}\lib\jcommon-1.0.16.jar
    File release\${VERSION}\lib\jfreechart-1.0.13.jar
    File release\${VERSION}\lib\jpf.jar
    File release\${VERSION}\lib\jsr173_1.0_api.jar
    File release\${VERSION}\lib\jxp.jar
    File release\${VERSION}\lib\resources.jar
    !insertmacro CREATE_SMGROUP_SHORTCUT "HomeControl" $INSTDIR\homecontrol.exe
    WriteRegStr HKLM "${REGKEY}\Components" Main 1
SectionEnd

SectionGroup /e AvrDude SECGRP0000
    Section "-AvrDude Binary" SEC0001
        SetOutPath $INSTDIR\3rdparty\avrdude\win
        SetOverwrite on
        File release\${VERSION}\3rdparty\avrdude\win\remove_giveio.bat
        File release\${VERSION}\3rdparty\avrdude\win\status_giveio.bat
        File release\${VERSION}\3rdparty\avrdude\win\avrdude.conf
        File release\${VERSION}\3rdparty\avrdude\win\avrdude.exe
        File release\${VERSION}\3rdparty\avrdude\win\giveio.sys
        File release\${VERSION}\3rdparty\avrdude\win\install_giveio.bat
        WriteRegStr HKLM "${REGKEY}\Components" "AvrDude Binary" 1
    SectionEnd

    Section "GiveIO installieren (ben�tigt f�r AvrDude)" SEC0002
        SetOutPath $WINDIR
        SetOverwrite on
        File release\${VERSION}\3rdparty\avrdude\win\giveio.sys
        !insertmacro CREATE_SMGROUP_SHORTCUT "GiveIO installieren" $INSTDIR\3rdparty\avrdude\win\install_giveio.bat
        !insertmacro CREATE_SMGROUP_SHORTCUT "GiveIO deinstallieren" $INSTDIR\3rdparty\avrdude\win\install_giveio.bat
        WriteRegStr HKLM "${REGKEY}\Components" "GiveIO installieren (ben�tigt f�r AvrDude)" 1
    SectionEnd
SectionGroupEnd

Section -post SEC0003
    WriteRegStr HKLM "${REGKEY}" Path $INSTDIR
    SetOutPath $INSTDIR
    WriteUninstaller $INSTDIR\uninstall.exe
    !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
    SetOutPath $SMPROGRAMS\$StartMenuGroup
    CreateShortcut "$SMPROGRAMS\$StartMenuGroup\Uninstall $(^Name).lnk" $INSTDIR\uninstall.exe
    !insertmacro MUI_STARTMENU_WRITE_END
    WriteRegStr HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" DisplayName "$(^Name)"
    WriteRegStr HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" DisplayVersion "${VERSION}"
    WriteRegStr HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" Publisher "${COMPANY}"
    WriteRegStr HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" URLInfoAbout "${URL}"
    WriteRegStr HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" DisplayIcon $INSTDIR\uninstall.exe
    WriteRegStr HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" UninstallString $INSTDIR\uninstall.exe
    WriteRegDWORD HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" NoModify 1
    WriteRegDWORD HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" NoRepair 1
SectionEnd

# Macro for selecting uninstaller sections
!macro SELECT_UNSECTION SECTION_NAME UNSECTION_ID
    Push $R0
    ReadRegStr $R0 HKLM "${REGKEY}\Components" "${SECTION_NAME}"
    StrCmp $R0 1 0 next${UNSECTION_ID}
    !insertmacro SelectSection "${UNSECTION_ID}"
    GoTo done${UNSECTION_ID}
next${UNSECTION_ID}:
    !insertmacro UnselectSection "${UNSECTION_ID}"
done${UNSECTION_ID}:
    Pop $R0
!macroend

# Uninstaller sections
!macro DELETE_SMGROUP_SHORTCUT NAME
    Push "${NAME}"
    Call un.DeleteSMGroupShortcut
!macroend

Section /o "-un.GiveIO installieren (benötigt für AvrDude)" UNSEC0002
    !insertmacro DELETE_SMGROUP_SHORTCUT "GiveIO deinstallieren"
    !insertmacro DELETE_SMGROUP_SHORTCUT "GiveIO installieren"
    Delete /REBOOTOK $WINDIR\giveio.sys
    DeleteRegValue HKLM "${REGKEY}\Components" "GiveIO installieren (benötigt für AvrDude)"
SectionEnd

Section /o "-un.AvrDude Binary" UNSEC0001
    Delete /REBOOTOK $INSTDIR\3rdparty\avrdude\win\install_giveio.bat
    Delete /REBOOTOK $INSTDIR\3rdparty\avrdude\win\giveio.sys
    Delete /REBOOTOK $INSTDIR\3rdparty\avrdude\win\avrdude.exe
    Delete /REBOOTOK $INSTDIR\3rdparty\avrdude\win\avrdude.conf
    Delete /REBOOTOK $INSTDIR\3rdparty\avrdude\win\status_giveio.bat
    Delete /REBOOTOK $INSTDIR\3rdparty\avrdude\win\remove_giveio.bat
    DeleteRegValue HKLM "${REGKEY}\Components" "AvrDude Binary"
SectionEnd

Section /o -un.Main UNSEC0000
    Delete /REBOOTOK $INSTDIR\lib\resources.jar
    Delete /REBOOTOK $INSTDIR\lib\jxp.jar
    Delete /REBOOTOK $INSTDIR\lib\jsr173_1.0_api.jar
    Delete /REBOOTOK $INSTDIR\lib\jpf.jar
    Delete /REBOOTOK $INSTDIR\lib\jfreechart-1.0.13.jar
    Delete /REBOOTOK $INSTDIR\lib\jcommon-1.0.16.jar
    Delete /REBOOTOK $INSTDIR\lib\jaxen-1.1.1.jar
    Delete /REBOOTOK $INSTDIR\lib\dom4j-1.6.1.jar
    Delete /REBOOTOK $INSTDIR\lib\cambozola.jar
    Delete /REBOOTOK $INSTDIR\lib\RXTXcomm.jar
    Delete /REBOOTOK $INSTDIR\rxtxSerial.dll
    Delete /REBOOTOK $INSTDIR\homecontrol_0.6.0.jar
    DeleteRegValue HKLM "${REGKEY}\Components" Main
SectionEnd

Section -un.post UNSEC0003
    DeleteRegKey HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)"
    Delete /REBOOTOK "$SMPROGRAMS\$StartMenuGroup\Uninstall $(^Name).lnk"
    Delete /REBOOTOK $INSTDIR\uninstall.exe
    DeleteRegValue HKLM "${REGKEY}" StartMenuGroup
    DeleteRegValue HKLM "${REGKEY}" Path
    DeleteRegKey /IfEmpty HKLM "${REGKEY}\Components"
    DeleteRegKey /IfEmpty HKLM "${REGKEY}"
    RmDir /REBOOTOK $SMPROGRAMS\$StartMenuGroup
    RmDir /REBOOTOK $INSTDIR
    Push $R0
    StrCpy $R0 $StartMenuGroup 1
    StrCmp $R0 ">" no_smgroup
no_smgroup:
    Pop $R0
SectionEnd

# Installer functions
Function .onInit
    InitPluginsDir
    !insertmacro MULTIUSER_INIT
FunctionEnd

Function CreateSMGroupShortcut
    Exch $R0 ;PATH
    Exch
    Exch $R1 ;NAME
    Push $R2
    StrCpy $R2 $StartMenuGroup 1
    StrCmp $R2 ">" no_smgroup
    SetOutPath $SMPROGRAMS\$StartMenuGroup
    CreateShortcut "$SMPROGRAMS\$StartMenuGroup\$R1.lnk" $R0
no_smgroup:
    Pop $R2
    Pop $R1
    Pop $R0
FunctionEnd

# Uninstaller functions
Function un.onInit
    !insertmacro MUI_STARTMENU_GETFOLDER Application $StartMenuGroup
    !insertmacro MULTIUSER_UNINIT
    !insertmacro SELECT_UNSECTION Main ${UNSEC0000}
    !insertmacro SELECT_UNSECTION "AvrDude Binary" ${UNSEC0001}
    !insertmacro SELECT_UNSECTION "GiveIO installieren (benötigt für AvrDude)" ${UNSEC0002}
FunctionEnd

Function un.DeleteSMGroupShortcut
    Exch $R1 ;NAME
    Push $R2
    StrCpy $R2 $StartMenuGroup 1
    StrCmp $R2 ">" no_smgroup
    Delete /REBOOTOK "$SMPROGRAMS\$StartMenuGroup\$R1.lnk"
no_smgroup:
    Pop $R2
    Pop $R1
FunctionEnd

# Section Descriptions
!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
!insertmacro MUI_DESCRIPTION_TEXT ${SECGRP0000} "Wird benötigt, um Knoten über ISP programmieren zu können"
!insertmacro MUI_FUNCTION_DESCRIPTION_END
