/**
 * @file		avrlib/trunk/lib/isb_app.h
 *
 * @brief		iSysBus Application.
 *
 * This file includes iSysBus Application.
 *
 * @author		© Patrick Amrhein <trick-at-isysbus-dot-org> 01.05.2010.
 *
 * @date		$Date: 2012-05-03 16:09:41 +0200 (Do, 03. Mai 2012) $
 *
 * @version		$Rev: 7505 $
 *
 * @note
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version. \n
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details. \n
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http:*www.gnu.org/licenses. \n
 */





#ifndef ISB_APP_H_
	#define ISB_APP_H_



	#if defined(ISB_CH_MAX)

		typedef struct Isb_Ch_t Isb_Ch_t;

		struct Isb_Ch_t
		{
			uint16_t Ctrl;
		};

		static Isb_Ch_t Isb_Ch[ISB_CH_MAX];

	#endif /* ISB_CH_MAX */



	#if defined(ISB_APP_ANAIN_MAX)

		#if ISB_APP_ANAIN_MAX == 1
			static const uint8_t pgmIsb_App_AnaIn_Ch_Array[] PROGMEM = { ISB_APP_ANAIN_0_CH };
			static const uint8_t pgmIsb_App_AnaIn_Obj_0_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_0 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_1_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_1 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_2_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_2 };
		#elif ISB_APP_ANAIN_MAX == 2
			static const uint8_t pgmIsb_App_AnaIn_Ch_Array[] PROGMEM = { ISB_APP_ANAIN_0_CH, ISB_APP_ANAIN_1_CH };
			static const uint8_t pgmIsb_App_AnaIn_Obj_0_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_0, ISB_APP_ANAIN_1_OBJ_0 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_1_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_1, ISB_APP_ANAIN_1_OBJ_1 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_2_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_2, ISB_APP_ANAIN_1_OBJ_2 };
		#elif ISB_APP_ANAIN_MAX == 3
			static const uint8_t pgmIsb_App_AnaIn_Ch_Array[] PROGMEM = { ISB_APP_ANAIN_0_CH, ISB_APP_ANAIN_1_CH, ISB_APP_ANAIN_2_CH };
			static const uint8_t pgmIsb_App_AnaIn_Obj_0_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_0, ISB_APP_ANAIN_1_OBJ_0, ISB_APP_ANAIN_2_OBJ_0 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_1_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_1, ISB_APP_ANAIN_1_OBJ_1, ISB_APP_ANAIN_2_OBJ_1 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_2_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_2, ISB_APP_ANAIN_1_OBJ_2, ISB_APP_ANAIN_2_OBJ_2 };
		#elif ISB_APP_ANAIN_MAX == 4
			static const uint8_t pgmIsb_App_AnaIn_Ch_Array[] PROGMEM = { ISB_APP_ANAIN_0_CH, ISB_APP_ANAIN_1_CH, ISB_APP_ANAIN_2_CH, ISB_APP_ANAIN_3_CH };
			static const uint8_t pgmIsb_App_AnaIn_Obj_0_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_0, ISB_APP_ANAIN_1_OBJ_0, ISB_APP_ANAIN_2_OBJ_0, ISB_APP_ANAIN_3_OBJ_0 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_1_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_1, ISB_APP_ANAIN_1_OBJ_1, ISB_APP_ANAIN_2_OBJ_1, ISB_APP_ANAIN_3_OBJ_1 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_2_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_2, ISB_APP_ANAIN_1_OBJ_2, ISB_APP_ANAIN_2_OBJ_2, ISB_APP_ANAIN_3_OBJ_2 };
		#elif ISB_APP_ANAIN_MAX == 5
			static const uint8_t pgmIsb_App_AnaIn_Ch_Array[] PROGMEM = { ISB_APP_ANAIN_0_CH, ISB_APP_ANAIN_1_CH, ISB_APP_ANAIN_2_CH, ISB_APP_ANAIN_3_CH, ISB_APP_ANAIN_4_CH };
			static const uint8_t pgmIsb_App_AnaIn_Obj_0_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_0, ISB_APP_ANAIN_1_OBJ_0, ISB_APP_ANAIN_2_OBJ_0, ISB_APP_ANAIN_3_OBJ_0, ISB_APP_ANAIN_4_OBJ_0 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_1_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_1, ISB_APP_ANAIN_1_OBJ_1, ISB_APP_ANAIN_2_OBJ_1, ISB_APP_ANAIN_3_OBJ_1, ISB_APP_ANAIN_4_OBJ_1 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_2_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_2, ISB_APP_ANAIN_1_OBJ_2, ISB_APP_ANAIN_2_OBJ_2, ISB_APP_ANAIN_3_OBJ_2, ISB_APP_ANAIN_4_OBJ_2 };
		#elif ISB_APP_ANAIN_MAX == 6
			static const uint8_t pgmIsb_App_AnaIn_Ch_Array[] PROGMEM = { ISB_APP_ANAIN_0_CH, ISB_APP_ANAIN_1_CH, ISB_APP_ANAIN_2_CH, ISB_APP_ANAIN_3_CH, ISB_APP_ANAIN_4_CH, ISB_APP_ANAIN_5_CH };
			static const uint8_t pgmIsb_App_AnaIn_Obj_0_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_0, ISB_APP_ANAIN_1_OBJ_0, ISB_APP_ANAIN_2_OBJ_0, ISB_APP_ANAIN_3_OBJ_0, ISB_APP_ANAIN_4_OBJ_0, ISB_APP_ANAIN_5_OBJ_0 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_1_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_1, ISB_APP_ANAIN_1_OBJ_1, ISB_APP_ANAIN_2_OBJ_1, ISB_APP_ANAIN_3_OBJ_1, ISB_APP_ANAIN_4_OBJ_1, ISB_APP_ANAIN_5_OBJ_1 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_2_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_2, ISB_APP_ANAIN_1_OBJ_2, ISB_APP_ANAIN_2_OBJ_2, ISB_APP_ANAIN_3_OBJ_2, ISB_APP_ANAIN_4_OBJ_2, ISB_APP_ANAIN_5_OBJ_2 };
		#elif ISB_APP_ANAIN_MAX == 7
			static const uint8_t pgmIsb_App_AnaIn_Ch_Array[] PROGMEM = { ISB_APP_ANAIN_0_CH, ISB_APP_ANAIN_1_CH, ISB_APP_ANAIN_2_CH, ISB_APP_ANAIN_3_CH, ISB_APP_ANAIN_4_CH, ISB_APP_ANAIN_5_CH, ISB_APP_ANAIN_6_CH };
			static const uint8_t pgmIsb_App_AnaIn_Obj_0_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_0, ISB_APP_ANAIN_1_OBJ_0, ISB_APP_ANAIN_2_OBJ_0, ISB_APP_ANAIN_3_OBJ_0, ISB_APP_ANAIN_4_OBJ_0, ISB_APP_ANAIN_5_OBJ_0, ISB_APP_ANAIN_6_OBJ_0 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_1_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_1, ISB_APP_ANAIN_1_OBJ_1, ISB_APP_ANAIN_2_OBJ_1, ISB_APP_ANAIN_3_OBJ_1, ISB_APP_ANAIN_4_OBJ_1, ISB_APP_ANAIN_5_OBJ_1, ISB_APP_ANAIN_6_OBJ_1 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_2_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_2, ISB_APP_ANAIN_1_OBJ_2, ISB_APP_ANAIN_2_OBJ_2, ISB_APP_ANAIN_3_OBJ_2, ISB_APP_ANAIN_4_OBJ_2, ISB_APP_ANAIN_5_OBJ_2, ISB_APP_ANAIN_6_OBJ_2 };
		#elif ISB_APP_ANAIN_MAX == 8
			static const uint8_t pgmIsb_App_AnaIn_Ch_Array[] PROGMEM = { ISB_APP_ANAIN_0_CH, ISB_APP_ANAIN_1_CH, ISB_APP_ANAIN_2_CH, ISB_APP_ANAIN_3_CH, ISB_APP_ANAIN_4_CH, ISB_APP_ANAIN_5_CH, ISB_APP_ANAIN_6_CH, ISB_APP_ANAIN_7_CH };
			static const uint8_t pgmIsb_App_AnaIn_Obj_0_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_0, ISB_APP_ANAIN_1_OBJ_0, ISB_APP_ANAIN_2_OBJ_0, ISB_APP_ANAIN_3_OBJ_0, ISB_APP_ANAIN_4_OBJ_0, ISB_APP_ANAIN_5_OBJ_0, ISB_APP_ANAIN_6_OBJ_0, ISB_APP_ANAIN_7_OBJ_0 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_1_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_1, ISB_APP_ANAIN_1_OBJ_1, ISB_APP_ANAIN_2_OBJ_1, ISB_APP_ANAIN_3_OBJ_1, ISB_APP_ANAIN_4_OBJ_1, ISB_APP_ANAIN_5_OBJ_1, ISB_APP_ANAIN_6_OBJ_1, ISB_APP_ANAIN_7_OBJ_1 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_2_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_2, ISB_APP_ANAIN_1_OBJ_2, ISB_APP_ANAIN_2_OBJ_2, ISB_APP_ANAIN_3_OBJ_2, ISB_APP_ANAIN_4_OBJ_2, ISB_APP_ANAIN_5_OBJ_2, ISB_APP_ANAIN_6_OBJ_2, ISB_APP_ANAIN_7_OBJ_2 };
		#elif ISB_APP_ANAIN_MAX == 9
			static const uint8_t pgmIsb_App_AnaIn_Ch_Array[] PROGMEM = { ISB_APP_ANAIN_0_CH, ISB_APP_ANAIN_1_CH, ISB_APP_ANAIN_2_CH, ISB_APP_ANAIN_3_CH, ISB_APP_ANAIN_4_CH, ISB_APP_ANAIN_5_CH, ISB_APP_ANAIN_6_CH, ISB_APP_ANAIN_7_CH, ISB_APP_ANAIN_8_CH };
			static const uint8_t pgmIsb_App_AnaIn_Obj_0_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_0, ISB_APP_ANAIN_1_OBJ_0, ISB_APP_ANAIN_2_OBJ_0, ISB_APP_ANAIN_3_OBJ_0, ISB_APP_ANAIN_4_OBJ_0, ISB_APP_ANAIN_5_OBJ_0, ISB_APP_ANAIN_6_OBJ_0, ISB_APP_ANAIN_7_OBJ_0, ISB_APP_ANAIN_8_OBJ_0 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_1_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_1, ISB_APP_ANAIN_1_OBJ_1, ISB_APP_ANAIN_2_OBJ_1, ISB_APP_ANAIN_3_OBJ_1, ISB_APP_ANAIN_4_OBJ_1, ISB_APP_ANAIN_5_OBJ_1, ISB_APP_ANAIN_6_OBJ_1, ISB_APP_ANAIN_7_OBJ_1, ISB_APP_ANAIN_8_OBJ_1 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_2_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_2, ISB_APP_ANAIN_1_OBJ_2, ISB_APP_ANAIN_2_OBJ_2, ISB_APP_ANAIN_3_OBJ_2, ISB_APP_ANAIN_4_OBJ_2, ISB_APP_ANAIN_5_OBJ_2, ISB_APP_ANAIN_6_OBJ_2, ISB_APP_ANAIN_7_OBJ_2, ISB_APP_ANAIN_8_OBJ_2 };
		#elif ISB_APP_ANAIN_MAX == 10
			static const uint8_t pgmIsb_App_AnaIn_Ch_Array[] PROGMEM = { ISB_APP_ANAIN_0_CH, ISB_APP_ANAIN_1_CH, ISB_APP_ANAIN_2_CH, ISB_APP_ANAIN_3_CH, ISB_APP_ANAIN_4_CH, ISB_APP_ANAIN_5_CH, ISB_APP_ANAIN_6_CH, ISB_APP_ANAIN_7_CH, ISB_APP_ANAIN_8_CH, ISB_APP_ANAIN_9_CH };
			static const uint8_t pgmIsb_App_AnaIn_Obj_0_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_0, ISB_APP_ANAIN_1_OBJ_0, ISB_APP_ANAIN_2_OBJ_0, ISB_APP_ANAIN_3_OBJ_0, ISB_APP_ANAIN_4_OBJ_0, ISB_APP_ANAIN_5_OBJ_0, ISB_APP_ANAIN_6_OBJ_0, ISB_APP_ANAIN_7_OBJ_0, ISB_APP_ANAIN_8_OBJ_0, ISB_APP_ANAIN_9_OBJ_0 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_1_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_1, ISB_APP_ANAIN_1_OBJ_1, ISB_APP_ANAIN_2_OBJ_1, ISB_APP_ANAIN_3_OBJ_1, ISB_APP_ANAIN_4_OBJ_1, ISB_APP_ANAIN_5_OBJ_1, ISB_APP_ANAIN_6_OBJ_1, ISB_APP_ANAIN_7_OBJ_1, ISB_APP_ANAIN_8_OBJ_1, ISB_APP_ANAIN_9_OBJ_1 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_2_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_2, ISB_APP_ANAIN_1_OBJ_2, ISB_APP_ANAIN_2_OBJ_2, ISB_APP_ANAIN_3_OBJ_2, ISB_APP_ANAIN_4_OBJ_2, ISB_APP_ANAIN_5_OBJ_2, ISB_APP_ANAIN_6_OBJ_2, ISB_APP_ANAIN_7_OBJ_2, ISB_APP_ANAIN_8_OBJ_2, ISB_APP_ANAIN_9_OBJ_2 };
		#elif ISB_APP_ANAIN_MAX == 11
			static const uint8_t pgmIsb_App_AnaIn_Ch_Array[] PROGMEM = { ISB_APP_ANAIN_0_CH, ISB_APP_ANAIN_1_CH, ISB_APP_ANAIN_2_CH, ISB_APP_ANAIN_3_CH, ISB_APP_ANAIN_4_CH, ISB_APP_ANAIN_5_CH, ISB_APP_ANAIN_6_CH, ISB_APP_ANAIN_7_CH, ISB_APP_ANAIN_8_CH, ISB_APP_ANAIN_9_CH, ISB_APP_ANAIN_10_CH };
			static const uint8_t pgmIsb_App_AnaIn_Obj_0_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_0, ISB_APP_ANAIN_1_OBJ_0, ISB_APP_ANAIN_2_OBJ_0, ISB_APP_ANAIN_3_OBJ_0, ISB_APP_ANAIN_4_OBJ_0, ISB_APP_ANAIN_5_OBJ_0, ISB_APP_ANAIN_6_OBJ_0, ISB_APP_ANAIN_7_OBJ_0, ISB_APP_ANAIN_8_OBJ_0, ISB_APP_ANAIN_9_OBJ_0, ISB_APP_ANAIN_10_OBJ_0 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_1_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_1, ISB_APP_ANAIN_1_OBJ_1, ISB_APP_ANAIN_2_OBJ_1, ISB_APP_ANAIN_3_OBJ_1, ISB_APP_ANAIN_4_OBJ_1, ISB_APP_ANAIN_5_OBJ_1, ISB_APP_ANAIN_6_OBJ_1, ISB_APP_ANAIN_7_OBJ_1, ISB_APP_ANAIN_8_OBJ_1, ISB_APP_ANAIN_9_OBJ_1, ISB_APP_ANAIN_10_OBJ_1 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_2_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_2, ISB_APP_ANAIN_1_OBJ_2, ISB_APP_ANAIN_2_OBJ_2, ISB_APP_ANAIN_3_OBJ_2, ISB_APP_ANAIN_4_OBJ_2, ISB_APP_ANAIN_5_OBJ_2, ISB_APP_ANAIN_6_OBJ_2, ISB_APP_ANAIN_7_OBJ_2, ISB_APP_ANAIN_8_OBJ_2, ISB_APP_ANAIN_9_OBJ_2, ISB_APP_ANAIN_10_OBJ_2 };
		#elif ISB_APP_ANAIN_MAX == 12
			static const uint8_t pgmIsb_App_AnaIn_Ch_Array[] PROGMEM = { ISB_APP_ANAIN_0_CH, ISB_APP_ANAIN_1_CH, ISB_APP_ANAIN_2_CH, ISB_APP_ANAIN_3_CH, ISB_APP_ANAIN_4_CH, ISB_APP_ANAIN_5_CH, ISB_APP_ANAIN_6_CH, ISB_APP_ANAIN_7_CH, ISB_APP_ANAIN_8_CH, ISB_APP_ANAIN_9_CH, ISB_APP_ANAIN_10_CH, ISB_APP_ANAIN_11_CH };
			static const uint8_t pgmIsb_App_AnaIn_Obj_0_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_0, ISB_APP_ANAIN_1_OBJ_0, ISB_APP_ANAIN_2_OBJ_0, ISB_APP_ANAIN_3_OBJ_0, ISB_APP_ANAIN_4_OBJ_0, ISB_APP_ANAIN_5_OBJ_0, ISB_APP_ANAIN_6_OBJ_0, ISB_APP_ANAIN_7_OBJ_0, ISB_APP_ANAIN_8_OBJ_0, ISB_APP_ANAIN_9_OBJ_0, ISB_APP_ANAIN_10_OBJ_0, ISB_APP_ANAIN_11_OBJ_0 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_1_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_1, ISB_APP_ANAIN_1_OBJ_1, ISB_APP_ANAIN_2_OBJ_1, ISB_APP_ANAIN_3_OBJ_1, ISB_APP_ANAIN_4_OBJ_1, ISB_APP_ANAIN_5_OBJ_1, ISB_APP_ANAIN_6_OBJ_1, ISB_APP_ANAIN_7_OBJ_1, ISB_APP_ANAIN_8_OBJ_1, ISB_APP_ANAIN_9_OBJ_1, ISB_APP_ANAIN_10_OBJ_1, ISB_APP_ANAIN_11_OBJ_1 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_2_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_2, ISB_APP_ANAIN_1_OBJ_2, ISB_APP_ANAIN_2_OBJ_2, ISB_APP_ANAIN_3_OBJ_2, ISB_APP_ANAIN_4_OBJ_2, ISB_APP_ANAIN_5_OBJ_2, ISB_APP_ANAIN_6_OBJ_2, ISB_APP_ANAIN_7_OBJ_2, ISB_APP_ANAIN_8_OBJ_2, ISB_APP_ANAIN_9_OBJ_2, ISB_APP_ANAIN_10_OBJ_2, ISB_APP_ANAIN_11_OBJ_2 };
		#elif ISB_APP_ANAIN_MAX == 13
			static const uint8_t pgmIsb_App_AnaIn_Ch_Array[] PROGMEM = { ISB_APP_ANAIN_0_CH, ISB_APP_ANAIN_1_CH, ISB_APP_ANAIN_2_CH, ISB_APP_ANAIN_3_CH, ISB_APP_ANAIN_4_CH, ISB_APP_ANAIN_5_CH, ISB_APP_ANAIN_6_CH, ISB_APP_ANAIN_7_CH, ISB_APP_ANAIN_8_CH, ISB_APP_ANAIN_9_CH, ISB_APP_ANAIN_10_CH, ISB_APP_ANAIN_11_CH, ISB_APP_ANAIN_12_CH };
			static const uint8_t pgmIsb_App_AnaIn_Obj_0_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_0, ISB_APP_ANAIN_1_OBJ_0, ISB_APP_ANAIN_2_OBJ_0, ISB_APP_ANAIN_3_OBJ_0, ISB_APP_ANAIN_4_OBJ_0, ISB_APP_ANAIN_5_OBJ_0, ISB_APP_ANAIN_6_OBJ_0, ISB_APP_ANAIN_7_OBJ_0, ISB_APP_ANAIN_8_OBJ_0, ISB_APP_ANAIN_9_OBJ_0, ISB_APP_ANAIN_10_OBJ_0, ISB_APP_ANAIN_11_OBJ_0, ISB_APP_ANAIN_12_OBJ_0 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_1_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_1, ISB_APP_ANAIN_1_OBJ_1, ISB_APP_ANAIN_2_OBJ_1, ISB_APP_ANAIN_3_OBJ_1, ISB_APP_ANAIN_4_OBJ_1, ISB_APP_ANAIN_5_OBJ_1, ISB_APP_ANAIN_6_OBJ_1, ISB_APP_ANAIN_7_OBJ_1, ISB_APP_ANAIN_8_OBJ_1, ISB_APP_ANAIN_9_OBJ_1, ISB_APP_ANAIN_10_OBJ_1, ISB_APP_ANAIN_11_OBJ_1, ISB_APP_ANAIN_12_OBJ_1 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_2_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_2, ISB_APP_ANAIN_1_OBJ_2, ISB_APP_ANAIN_2_OBJ_2, ISB_APP_ANAIN_3_OBJ_2, ISB_APP_ANAIN_4_OBJ_2, ISB_APP_ANAIN_5_OBJ_2, ISB_APP_ANAIN_6_OBJ_2, ISB_APP_ANAIN_7_OBJ_2, ISB_APP_ANAIN_8_OBJ_2, ISB_APP_ANAIN_9_OBJ_2, ISB_APP_ANAIN_10_OBJ_2, ISB_APP_ANAIN_11_OBJ_2, ISB_APP_ANAIN_12_OBJ_2 };
		#elif ISB_APP_ANAIN_MAX == 14
			static const uint8_t pgmIsb_App_AnaIn_Ch_Array[] PROGMEM = { ISB_APP_ANAIN_0_CH, ISB_APP_ANAIN_1_CH, ISB_APP_ANAIN_2_CH, ISB_APP_ANAIN_3_CH, ISB_APP_ANAIN_4_CH, ISB_APP_ANAIN_5_CH, ISB_APP_ANAIN_6_CH, ISB_APP_ANAIN_7_CH, ISB_APP_ANAIN_8_CH, ISB_APP_ANAIN_9_CH, ISB_APP_ANAIN_10_CH, ISB_APP_ANAIN_11_CH, ISB_APP_ANAIN_12_CH, ISB_APP_ANAIN_13_CH };
			static const uint8_t pgmIsb_App_AnaIn_Obj_0_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_0, ISB_APP_ANAIN_1_OBJ_0, ISB_APP_ANAIN_2_OBJ_0, ISB_APP_ANAIN_3_OBJ_0, ISB_APP_ANAIN_4_OBJ_0, ISB_APP_ANAIN_5_OBJ_0, ISB_APP_ANAIN_6_OBJ_0, ISB_APP_ANAIN_7_OBJ_0, ISB_APP_ANAIN_8_OBJ_0, ISB_APP_ANAIN_9_OBJ_0, ISB_APP_ANAIN_10_OBJ_0, ISB_APP_ANAIN_11_OBJ_0, ISB_APP_ANAIN_12_OBJ_0, ISB_APP_ANAIN_13_OBJ_0 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_1_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_1, ISB_APP_ANAIN_1_OBJ_1, ISB_APP_ANAIN_2_OBJ_1, ISB_APP_ANAIN_3_OBJ_1, ISB_APP_ANAIN_4_OBJ_1, ISB_APP_ANAIN_5_OBJ_1, ISB_APP_ANAIN_6_OBJ_1, ISB_APP_ANAIN_7_OBJ_1, ISB_APP_ANAIN_8_OBJ_1, ISB_APP_ANAIN_9_OBJ_1, ISB_APP_ANAIN_10_OBJ_1, ISB_APP_ANAIN_11_OBJ_1, ISB_APP_ANAIN_12_OBJ_1, ISB_APP_ANAIN_13_OBJ_1 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_2_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_2, ISB_APP_ANAIN_1_OBJ_2, ISB_APP_ANAIN_2_OBJ_2, ISB_APP_ANAIN_3_OBJ_2, ISB_APP_ANAIN_4_OBJ_2, ISB_APP_ANAIN_5_OBJ_2, ISB_APP_ANAIN_6_OBJ_2, ISB_APP_ANAIN_7_OBJ_2, ISB_APP_ANAIN_8_OBJ_2, ISB_APP_ANAIN_9_OBJ_2, ISB_APP_ANAIN_10_OBJ_2, ISB_APP_ANAIN_11_OBJ_2, ISB_APP_ANAIN_12_OBJ_2, ISB_APP_ANAIN_13_OBJ_2 };
		#elif ISB_APP_ANAIN_MAX == 15
			static const uint8_t pgmIsb_App_AnaIn_Ch_Array[] PROGMEM = { ISB_APP_ANAIN_0_CH, ISB_APP_ANAIN_1_CH, ISB_APP_ANAIN_2_CH, ISB_APP_ANAIN_3_CH, ISB_APP_ANAIN_4_CH, ISB_APP_ANAIN_5_CH, ISB_APP_ANAIN_6_CH, ISB_APP_ANAIN_7_CH, ISB_APP_ANAIN_8_CH, ISB_APP_ANAIN_9_CH, ISB_APP_ANAIN_10_CH, ISB_APP_ANAIN_11_CH, ISB_APP_ANAIN_12_CH, ISB_APP_ANAIN_13_CH, ISB_APP_ANAIN_14_CH };
			static const uint8_t pgmIsb_App_AnaIn_Obj_0_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_0, ISB_APP_ANAIN_1_OBJ_0, ISB_APP_ANAIN_2_OBJ_0, ISB_APP_ANAIN_3_OBJ_0, ISB_APP_ANAIN_4_OBJ_0, ISB_APP_ANAIN_5_OBJ_0, ISB_APP_ANAIN_6_OBJ_0, ISB_APP_ANAIN_7_OBJ_0, ISB_APP_ANAIN_8_OBJ_0, ISB_APP_ANAIN_9_OBJ_0, ISB_APP_ANAIN_10_OBJ_0, ISB_APP_ANAIN_11_OBJ_0, ISB_APP_ANAIN_12_OBJ_0, ISB_APP_ANAIN_13_OBJ_0, ISB_APP_ANAIN_14_OBJ_0 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_1_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_1, ISB_APP_ANAIN_1_OBJ_1, ISB_APP_ANAIN_2_OBJ_1, ISB_APP_ANAIN_3_OBJ_1, ISB_APP_ANAIN_4_OBJ_1, ISB_APP_ANAIN_5_OBJ_1, ISB_APP_ANAIN_6_OBJ_1, ISB_APP_ANAIN_7_OBJ_1, ISB_APP_ANAIN_8_OBJ_1, ISB_APP_ANAIN_9_OBJ_1, ISB_APP_ANAIN_10_OBJ_1, ISB_APP_ANAIN_11_OBJ_1, ISB_APP_ANAIN_12_OBJ_1, ISB_APP_ANAIN_13_OBJ_1, ISB_APP_ANAIN_14_OBJ_1 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_2_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_2, ISB_APP_ANAIN_1_OBJ_2, ISB_APP_ANAIN_2_OBJ_2, ISB_APP_ANAIN_3_OBJ_2, ISB_APP_ANAIN_4_OBJ_2, ISB_APP_ANAIN_5_OBJ_2, ISB_APP_ANAIN_6_OBJ_2, ISB_APP_ANAIN_7_OBJ_2, ISB_APP_ANAIN_8_OBJ_2, ISB_APP_ANAIN_9_OBJ_2, ISB_APP_ANAIN_10_OBJ_2, ISB_APP_ANAIN_11_OBJ_2, ISB_APP_ANAIN_12_OBJ_2, ISB_APP_ANAIN_13_OBJ_2, ISB_APP_ANAIN_14_OBJ_2 };
		#elif ISB_APP_ANAIN_MAX == 16
			static const uint8_t pgmIsb_App_AnaIn_Ch_Array[] PROGMEM = { ISB_APP_ANAIN_0_CH, ISB_APP_ANAIN_1_CH, ISB_APP_ANAIN_2_CH, ISB_APP_ANAIN_3_CH, ISB_APP_ANAIN_4_CH, ISB_APP_ANAIN_5_CH, ISB_APP_ANAIN_6_CH, ISB_APP_ANAIN_7_CH, ISB_APP_ANAIN_8_CH, ISB_APP_ANAIN_9_CH, ISB_APP_ANAIN_10_CH, ISB_APP_ANAIN_11_CH, ISB_APP_ANAIN_12_CH, ISB_APP_ANAIN_13_CH, ISB_APP_ANAIN_14_CH, ISB_APP_ANAIN_15_CH };
			static const uint8_t pgmIsb_App_AnaIn_Obj_0_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_0, ISB_APP_ANAIN_1_OBJ_0, ISB_APP_ANAIN_2_OBJ_0, ISB_APP_ANAIN_3_OBJ_0, ISB_APP_ANAIN_4_OBJ_0, ISB_APP_ANAIN_5_OBJ_0, ISB_APP_ANAIN_6_OBJ_0, ISB_APP_ANAIN_7_OBJ_0, ISB_APP_ANAIN_8_OBJ_0, ISB_APP_ANAIN_9_OBJ_0, ISB_APP_ANAIN_10_OBJ_0, ISB_APP_ANAIN_11_OBJ_0, ISB_APP_ANAIN_12_OBJ_0, ISB_APP_ANAIN_13_OBJ_0, ISB_APP_ANAIN_14_OBJ_0, ISB_APP_ANAIN_15_OBJ_0 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_1_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_1, ISB_APP_ANAIN_1_OBJ_1, ISB_APP_ANAIN_2_OBJ_1, ISB_APP_ANAIN_3_OBJ_1, ISB_APP_ANAIN_4_OBJ_1, ISB_APP_ANAIN_5_OBJ_1, ISB_APP_ANAIN_6_OBJ_1, ISB_APP_ANAIN_7_OBJ_1, ISB_APP_ANAIN_8_OBJ_1, ISB_APP_ANAIN_9_OBJ_1, ISB_APP_ANAIN_10_OBJ_1, ISB_APP_ANAIN_11_OBJ_1, ISB_APP_ANAIN_12_OBJ_1, ISB_APP_ANAIN_13_OBJ_1, ISB_APP_ANAIN_14_OBJ_1, ISB_APP_ANAIN_15_OBJ_1 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_2_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_2, ISB_APP_ANAIN_1_OBJ_2, ISB_APP_ANAIN_2_OBJ_2, ISB_APP_ANAIN_3_OBJ_2, ISB_APP_ANAIN_4_OBJ_2, ISB_APP_ANAIN_5_OBJ_2, ISB_APP_ANAIN_6_OBJ_2, ISB_APP_ANAIN_7_OBJ_2, ISB_APP_ANAIN_8_OBJ_2, ISB_APP_ANAIN_9_OBJ_2, ISB_APP_ANAIN_10_OBJ_2, ISB_APP_ANAIN_11_OBJ_2, ISB_APP_ANAIN_12_OBJ_2, ISB_APP_ANAIN_13_OBJ_2, ISB_APP_ANAIN_14_OBJ_2, ISB_APP_ANAIN_15_OBJ_2 };
		#else
			#error ISB_APP_ANAIN_MAX
		#endif /* ISB_APP_ANAIN_MAX == ? */

		typedef struct Isb_App_AnaIn_t Isb_App_AnaIn_t;

		struct Isb_App_AnaIn_t
		{
			uint16_t TimeCount;
			uint8_t Cfg0;
			uint8_t Cfg1;
			uint8_t Cfg2;
			uint16_t Cfg_Switch1On;
			uint16_t Cfg_Switch1Off;
			uint16_t Cfg_Switch2On;
			uint16_t Cfg_Switch2Off;
			uint16_t Value;
		};

		static uint8_t Isb_App_AnaIn_Ctrl = 0;
		static uint16_t Isb_App_AnaIn_IrqExec = 0;
		static Isb_App_AnaIn_t Isb_App_AnaIn[ISB_APP_ANAIN_MAX];

	#endif /* ISB_APP_ANAIN_MAX */



	#if defined(ISB_APP_CLOCK_MAX)

		#if ISB_APP_CLOCK_MAX == 1
			static const uint8_t pgmIsb_App_Clock_Ch_Array[] PROGMEM = { ISB_APP_CLOCK_0_CH };
			static const uint8_t pgmIsb_App_Clock_Obj_0_Array[] PROGMEM = { ISB_APP_CLOCK_0_OBJ_0 };
			static const uint8_t pgmIsb_App_Clock_Obj_1_Array[] PROGMEM = { ISB_APP_CLOCK_0_OBJ_1 };
		#else
			#error ISB_APP_CLOCK_MAX
		#endif /* ISB_APP_CLOCK_MAX == ? */

//		typedef struct Isb_App_Clock_t Isb_App_Clock_t;

//		struct Isb_App_Clock_t
//		{
//			uint8_t Ch;
//			uint8_t Obj_Sensor;
//			uint16_t TimeCount;
//			uint8_t Typ;
//			uint8_t Cfg0;
//			uint8_t Cfg1;
//			uint8_t Cfg2;
//			uint16_t Min;
//			uint16_t Max;
//			uint16_t Value;
//		};

		static uint8_t Isb_App_Clock_Ctrl = 0;
		static uint16_t Isb_App_Clock_IrqExec = 0;
//		static Isb_App_Clock_t Isb_App_Clock[ISB_APP_CLOCK_MAX];

	#endif /* ISB_APP_CLOCK_MAX */



	#if defined(ISB_APP_DIGIN_MAX)

		#if ISB_APP_DIGIN_MAX == 1
			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH };
			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1 };
			static const uint8_t pgmIsb_App_DigIn_Obj_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_2 };
		#elif ISB_APP_DIGIN_MAX == 2
			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH, ISB_APP_DIGIN_1_CH };
			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0, ISB_APP_DIGIN_1_PIN0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_0, ISB_APP_DIGIN_1_OBJ_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1, ISB_APP_DIGIN_1_OBJ_1 };
			static const uint8_t pgmIsb_App_DigIn_Obj_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_2, ISB_APP_DIGIN_1_OBJ_2 };
		#elif ISB_APP_DIGIN_MAX == 3
			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH, ISB_APP_DIGIN_1_CH, ISB_APP_DIGIN_2_CH };
			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0, ISB_APP_DIGIN_1_PIN0, ISB_APP_DIGIN_2_PIN0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_0, ISB_APP_DIGIN_1_OBJ_0, ISB_APP_DIGIN_2_OBJ_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1, ISB_APP_DIGIN_1_OBJ_1, ISB_APP_DIGIN_2_OBJ_1 };
			static const uint8_t pgmIsb_App_DigIn_Obj_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_2, ISB_APP_DIGIN_1_OBJ_2, ISB_APP_DIGIN_2_OBJ_2 };
		#elif ISB_APP_DIGIN_MAX == 4
			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH, ISB_APP_DIGIN_1_CH, ISB_APP_DIGIN_2_CH, ISB_APP_DIGIN_3_CH };
			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0, ISB_APP_DIGIN_1_PIN0, ISB_APP_DIGIN_2_PIN0, ISB_APP_DIGIN_3_PIN0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_0, ISB_APP_DIGIN_1_OBJ_0, ISB_APP_DIGIN_2_OBJ_0, ISB_APP_DIGIN_3_OBJ_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1, ISB_APP_DIGIN_1_OBJ_1, ISB_APP_DIGIN_2_OBJ_1, ISB_APP_DIGIN_3_OBJ_1 };
			static const uint8_t pgmIsb_App_DigIn_Obj_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_2, ISB_APP_DIGIN_1_OBJ_2, ISB_APP_DIGIN_2_OBJ_2, ISB_APP_DIGIN_3_OBJ_2 };
		#elif ISB_APP_DIGIN_MAX == 5
			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH, ISB_APP_DIGIN_1_CH, ISB_APP_DIGIN_2_CH, ISB_APP_DIGIN_3_CH, ISB_APP_DIGIN_4_CH };
			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0, ISB_APP_DIGIN_1_PIN0, ISB_APP_DIGIN_2_PIN0, ISB_APP_DIGIN_3_PIN0, ISB_APP_DIGIN_4_PIN0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_0, ISB_APP_DIGIN_1_OBJ_0, ISB_APP_DIGIN_2_OBJ_0, ISB_APP_DIGIN_3_OBJ_0, ISB_APP_DIGIN_4_OBJ_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1, ISB_APP_DIGIN_1_OBJ_1, ISB_APP_DIGIN_2_OBJ_1, ISB_APP_DIGIN_3_OBJ_1, ISB_APP_DIGIN_4_OBJ_1 };
			static const uint8_t pgmIsb_App_DigIn_Obj_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_2, ISB_APP_DIGIN_1_OBJ_2, ISB_APP_DIGIN_2_OBJ_2, ISB_APP_DIGIN_3_OBJ_2, ISB_APP_DIGIN_4_OBJ_2 };
		#elif ISB_APP_DIGIN_MAX == 6
			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH, ISB_APP_DIGIN_1_CH, ISB_APP_DIGIN_2_CH, ISB_APP_DIGIN_3_CH, ISB_APP_DIGIN_4_CH, ISB_APP_DIGIN_5_CH };
			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0, ISB_APP_DIGIN_1_PIN0, ISB_APP_DIGIN_2_PIN0, ISB_APP_DIGIN_3_PIN0, ISB_APP_DIGIN_4_PIN0, ISB_APP_DIGIN_5_PIN0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_0, ISB_APP_DIGIN_1_OBJ_0, ISB_APP_DIGIN_2_OBJ_0, ISB_APP_DIGIN_3_OBJ_0, ISB_APP_DIGIN_4_OBJ_0, ISB_APP_DIGIN_5_OBJ_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1, ISB_APP_DIGIN_1_OBJ_1, ISB_APP_DIGIN_2_OBJ_1, ISB_APP_DIGIN_3_OBJ_1, ISB_APP_DIGIN_4_OBJ_1, ISB_APP_DIGIN_5_OBJ_1 };
			static const uint8_t pgmIsb_App_DigIn_Obj_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_2, ISB_APP_DIGIN_1_OBJ_2, ISB_APP_DIGIN_2_OBJ_2, ISB_APP_DIGIN_3_OBJ_2, ISB_APP_DIGIN_4_OBJ_2, ISB_APP_DIGIN_5_OBJ_2 };
		#elif ISB_APP_DIGIN_MAX == 7
			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH, ISB_APP_DIGIN_1_CH, ISB_APP_DIGIN_2_CH, ISB_APP_DIGIN_3_CH, ISB_APP_DIGIN_4_CH, ISB_APP_DIGIN_5_CH, ISB_APP_DIGIN_6_CH };
			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0, ISB_APP_DIGIN_1_PIN0, ISB_APP_DIGIN_2_PIN0, ISB_APP_DIGIN_3_PIN0, ISB_APP_DIGIN_4_PIN0, ISB_APP_DIGIN_5_PIN0, ISB_APP_DIGIN_6_PIN0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_0, ISB_APP_DIGIN_1_OBJ_0, ISB_APP_DIGIN_2_OBJ_0, ISB_APP_DIGIN_3_OBJ_0, ISB_APP_DIGIN_4_OBJ_0, ISB_APP_DIGIN_5_OBJ_0, ISB_APP_DIGIN_6_OBJ_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1, ISB_APP_DIGIN_1_OBJ_1, ISB_APP_DIGIN_2_OBJ_1, ISB_APP_DIGIN_3_OBJ_1, ISB_APP_DIGIN_4_OBJ_1, ISB_APP_DIGIN_5_OBJ_1, ISB_APP_DIGIN_6_OBJ_1 };
			static const uint8_t pgmIsb_App_DigIn_Obj_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_2, ISB_APP_DIGIN_1_OBJ_2, ISB_APP_DIGIN_2_OBJ_2, ISB_APP_DIGIN_3_OBJ_2, ISB_APP_DIGIN_4_OBJ_2, ISB_APP_DIGIN_5_OBJ_2, ISB_APP_DIGIN_6_OBJ_2 };
		#elif ISB_APP_DIGIN_MAX == 8
			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH, ISB_APP_DIGIN_1_CH, ISB_APP_DIGIN_2_CH, ISB_APP_DIGIN_3_CH, ISB_APP_DIGIN_4_CH, ISB_APP_DIGIN_5_CH, ISB_APP_DIGIN_6_CH, ISB_APP_DIGIN_7_CH };
			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0, ISB_APP_DIGIN_1_PIN0, ISB_APP_DIGIN_2_PIN0, ISB_APP_DIGIN_3_PIN0, ISB_APP_DIGIN_4_PIN0, ISB_APP_DIGIN_5_PIN0, ISB_APP_DIGIN_6_PIN0, ISB_APP_DIGIN_7_PIN0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_0, ISB_APP_DIGIN_1_OBJ_0, ISB_APP_DIGIN_2_OBJ_0, ISB_APP_DIGIN_3_OBJ_0, ISB_APP_DIGIN_4_OBJ_0, ISB_APP_DIGIN_5_OBJ_0, ISB_APP_DIGIN_6_OBJ_0, ISB_APP_DIGIN_7_OBJ_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1, ISB_APP_DIGIN_1_OBJ_1, ISB_APP_DIGIN_2_OBJ_1, ISB_APP_DIGIN_3_OBJ_1, ISB_APP_DIGIN_4_OBJ_1, ISB_APP_DIGIN_5_OBJ_1, ISB_APP_DIGIN_6_OBJ_1, ISB_APP_DIGIN_7_OBJ_1 };
			static const uint8_t pgmIsb_App_DigIn_Obj_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_2, ISB_APP_DIGIN_1_OBJ_2, ISB_APP_DIGIN_2_OBJ_2, ISB_APP_DIGIN_3_OBJ_2, ISB_APP_DIGIN_4_OBJ_2, ISB_APP_DIGIN_5_OBJ_2, ISB_APP_DIGIN_6_OBJ_2, ISB_APP_DIGIN_7_OBJ_2 };
//		#elif ISB_APP_DIGIN_MAX == 9
//		#elif ISB_APP_DIGIN_MAX == 10
//		#elif ISB_APP_DIGIN_MAX == 11
//		#elif ISB_APP_DIGIN_MAX == 12
//		#elif ISB_APP_DIGIN_MAX == 13
//		#elif ISB_APP_DIGIN_MAX == 14
//		#elif ISB_APP_DIGIN_MAX == 15
//		#elif ISB_APP_DIGIN_MAX == 16
		#else
			#error ISB_APP_DIGIN_MAX
		#endif /* ISB_APP_DIGIN_MAX == ? */

		typedef struct Isb_App_DigIn_t Isb_App_DigIn_t;

		struct Isb_App_DigIn_t
		{
			uint8_t Cfg0;
			uint8_t Cfg1;
			uint8_t Cfg2;
			uint8_t Cfg3;
			uint8_t Value;
			uint8_t Event;
			uint8_t CountLow;
			uint8_t CountHigh;
		};

		static uint8_t Isb_App_DigIn_Ctrl = 0;
		static uint16_t Isb_App_DigIn_IrqExec = 0;
		static Isb_App_DigIn_t Isb_App_DigIn[ISB_APP_DIGIN_MAX];

	#endif /* ISB_APP_DIGIN_MAX */



	#if defined(ISB_APP_DIGOUT_MAX)

		#if ISB_APP_DIGOUT_MAX == 1
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_0 };
			#if ISB_APP_DIGOUT_FEATURE_RESULT == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1 };
			#endif /* ISB_APP_DIGOUT_FEATURE_RESULT == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_2 };
			#endif /* ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_3 };
			#endif /* ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE */
		#elif ISB_APP_DIGOUT_MAX == 2
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_0, ISB_APP_DIGOUT_1_OBJ_0 };
			#if ISB_APP_DIGOUT_FEATURE_RESULT == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1, ISB_APP_DIGOUT_1_OBJ_1 };
			#endif /* ISB_APP_DIGOUT_FEATURE_RESULT == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_2, ISB_APP_DIGOUT_1_OBJ_2 };
			#endif /* ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_3, ISB_APP_DIGOUT_1_OBJ_3 };
			#endif /* ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE */
		#elif ISB_APP_DIGOUT_MAX == 3
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_0, ISB_APP_DIGOUT_1_OBJ_0, ISB_APP_DIGOUT_2_OBJ_0 };
			#if ISB_APP_DIGOUT_FEATURE_RESULT == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1, ISB_APP_DIGOUT_1_OBJ_1, ISB_APP_DIGOUT_2_OBJ_1 };
			#endif /* ISB_APP_DIGOUT_FEATURE_RESULT == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_2, ISB_APP_DIGOUT_1_OBJ_2, ISB_APP_DIGOUT_2_OBJ_2 };
			#endif /* ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_3, ISB_APP_DIGOUT_1_OBJ_3, ISB_APP_DIGOUT_2_OBJ_3 };
			#endif /* ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE */
		#elif ISB_APP_DIGOUT_MAX == 4
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_0, ISB_APP_DIGOUT_1_OBJ_0, ISB_APP_DIGOUT_2_OBJ_0, ISB_APP_DIGOUT_3_OBJ_0 };
			#if ISB_APP_DIGOUT_FEATURE_RESULT == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1, ISB_APP_DIGOUT_1_OBJ_1, ISB_APP_DIGOUT_2_OBJ_1, ISB_APP_DIGOUT_3_OBJ_1 };
			#endif /* ISB_APP_DIGOUT_FEATURE_RESULT == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_2, ISB_APP_DIGOUT_1_OBJ_2, ISB_APP_DIGOUT_2_OBJ_2, ISB_APP_DIGOUT_3_OBJ_2 };
			#endif /* ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_3, ISB_APP_DIGOUT_1_OBJ_3, ISB_APP_DIGOUT_2_OBJ_3, ISB_APP_DIGOUT_3_OBJ_3 };
			#endif /* ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE */
		#elif ISB_APP_DIGOUT_MAX == 5
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_0, ISB_APP_DIGOUT_1_OBJ_0, ISB_APP_DIGOUT_2_OBJ_0, ISB_APP_DIGOUT_3_OBJ_0, ISB_APP_DIGOUT_4_OBJ_0 };
			#if ISB_APP_DIGOUT_FEATURE_RESULT == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1, ISB_APP_DIGOUT_1_OBJ_1, ISB_APP_DIGOUT_2_OBJ_1, ISB_APP_DIGOUT_3_OBJ_1, ISB_APP_DIGOUT_4_OBJ_1 };
			#endif /* ISB_APP_DIGOUT_FEATURE_RESULT == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_2, ISB_APP_DIGOUT_1_OBJ_2, ISB_APP_DIGOUT_2_OBJ_2, ISB_APP_DIGOUT_3_OBJ_2, ISB_APP_DIGOUT_4_OBJ_2 };
			#endif /* ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_3, ISB_APP_DIGOUT_1_OBJ_3, ISB_APP_DIGOUT_2_OBJ_3, ISB_APP_DIGOUT_3_OBJ_3, ISB_APP_DIGOUT_4_OBJ_3 };
			#endif /* ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE */
		#elif ISB_APP_DIGOUT_MAX == 6
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH, ISB_APP_DIGOUT_5_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0, ISB_APP_DIGOUT_5_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1, ISB_APP_DIGOUT_5_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_0, ISB_APP_DIGOUT_1_OBJ_0, ISB_APP_DIGOUT_2_OBJ_0, ISB_APP_DIGOUT_3_OBJ_0, ISB_APP_DIGOUT_4_OBJ_0, ISB_APP_DIGOUT_5_OBJ_0 };
			#if ISB_APP_DIGOUT_FEATURE_RESULT == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1, ISB_APP_DIGOUT_1_OBJ_1, ISB_APP_DIGOUT_2_OBJ_1, ISB_APP_DIGOUT_3_OBJ_1, ISB_APP_DIGOUT_4_OBJ_1, ISB_APP_DIGOUT_5_OBJ_1 };
			#endif /* ISB_APP_DIGOUT_FEATURE_RESULT == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_2, ISB_APP_DIGOUT_1_OBJ_2, ISB_APP_DIGOUT_2_OBJ_2, ISB_APP_DIGOUT_3_OBJ_2, ISB_APP_DIGOUT_4_OBJ_2, ISB_APP_DIGOUT_5_OBJ_2 };
			#endif /* ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_3, ISB_APP_DIGOUT_1_OBJ_3, ISB_APP_DIGOUT_2_OBJ_3, ISB_APP_DIGOUT_3_OBJ_3, ISB_APP_DIGOUT_4_OBJ_3, ISB_APP_DIGOUT_5_OBJ_3 };
			#endif /* ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE */
		#elif ISB_APP_DIGOUT_MAX == 7
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH, ISB_APP_DIGOUT_5_CH, ISB_APP_DIGOUT_6_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0, ISB_APP_DIGOUT_5_PIN0, ISB_APP_DIGOUT_6_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1, ISB_APP_DIGOUT_5_PIN1, ISB_APP_DIGOUT_6_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_0, ISB_APP_DIGOUT_1_OBJ_0, ISB_APP_DIGOUT_2_OBJ_0, ISB_APP_DIGOUT_3_OBJ_0, ISB_APP_DIGOUT_4_OBJ_0, ISB_APP_DIGOUT_5_OBJ_0, ISB_APP_DIGOUT_6_OBJ_0 };
			#if ISB_APP_DIGOUT_FEATURE_RESULT == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1, ISB_APP_DIGOUT_1_OBJ_1, ISB_APP_DIGOUT_2_OBJ_1, ISB_APP_DIGOUT_3_OBJ_1, ISB_APP_DIGOUT_4_OBJ_1, ISB_APP_DIGOUT_5_OBJ_1, ISB_APP_DIGOUT_6_OBJ_1 };
			#endif /* ISB_APP_DIGOUT_FEATURE_RESULT == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_2, ISB_APP_DIGOUT_1_OBJ_2, ISB_APP_DIGOUT_2_OBJ_2, ISB_APP_DIGOUT_3_OBJ_2, ISB_APP_DIGOUT_4_OBJ_2, ISB_APP_DIGOUT_5_OBJ_2, ISB_APP_DIGOUT_6_OBJ_2 };
			#endif /* ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_3, ISB_APP_DIGOUT_1_OBJ_3, ISB_APP_DIGOUT_2_OBJ_3, ISB_APP_DIGOUT_3_OBJ_3, ISB_APP_DIGOUT_4_OBJ_3, ISB_APP_DIGOUT_5_OBJ_3, ISB_APP_DIGOUT_6_OBJ_3 };
			#endif /* ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE */
		#elif ISB_APP_DIGOUT_MAX == 8
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH, ISB_APP_DIGOUT_5_CH, ISB_APP_DIGOUT_6_CH, ISB_APP_DIGOUT_7_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0, ISB_APP_DIGOUT_5_PIN0, ISB_APP_DIGOUT_6_PIN0, ISB_APP_DIGOUT_7_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1, ISB_APP_DIGOUT_5_PIN1, ISB_APP_DIGOUT_6_PIN1, ISB_APP_DIGOUT_7_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_0, ISB_APP_DIGOUT_1_OBJ_0, ISB_APP_DIGOUT_2_OBJ_0, ISB_APP_DIGOUT_3_OBJ_0, ISB_APP_DIGOUT_4_OBJ_0, ISB_APP_DIGOUT_5_OBJ_0, ISB_APP_DIGOUT_6_OBJ_0, ISB_APP_DIGOUT_7_OBJ_0 };
			#if ISB_APP_DIGOUT_FEATURE_RESULT == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1, ISB_APP_DIGOUT_1_OBJ_1, ISB_APP_DIGOUT_2_OBJ_1, ISB_APP_DIGOUT_3_OBJ_1, ISB_APP_DIGOUT_4_OBJ_1, ISB_APP_DIGOUT_5_OBJ_1, ISB_APP_DIGOUT_6_OBJ_1, ISB_APP_DIGOUT_7_OBJ_1 };
			#endif /* ISB_APP_DIGOUT_FEATURE_RESULT == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_2, ISB_APP_DIGOUT_1_OBJ_2, ISB_APP_DIGOUT_2_OBJ_2, ISB_APP_DIGOUT_3_OBJ_2, ISB_APP_DIGOUT_4_OBJ_2, ISB_APP_DIGOUT_5_OBJ_2, ISB_APP_DIGOUT_6_OBJ_2, ISB_APP_DIGOUT_7_OBJ_2 };
			#endif /* ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_3, ISB_APP_DIGOUT_1_OBJ_3, ISB_APP_DIGOUT_2_OBJ_3, ISB_APP_DIGOUT_3_OBJ_3, ISB_APP_DIGOUT_4_OBJ_3, ISB_APP_DIGOUT_5_OBJ_3, ISB_APP_DIGOUT_6_OBJ_3, ISB_APP_DIGOUT_7_OBJ_3 };
			#endif /* ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE */
		#elif ISB_APP_DIGOUT_MAX == 9
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH, ISB_APP_DIGOUT_5_CH, ISB_APP_DIGOUT_6_CH, ISB_APP_DIGOUT_7_CH, ISB_APP_DIGOUT_8_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0, ISB_APP_DIGOUT_5_PIN0, ISB_APP_DIGOUT_6_PIN0, ISB_APP_DIGOUT_7_PIN0, ISB_APP_DIGOUT_8_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1, ISB_APP_DIGOUT_5_PIN1, ISB_APP_DIGOUT_6_PIN1, ISB_APP_DIGOUT_7_PIN1, ISB_APP_DIGOUT_8_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_0, ISB_APP_DIGOUT_1_OBJ_0, ISB_APP_DIGOUT_2_OBJ_0, ISB_APP_DIGOUT_3_OBJ_0, ISB_APP_DIGOUT_4_OBJ_0, ISB_APP_DIGOUT_5_OBJ_0, ISB_APP_DIGOUT_6_OBJ_0, ISB_APP_DIGOUT_7_OBJ_0, ISB_APP_DIGOUT_8_OBJ_0 };
			#if ISB_APP_DIGOUT_FEATURE_RESULT == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1, ISB_APP_DIGOUT_1_OBJ_1, ISB_APP_DIGOUT_2_OBJ_1, ISB_APP_DIGOUT_3_OBJ_1, ISB_APP_DIGOUT_4_OBJ_1, ISB_APP_DIGOUT_5_OBJ_1, ISB_APP_DIGOUT_6_OBJ_1, ISB_APP_DIGOUT_7_OBJ_1, ISB_APP_DIGOUT_8_OBJ_1 };
			#endif /* ISB_APP_DIGOUT_FEATURE_RESULT == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_2, ISB_APP_DIGOUT_1_OBJ_2, ISB_APP_DIGOUT_2_OBJ_2, ISB_APP_DIGOUT_3_OBJ_2, ISB_APP_DIGOUT_4_OBJ_2, ISB_APP_DIGOUT_5_OBJ_2, ISB_APP_DIGOUT_6_OBJ_2, ISB_APP_DIGOUT_7_OBJ_2, ISB_APP_DIGOUT_8_OBJ_2 };
			#endif /* ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_3, ISB_APP_DIGOUT_1_OBJ_3, ISB_APP_DIGOUT_2_OBJ_3, ISB_APP_DIGOUT_3_OBJ_3, ISB_APP_DIGOUT_4_OBJ_3, ISB_APP_DIGOUT_5_OBJ_3, ISB_APP_DIGOUT_6_OBJ_3, ISB_APP_DIGOUT_7_OBJ_3, ISB_APP_DIGOUT_8_OBJ_3 };
			#endif /* ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE */
		#elif ISB_APP_DIGOUT_MAX == 10
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH, ISB_APP_DIGOUT_5_CH, ISB_APP_DIGOUT_6_CH, ISB_APP_DIGOUT_7_CH, ISB_APP_DIGOUT_8_CH, ISB_APP_DIGOUT_9_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0, ISB_APP_DIGOUT_5_PIN0, ISB_APP_DIGOUT_6_PIN0, ISB_APP_DIGOUT_7_PIN0, ISB_APP_DIGOUT_8_PIN0, ISB_APP_DIGOUT_9_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1, ISB_APP_DIGOUT_5_PIN1, ISB_APP_DIGOUT_6_PIN1, ISB_APP_DIGOUT_7_PIN1, ISB_APP_DIGOUT_8_PIN1, ISB_APP_DIGOUT_9_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_0, ISB_APP_DIGOUT_1_OBJ_0, ISB_APP_DIGOUT_2_OBJ_0, ISB_APP_DIGOUT_3_OBJ_0, ISB_APP_DIGOUT_4_OBJ_0, ISB_APP_DIGOUT_5_OBJ_0, ISB_APP_DIGOUT_6_OBJ_0, ISB_APP_DIGOUT_7_OBJ_0, ISB_APP_DIGOUT_8_OBJ_0, ISB_APP_DIGOUT_9_OBJ_0 };
			#if ISB_APP_DIGOUT_FEATURE_RESULT == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1, ISB_APP_DIGOUT_1_OBJ_1, ISB_APP_DIGOUT_2_OBJ_1, ISB_APP_DIGOUT_3_OBJ_1, ISB_APP_DIGOUT_4_OBJ_1, ISB_APP_DIGOUT_5_OBJ_1, ISB_APP_DIGOUT_6_OBJ_1, ISB_APP_DIGOUT_7_OBJ_1, ISB_APP_DIGOUT_8_OBJ_1, ISB_APP_DIGOUT_9_OBJ_1 };
			#endif /* ISB_APP_DIGOUT_FEATURE_RESULT == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_2, ISB_APP_DIGOUT_1_OBJ_2, ISB_APP_DIGOUT_2_OBJ_2, ISB_APP_DIGOUT_3_OBJ_2, ISB_APP_DIGOUT_4_OBJ_2, ISB_APP_DIGOUT_5_OBJ_2, ISB_APP_DIGOUT_6_OBJ_2, ISB_APP_DIGOUT_7_OBJ_2, ISB_APP_DIGOUT_8_OBJ_2, ISB_APP_DIGOUT_9_OBJ_2 };
			#endif /* ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_3, ISB_APP_DIGOUT_1_OBJ_3, ISB_APP_DIGOUT_2_OBJ_3, ISB_APP_DIGOUT_3_OBJ_3, ISB_APP_DIGOUT_4_OBJ_3, ISB_APP_DIGOUT_5_OBJ_3, ISB_APP_DIGOUT_6_OBJ_3, ISB_APP_DIGOUT_7_OBJ_3, ISB_APP_DIGOUT_8_OBJ_3, ISB_APP_DIGOUT_9_OBJ_3 };
			#endif /* ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE */
		#elif ISB_APP_DIGOUT_MAX == 11
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH, ISB_APP_DIGOUT_5_CH, ISB_APP_DIGOUT_6_CH, ISB_APP_DIGOUT_7_CH, ISB_APP_DIGOUT_8_CH, ISB_APP_DIGOUT_9_CH, ISB_APP_DIGOUT_10_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0, ISB_APP_DIGOUT_5_PIN0, ISB_APP_DIGOUT_6_PIN0, ISB_APP_DIGOUT_7_PIN0, ISB_APP_DIGOUT_8_PIN0, ISB_APP_DIGOUT_9_PIN0, ISB_APP_DIGOUT_10_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1, ISB_APP_DIGOUT_5_PIN1, ISB_APP_DIGOUT_6_PIN1, ISB_APP_DIGOUT_7_PIN1, ISB_APP_DIGOUT_8_PIN1, ISB_APP_DIGOUT_9_PIN1, ISB_APP_DIGOUT_10_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_0, ISB_APP_DIGOUT_1_OBJ_0, ISB_APP_DIGOUT_2_OBJ_0, ISB_APP_DIGOUT_3_OBJ_0, ISB_APP_DIGOUT_4_OBJ_0, ISB_APP_DIGOUT_5_OBJ_0, ISB_APP_DIGOUT_6_OBJ_0, ISB_APP_DIGOUT_7_OBJ_0, ISB_APP_DIGOUT_8_OBJ_0, ISB_APP_DIGOUT_9_OBJ_0, ISB_APP_DIGOUT_10_OBJ_0 };
			#if ISB_APP_DIGOUT_FEATURE_RESULT == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1, ISB_APP_DIGOUT_1_OBJ_1, ISB_APP_DIGOUT_2_OBJ_1, ISB_APP_DIGOUT_3_OBJ_1, ISB_APP_DIGOUT_4_OBJ_1, ISB_APP_DIGOUT_5_OBJ_1, ISB_APP_DIGOUT_6_OBJ_1, ISB_APP_DIGOUT_7_OBJ_1, ISB_APP_DIGOUT_8_OBJ_1, ISB_APP_DIGOUT_9_OBJ_1, ISB_APP_DIGOUT_10_OBJ_1 };
			#endif /* ISB_APP_DIGOUT_FEATURE_RESULT == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_2, ISB_APP_DIGOUT_1_OBJ_2, ISB_APP_DIGOUT_2_OBJ_2, ISB_APP_DIGOUT_3_OBJ_2, ISB_APP_DIGOUT_4_OBJ_2, ISB_APP_DIGOUT_5_OBJ_2, ISB_APP_DIGOUT_6_OBJ_2, ISB_APP_DIGOUT_7_OBJ_2, ISB_APP_DIGOUT_8_OBJ_2, ISB_APP_DIGOUT_9_OBJ_2, ISB_APP_DIGOUT_10_OBJ_2 };
			#endif /* ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_3, ISB_APP_DIGOUT_1_OBJ_3, ISB_APP_DIGOUT_2_OBJ_3, ISB_APP_DIGOUT_3_OBJ_3, ISB_APP_DIGOUT_4_OBJ_3, ISB_APP_DIGOUT_5_OBJ_3, ISB_APP_DIGOUT_6_OBJ_3, ISB_APP_DIGOUT_7_OBJ_3, ISB_APP_DIGOUT_8_OBJ_3, ISB_APP_DIGOUT_9_OBJ_3, ISB_APP_DIGOUT_10_OBJ_3 };
			#endif /* ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE */
		#elif ISB_APP_DIGOUT_MAX == 12
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH, ISB_APP_DIGOUT_5_CH, ISB_APP_DIGOUT_6_CH, ISB_APP_DIGOUT_7_CH, ISB_APP_DIGOUT_8_CH, ISB_APP_DIGOUT_9_CH, ISB_APP_DIGOUT_10_CH, ISB_APP_DIGOUT_11_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0, ISB_APP_DIGOUT_5_PIN0, ISB_APP_DIGOUT_6_PIN0, ISB_APP_DIGOUT_7_PIN0, ISB_APP_DIGOUT_8_PIN0, ISB_APP_DIGOUT_9_PIN0, ISB_APP_DIGOUT_10_PIN0, ISB_APP_DIGOUT_11_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1, ISB_APP_DIGOUT_5_PIN1, ISB_APP_DIGOUT_6_PIN1, ISB_APP_DIGOUT_7_PIN1, ISB_APP_DIGOUT_8_PIN1, ISB_APP_DIGOUT_9_PIN1, ISB_APP_DIGOUT_10_PIN1, ISB_APP_DIGOUT_11_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_0, ISB_APP_DIGOUT_1_OBJ_0, ISB_APP_DIGOUT_2_OBJ_0, ISB_APP_DIGOUT_3_OBJ_0, ISB_APP_DIGOUT_4_OBJ_0, ISB_APP_DIGOUT_5_OBJ_0, ISB_APP_DIGOUT_6_OBJ_0, ISB_APP_DIGOUT_7_OBJ_0, ISB_APP_DIGOUT_8_OBJ_0, ISB_APP_DIGOUT_9_OBJ_0, ISB_APP_DIGOUT_10_OBJ_0, ISB_APP_DIGOUT_11_OBJ_0 };
			#if ISB_APP_DIGOUT_FEATURE_RESULT == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1, ISB_APP_DIGOUT_1_OBJ_1, ISB_APP_DIGOUT_2_OBJ_1, ISB_APP_DIGOUT_3_OBJ_1, ISB_APP_DIGOUT_4_OBJ_1, ISB_APP_DIGOUT_5_OBJ_1, ISB_APP_DIGOUT_6_OBJ_1, ISB_APP_DIGOUT_7_OBJ_1, ISB_APP_DIGOUT_8_OBJ_1, ISB_APP_DIGOUT_9_OBJ_1, ISB_APP_DIGOUT_10_OBJ_1, ISB_APP_DIGOUT_11_OBJ_1 };
			#endif /* ISB_APP_DIGOUT_FEATURE_RESULT == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_2, ISB_APP_DIGOUT_1_OBJ_2, ISB_APP_DIGOUT_2_OBJ_2, ISB_APP_DIGOUT_3_OBJ_2, ISB_APP_DIGOUT_4_OBJ_2, ISB_APP_DIGOUT_5_OBJ_2, ISB_APP_DIGOUT_6_OBJ_2, ISB_APP_DIGOUT_7_OBJ_2, ISB_APP_DIGOUT_8_OBJ_2, ISB_APP_DIGOUT_9_OBJ_2, ISB_APP_DIGOUT_10_OBJ_2, ISB_APP_DIGOUT_11_OBJ_2 };
			#endif /* ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_3, ISB_APP_DIGOUT_1_OBJ_3, ISB_APP_DIGOUT_2_OBJ_3, ISB_APP_DIGOUT_3_OBJ_3, ISB_APP_DIGOUT_4_OBJ_3, ISB_APP_DIGOUT_5_OBJ_3, ISB_APP_DIGOUT_6_OBJ_3, ISB_APP_DIGOUT_7_OBJ_3, ISB_APP_DIGOUT_8_OBJ_3, ISB_APP_DIGOUT_9_OBJ_3, ISB_APP_DIGOUT_10_OBJ_3, ISB_APP_DIGOUT_11_OBJ_3 };
			#endif /* ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE */
		#elif ISB_APP_DIGOUT_MAX == 13
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH, ISB_APP_DIGOUT_5_CH, ISB_APP_DIGOUT_6_CH, ISB_APP_DIGOUT_7_CH, ISB_APP_DIGOUT_8_CH, ISB_APP_DIGOUT_9_CH, ISB_APP_DIGOUT_10_CH, ISB_APP_DIGOUT_11_CH, ISB_APP_DIGOUT_12_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0, ISB_APP_DIGOUT_5_PIN0, ISB_APP_DIGOUT_6_PIN0, ISB_APP_DIGOUT_7_PIN0, ISB_APP_DIGOUT_8_PIN0, ISB_APP_DIGOUT_9_PIN0, ISB_APP_DIGOUT_10_PIN0, ISB_APP_DIGOUT_11_PIN0, ISB_APP_DIGOUT_12_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1, ISB_APP_DIGOUT_5_PIN1, ISB_APP_DIGOUT_6_PIN1, ISB_APP_DIGOUT_7_PIN1, ISB_APP_DIGOUT_8_PIN1, ISB_APP_DIGOUT_9_PIN1, ISB_APP_DIGOUT_10_PIN1, ISB_APP_DIGOUT_11_PIN1, ISB_APP_DIGOUT_12_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_0, ISB_APP_DIGOUT_1_OBJ_0, ISB_APP_DIGOUT_2_OBJ_0, ISB_APP_DIGOUT_3_OBJ_0, ISB_APP_DIGOUT_4_OBJ_0, ISB_APP_DIGOUT_5_OBJ_0, ISB_APP_DIGOUT_6_OBJ_0, ISB_APP_DIGOUT_7_OBJ_0, ISB_APP_DIGOUT_8_OBJ_0, ISB_APP_DIGOUT_9_OBJ_0, ISB_APP_DIGOUT_10_OBJ_0, ISB_APP_DIGOUT_11_OBJ_0, ISB_APP_DIGOUT_12_OBJ_0 };
			#if ISB_APP_DIGOUT_FEATURE_RESULT == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1, ISB_APP_DIGOUT_1_OBJ_1, ISB_APP_DIGOUT_2_OBJ_1, ISB_APP_DIGOUT_3_OBJ_1, ISB_APP_DIGOUT_4_OBJ_1, ISB_APP_DIGOUT_5_OBJ_1, ISB_APP_DIGOUT_6_OBJ_1, ISB_APP_DIGOUT_7_OBJ_1, ISB_APP_DIGOUT_8_OBJ_1, ISB_APP_DIGOUT_9_OBJ_1, ISB_APP_DIGOUT_10_OBJ_1, ISB_APP_DIGOUT_11_OBJ_1, ISB_APP_DIGOUT_12_OBJ_1 };
			#endif /* ISB_APP_DIGOUT_FEATURE_RESULT == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_2, ISB_APP_DIGOUT_1_OBJ_2, ISB_APP_DIGOUT_2_OBJ_2, ISB_APP_DIGOUT_3_OBJ_2, ISB_APP_DIGOUT_4_OBJ_2, ISB_APP_DIGOUT_5_OBJ_2, ISB_APP_DIGOUT_6_OBJ_2, ISB_APP_DIGOUT_7_OBJ_2, ISB_APP_DIGOUT_8_OBJ_2, ISB_APP_DIGOUT_9_OBJ_2, ISB_APP_DIGOUT_10_OBJ_2, ISB_APP_DIGOUT_11_OBJ_2, ISB_APP_DIGOUT_12_OBJ_2 };
			#endif /* ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_3, ISB_APP_DIGOUT_1_OBJ_3, ISB_APP_DIGOUT_2_OBJ_3, ISB_APP_DIGOUT_3_OBJ_3, ISB_APP_DIGOUT_4_OBJ_3, ISB_APP_DIGOUT_5_OBJ_3, ISB_APP_DIGOUT_6_OBJ_3, ISB_APP_DIGOUT_7_OBJ_3, ISB_APP_DIGOUT_8_OBJ_3, ISB_APP_DIGOUT_9_OBJ_3, ISB_APP_DIGOUT_10_OBJ_3, ISB_APP_DIGOUT_11_OBJ_3, ISB_APP_DIGOUT_12_OBJ_3 };
			#endif /* ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE */
		#elif ISB_APP_DIGOUT_MAX == 14
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH, ISB_APP_DIGOUT_5_CH, ISB_APP_DIGOUT_6_CH, ISB_APP_DIGOUT_7_CH, ISB_APP_DIGOUT_8_CH, ISB_APP_DIGOUT_9_CH, ISB_APP_DIGOUT_10_CH, ISB_APP_DIGOUT_11_CH, ISB_APP_DIGOUT_12_CH, ISB_APP_DIGOUT_13_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0, ISB_APP_DIGOUT_5_PIN0, ISB_APP_DIGOUT_6_PIN0, ISB_APP_DIGOUT_7_PIN0, ISB_APP_DIGOUT_8_PIN0, ISB_APP_DIGOUT_9_PIN0, ISB_APP_DIGOUT_10_PIN0, ISB_APP_DIGOUT_11_PIN0, ISB_APP_DIGOUT_12_PIN0, ISB_APP_DIGOUT_13_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1, ISB_APP_DIGOUT_5_PIN1, ISB_APP_DIGOUT_6_PIN1, ISB_APP_DIGOUT_7_PIN1, ISB_APP_DIGOUT_8_PIN1, ISB_APP_DIGOUT_9_PIN1, ISB_APP_DIGOUT_10_PIN1, ISB_APP_DIGOUT_11_PIN1, ISB_APP_DIGOUT_12_PIN1, ISB_APP_DIGOUT_13_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_0, ISB_APP_DIGOUT_1_OBJ_0, ISB_APP_DIGOUT_2_OBJ_0, ISB_APP_DIGOUT_3_OBJ_0, ISB_APP_DIGOUT_4_OBJ_0, ISB_APP_DIGOUT_5_OBJ_0, ISB_APP_DIGOUT_6_OBJ_0, ISB_APP_DIGOUT_7_OBJ_0, ISB_APP_DIGOUT_8_OBJ_0, ISB_APP_DIGOUT_9_OBJ_0, ISB_APP_DIGOUT_10_OBJ_0, ISB_APP_DIGOUT_11_OBJ_0, ISB_APP_DIGOUT_12_OBJ_0, ISB_APP_DIGOUT_13_OBJ_0 };
			#if ISB_APP_DIGOUT_FEATURE_RESULT == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1, ISB_APP_DIGOUT_1_OBJ_1, ISB_APP_DIGOUT_2_OBJ_1, ISB_APP_DIGOUT_3_OBJ_1, ISB_APP_DIGOUT_4_OBJ_1, ISB_APP_DIGOUT_5_OBJ_1, ISB_APP_DIGOUT_6_OBJ_1, ISB_APP_DIGOUT_7_OBJ_1, ISB_APP_DIGOUT_8_OBJ_1, ISB_APP_DIGOUT_9_OBJ_1, ISB_APP_DIGOUT_10_OBJ_1, ISB_APP_DIGOUT_11_OBJ_1, ISB_APP_DIGOUT_12_OBJ_1, ISB_APP_DIGOUT_13_OBJ_1 };
			#endif /* ISB_APP_DIGOUT_FEATURE_RESULT == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_2, ISB_APP_DIGOUT_1_OBJ_2, ISB_APP_DIGOUT_2_OBJ_2, ISB_APP_DIGOUT_3_OBJ_2, ISB_APP_DIGOUT_4_OBJ_2, ISB_APP_DIGOUT_5_OBJ_2, ISB_APP_DIGOUT_6_OBJ_2, ISB_APP_DIGOUT_7_OBJ_2, ISB_APP_DIGOUT_8_OBJ_2, ISB_APP_DIGOUT_9_OBJ_2, ISB_APP_DIGOUT_10_OBJ_2, ISB_APP_DIGOUT_11_OBJ_1, ISB_APP_DIGOUT_12_OBJ_2, ISB_APP_DIGOUT_13_OBJ_2 };
			#endif /* ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_3, ISB_APP_DIGOUT_1_OBJ_3, ISB_APP_DIGOUT_2_OBJ_3, ISB_APP_DIGOUT_3_OBJ_3, ISB_APP_DIGOUT_4_OBJ_3, ISB_APP_DIGOUT_5_OBJ_3, ISB_APP_DIGOUT_6_OBJ_3, ISB_APP_DIGOUT_7_OBJ_3, ISB_APP_DIGOUT_8_OBJ_3, ISB_APP_DIGOUT_9_OBJ_3, ISB_APP_DIGOUT_10_OBJ_3, ISB_APP_DIGOUT_11_OBJ_1, ISB_APP_DIGOUT_12_OBJ_3, ISB_APP_DIGOUT_13_OBJ_3 };
			#endif /* ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE */
		#elif ISB_APP_DIGOUT_MAX == 15
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH, ISB_APP_DIGOUT_5_CH, ISB_APP_DIGOUT_6_CH, ISB_APP_DIGOUT_7_CH, ISB_APP_DIGOUT_8_CH, ISB_APP_DIGOUT_9_CH, ISB_APP_DIGOUT_10_CH, ISB_APP_DIGOUT_11_CH, ISB_APP_DIGOUT_12_CH, ISB_APP_DIGOUT_13_CH, ISB_APP_DIGOUT_14_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0, ISB_APP_DIGOUT_5_PIN0, ISB_APP_DIGOUT_6_PIN0, ISB_APP_DIGOUT_7_PIN0, ISB_APP_DIGOUT_8_PIN0, ISB_APP_DIGOUT_9_PIN0, ISB_APP_DIGOUT_10_PIN0, ISB_APP_DIGOUT_11_PIN0, ISB_APP_DIGOUT_12_PIN0, ISB_APP_DIGOUT_13_PIN0, ISB_APP_DIGOUT_14_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1, ISB_APP_DIGOUT_5_PIN1, ISB_APP_DIGOUT_6_PIN1, ISB_APP_DIGOUT_7_PIN1, ISB_APP_DIGOUT_8_PIN1, ISB_APP_DIGOUT_9_PIN1, ISB_APP_DIGOUT_10_PIN1, ISB_APP_DIGOUT_11_PIN1, ISB_APP_DIGOUT_12_PIN1, ISB_APP_DIGOUT_13_PIN1, ISB_APP_DIGOUT_14_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_0, ISB_APP_DIGOUT_1_OBJ_0, ISB_APP_DIGOUT_2_OBJ_0, ISB_APP_DIGOUT_3_OBJ_0, ISB_APP_DIGOUT_4_OBJ_0, ISB_APP_DIGOUT_5_OBJ_0, ISB_APP_DIGOUT_6_OBJ_0, ISB_APP_DIGOUT_7_OBJ_0, ISB_APP_DIGOUT_8_OBJ_0, ISB_APP_DIGOUT_9_OBJ_0, ISB_APP_DIGOUT_10_OBJ_0, ISB_APP_DIGOUT_11_OBJ_0, ISB_APP_DIGOUT_12_OBJ_0, ISB_APP_DIGOUT_13_OBJ_0, ISB_APP_DIGOUT_14_OBJ_0 };
			#if ISB_APP_DIGOUT_FEATURE_RESULT == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1, ISB_APP_DIGOUT_1_OBJ_1, ISB_APP_DIGOUT_2_OBJ_1, ISB_APP_DIGOUT_3_OBJ_1, ISB_APP_DIGOUT_4_OBJ_1, ISB_APP_DIGOUT_5_OBJ_1, ISB_APP_DIGOUT_6_OBJ_1, ISB_APP_DIGOUT_7_OBJ_1, ISB_APP_DIGOUT_8_OBJ_1, ISB_APP_DIGOUT_9_OBJ_1, ISB_APP_DIGOUT_10_OBJ_1, ISB_APP_DIGOUT_11_OBJ_1, ISB_APP_DIGOUT_12_OBJ_1, ISB_APP_DIGOUT_13_OBJ_1, ISB_APP_DIGOUT_14_OBJ_1 };
			#endif /* ISB_APP_DIGOUT_FEATURE_RESULT == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_2, ISB_APP_DIGOUT_1_OBJ_2, ISB_APP_DIGOUT_2_OBJ_2, ISB_APP_DIGOUT_3_OBJ_2, ISB_APP_DIGOUT_4_OBJ_2, ISB_APP_DIGOUT_5_OBJ_2, ISB_APP_DIGOUT_6_OBJ_2, ISB_APP_DIGOUT_7_OBJ_2, ISB_APP_DIGOUT_8_OBJ_2, ISB_APP_DIGOUT_9_OBJ_2, ISB_APP_DIGOUT_10_OBJ_2, ISB_APP_DIGOUT_11_OBJ_1, ISB_APP_DIGOUT_12_OBJ_2, ISB_APP_DIGOUT_13_OBJ_2, ISB_APP_DIGOUT_14_OBJ_2 };
			#endif /* ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_3, ISB_APP_DIGOUT_1_OBJ_3, ISB_APP_DIGOUT_2_OBJ_3, ISB_APP_DIGOUT_3_OBJ_3, ISB_APP_DIGOUT_4_OBJ_3, ISB_APP_DIGOUT_5_OBJ_3, ISB_APP_DIGOUT_6_OBJ_3, ISB_APP_DIGOUT_7_OBJ_3, ISB_APP_DIGOUT_8_OBJ_3, ISB_APP_DIGOUT_9_OBJ_3, ISB_APP_DIGOUT_10_OBJ_3, ISB_APP_DIGOUT_11_OBJ_1, ISB_APP_DIGOUT_12_OBJ_3, ISB_APP_DIGOUT_13_OBJ_3, ISB_APP_DIGOUT_14_OBJ_3 };
			#endif /* ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE */
		#elif ISB_APP_DIGOUT_MAX == 16
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH, ISB_APP_DIGOUT_5_CH, ISB_APP_DIGOUT_6_CH, ISB_APP_DIGOUT_7_CH, ISB_APP_DIGOUT_8_CH, ISB_APP_DIGOUT_9_CH, ISB_APP_DIGOUT_10_CH, ISB_APP_DIGOUT_11_CH, ISB_APP_DIGOUT_12_CH, ISB_APP_DIGOUT_13_CH, ISB_APP_DIGOUT_14_CH, ISB_APP_DIGOUT_15_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0, ISB_APP_DIGOUT_5_PIN0, ISB_APP_DIGOUT_6_PIN0, ISB_APP_DIGOUT_7_PIN0, ISB_APP_DIGOUT_8_PIN0, ISB_APP_DIGOUT_9_PIN0, ISB_APP_DIGOUT_10_PIN0, ISB_APP_DIGOUT_11_PIN0, ISB_APP_DIGOUT_12_PIN0, ISB_APP_DIGOUT_13_PIN0, ISB_APP_DIGOUT_14_PIN0, ISB_APP_DIGOUT_15_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1, ISB_APP_DIGOUT_5_PIN1, ISB_APP_DIGOUT_6_PIN1, ISB_APP_DIGOUT_7_PIN1, ISB_APP_DIGOUT_8_PIN1, ISB_APP_DIGOUT_9_PIN1, ISB_APP_DIGOUT_10_PIN1, ISB_APP_DIGOUT_11_PIN1, ISB_APP_DIGOUT_12_PIN1, ISB_APP_DIGOUT_13_PIN1, ISB_APP_DIGOUT_14_PIN1, ISB_APP_DIGOUT_15_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_0, ISB_APP_DIGOUT_1_OBJ_0, ISB_APP_DIGOUT_2_OBJ_0, ISB_APP_DIGOUT_3_OBJ_0, ISB_APP_DIGOUT_4_OBJ_0, ISB_APP_DIGOUT_5_OBJ_0, ISB_APP_DIGOUT_6_OBJ_0, ISB_APP_DIGOUT_7_OBJ_0, ISB_APP_DIGOUT_8_OBJ_0, ISB_APP_DIGOUT_9_OBJ_0, ISB_APP_DIGOUT_10_OBJ_0, ISB_APP_DIGOUT_11_OBJ_0, ISB_APP_DIGOUT_12_OBJ_0, ISB_APP_DIGOUT_13_OBJ_0, ISB_APP_DIGOUT_14_OBJ_0, ISB_APP_DIGOUT_15_OBJ_0 };
			#if ISB_APP_DIGOUT_FEATURE_RESULT == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1, ISB_APP_DIGOUT_1_OBJ_1, ISB_APP_DIGOUT_2_OBJ_1, ISB_APP_DIGOUT_3_OBJ_1, ISB_APP_DIGOUT_4_OBJ_1, ISB_APP_DIGOUT_5_OBJ_1, ISB_APP_DIGOUT_6_OBJ_1, ISB_APP_DIGOUT_7_OBJ_1, ISB_APP_DIGOUT_8_OBJ_1, ISB_APP_DIGOUT_9_OBJ_1, ISB_APP_DIGOUT_10_OBJ_1, ISB_APP_DIGOUT_11_OBJ_1, ISB_APP_DIGOUT_12_OBJ_1, ISB_APP_DIGOUT_13_OBJ_1, ISB_APP_DIGOUT_14_OBJ_1, ISB_APP_DIGOUT_15_OBJ_1 };
			#endif /* ISB_APP_DIGOUT_FEATURE_RESULT == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_2, ISB_APP_DIGOUT_1_OBJ_2, ISB_APP_DIGOUT_2_OBJ_2, ISB_APP_DIGOUT_3_OBJ_2, ISB_APP_DIGOUT_4_OBJ_2, ISB_APP_DIGOUT_5_OBJ_2, ISB_APP_DIGOUT_6_OBJ_2, ISB_APP_DIGOUT_7_OBJ_2, ISB_APP_DIGOUT_8_OBJ_2, ISB_APP_DIGOUT_9_OBJ_2, ISB_APP_DIGOUT_10_OBJ_2, ISB_APP_DIGOUT_11_OBJ_1, ISB_APP_DIGOUT_12_OBJ_2, ISB_APP_DIGOUT_13_OBJ_2, ISB_APP_DIGOUT_14_OBJ_2, ISB_APP_DIGOUT_15_OBJ_2 };
			#endif /* ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE
				static const uint8_t pgmIsb_App_DigOut_Obj_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_3, ISB_APP_DIGOUT_1_OBJ_3, ISB_APP_DIGOUT_2_OBJ_3, ISB_APP_DIGOUT_3_OBJ_3, ISB_APP_DIGOUT_4_OBJ_3, ISB_APP_DIGOUT_5_OBJ_3, ISB_APP_DIGOUT_6_OBJ_3, ISB_APP_DIGOUT_7_OBJ_3, ISB_APP_DIGOUT_8_OBJ_3, ISB_APP_DIGOUT_9_OBJ_3, ISB_APP_DIGOUT_10_OBJ_3, ISB_APP_DIGOUT_11_OBJ_1, ISB_APP_DIGOUT_12_OBJ_3, ISB_APP_DIGOUT_13_OBJ_3, ISB_APP_DIGOUT_14_OBJ_3, ISB_APP_DIGOUT_15_OBJ_3 };
			#endif /* ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE */
		#else
			#error ISB_APP_DIGOUT_MAX
		#endif /* ISB_APP_DIGOUT_MAX == ? */

		typedef struct Isb_App_DigOut_t Isb_App_DigOut_t;

		struct Isb_App_DigOut_t
		{
			uint8_t Cfg0;
			uint16_t Counter;
			uint8_t Value;
			uint8_t IsChanged;
			#if ISB_APP_DIGOUT_FEATURE_RESULT == TRUE
				uint8_t Cfg1;
			#endif /* ISB_APP_DIGOUT_FEATURE_RESULT == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE
				uint8_t Cfg2;
				uint8_t LogicValue;
				uint8_t LogicIsChanged;
			#endif /* ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_TIMEFUNCTION == TRUE
				uint8_t Cfg3;
				uint8_t Cfg4;
				uint8_t Cfg5;
				uint8_t Cfg6;
				uint8_t Cfg7;
				uint8_t Cfg8;
				uint8_t Cfg9;
				uint32_t TimeOnCount;
				uint32_t TimeOffCount;
				uint8_t TimeValue;
				uint8_t TimeIsChanged;
			#endif /* ISB_APP_DIGOUT_FEATURE_TIMEFUNCTION == TRUE */
			#if ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE
				uint8_t Cfg10;
				uint8_t Special_Action;
			#endif /* ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION == TRUE */
		};

		static uint8_t Isb_App_DigOut_Ctrl = 0;
		static uint16_t Isb_App_DigOut_IrqExec = 0;
		static Isb_App_DigOut_t Isb_App_DigOut[ISB_APP_DIGOUT_MAX];

	#endif /* ISB_APP_DIGOUT_MAX */



	#if defined(ISB_APP_HOTWATER_CIRCULATION_MAX)

		#if ISB_APP_HOTWATER_CIRCULATION_MAX == 1
			static const uint8_t pgmIsb_App_HotWater_Circulation_Ch_Array[] PROGMEM = { ISB_APP_HOTWATER_CIRCULATION_0_CH };
			static const uint8_t pgmIsb_App_HotWater_Circulation_Obj_0_Array[] PROGMEM = { ISB_APP_HOTWATER_CIRCULATION_0_OBJ_0 };
			static const uint8_t pgmIsb_App_HotWater_Circulation_Obj_1_Array[] PROGMEM = { ISB_APP_HOTWATER_CIRCULATION_0_OBJ_1 };
			static const uint8_t pgmIsb_App_HotWater_Circulation_Obj_2_Array[] PROGMEM = { ISB_APP_HOTWATER_CIRCULATION_0_OBJ_2 };
		#else
			#error ISB_APP_HOTWATER_CIRCULATION_MAX
		#endif /* ISB_APP_HOTWATER_CIRCULATION_MAX == ? */

		typedef struct Isb_App_HotWater_Circulation_t Isb_App_HotWater_Circulation_t;

		struct Isb_App_HotWater_Circulation_t
		{
			uint8_t Cfg0;
			uint8_t Cfg1;
			uint8_t Cfg2;
			uint8_t Cfg3;

			uint8_t OperatingMode;
			uint32_t Interval;
			uint32_t Duration;
//			uint16_t TimeCount;
//			uint8_t Typ;
			uint8_t Pump;
			uint32_t PumpRuntimeToday;
			uint32_t PumpRuntimeNow;
//			uint8_t Cfg1;
//			uint8_t Cfg2;
//			uint16_t Min;
//			uint16_t Max;
		};

		static uint8_t Isb_App_HotWater_Circulation_Ctrl = 0;
		static uint16_t Isb_App_HotWater_Circulation_IrqExec = 0;
		static Isb_App_HotWater_Circulation_t Isb_App_HotWater_Circulation[ISB_APP_HOTWATER_CIRCULATION_MAX];

	#endif /* ISB_APP_HOTWATER_CIRCULATION_MAX */



	#if defined(ISB_APP_LCD_MAX)

		#if ISB_APP_LCD_MAX == 1
			static const uint8_t pgmIsb_App_Lcd_Ch_Array[] PROGMEM = { ISB_APP_LCD_0_CH };
		#else
			#error ISB_APP_LCD_MAX
		#endif /* ISB_APP_LCD_MAX == ? */

		typedef struct Isb_App_Lcd_t Isb_App_Lcd_t;

		struct Isb_App_Lcd_t
		{
//			uint8_t Ch;
//			uint8_t Obj_Sensor;
//			uint16_t TimeCount;
//			uint8_t Typ;
			uint8_t Cfg0;
			uint8_t Cfg1;
			uint8_t Cfg2;
//			uint16_t Min;
//			uint16_t Max;
			uint16_t Value;
		};

		static uint8_t Isb_App_Lcd_Ctrl = 0;
		static uint16_t Isb_App_Lcd_IrqExec = 0;
		static Isb_App_Lcd_t Isb_App_Lcd[ISB_APP_LCD_MAX];

	#endif /* ISB_APP_LCD_MAX */



	void Isb_App_Init(void);
	void Isb_App_Exec(void);



#endif /* ISB_APP_H_ */
