/**
 * @file		avrlib/trunk/lib/isb_app.h
 *
 * @brief		iSysBus Application.
 *
 * This file includes iSysBus Application.
 *
 * @author		© Patrick Amrhein <trick-at-isysbus-dot-org> 01.05.2010.
 *
 * @date		$Date: 2011-09-22 10:55:17 +0200 (Do, 22 Sep 2011) $
 *
 * @version		$Rev: 5116 $
 *
 * @note
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version. \n
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details. \n
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http:*www.gnu.org/licenses. \n
 */





#ifndef ISB_APP_H_
	#define ISB_APP_H_



	#if defined(ISB_APP_DIGOUT_MAX)

		#if ISB_APP_DIGOUT_MAX == 1
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_3 };
		#elif ISB_APP_DIGOUT_MAX == 2
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_0, ISB_APP_DIGOUT_1_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_1, ISB_APP_DIGOUT_1_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_2, ISB_APP_DIGOUT_1_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_3, ISB_APP_DIGOUT_1_OBJ_1BIT_3 };
		#elif ISB_APP_DIGOUT_MAX == 3
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_0, ISB_APP_DIGOUT_1_OBJ_1BIT_0, ISB_APP_DIGOUT_2_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_1, ISB_APP_DIGOUT_1_OBJ_1BIT_1, ISB_APP_DIGOUT_2_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_2, ISB_APP_DIGOUT_1_OBJ_1BIT_2, ISB_APP_DIGOUT_2_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_3, ISB_APP_DIGOUT_1_OBJ_1BIT_3, ISB_APP_DIGOUT_2_OBJ_1BIT_3 };
		#elif ISB_APP_DIGOUT_MAX == 4
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_0, ISB_APP_DIGOUT_1_OBJ_1BIT_0, ISB_APP_DIGOUT_2_OBJ_1BIT_0, ISB_APP_DIGOUT_3_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_1, ISB_APP_DIGOUT_1_OBJ_1BIT_1, ISB_APP_DIGOUT_2_OBJ_1BIT_1, ISB_APP_DIGOUT_3_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_2, ISB_APP_DIGOUT_1_OBJ_1BIT_2, ISB_APP_DIGOUT_2_OBJ_1BIT_2, ISB_APP_DIGOUT_3_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_3, ISB_APP_DIGOUT_1_OBJ_1BIT_3, ISB_APP_DIGOUT_2_OBJ_1BIT_3, ISB_APP_DIGOUT_3_OBJ_1BIT_3 };
		#elif ISB_APP_DIGOUT_MAX == 5
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_0, ISB_APP_DIGOUT_1_OBJ_1BIT_0, ISB_APP_DIGOUT_2_OBJ_1BIT_0, ISB_APP_DIGOUT_3_OBJ_1BIT_0, ISB_APP_DIGOUT_4_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_1, ISB_APP_DIGOUT_1_OBJ_1BIT_1, ISB_APP_DIGOUT_2_OBJ_1BIT_1, ISB_APP_DIGOUT_3_OBJ_1BIT_1, ISB_APP_DIGOUT_4_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_2, ISB_APP_DIGOUT_1_OBJ_1BIT_2, ISB_APP_DIGOUT_2_OBJ_1BIT_2, ISB_APP_DIGOUT_3_OBJ_1BIT_2, ISB_APP_DIGOUT_4_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_3, ISB_APP_DIGOUT_1_OBJ_1BIT_3, ISB_APP_DIGOUT_2_OBJ_1BIT_3, ISB_APP_DIGOUT_3_OBJ_1BIT_3, ISB_APP_DIGOUT_4_OBJ_1BIT_3 };
		#elif ISB_APP_DIGOUT_MAX == 6
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH, ISB_APP_DIGOUT_5_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0, ISB_APP_DIGOUT_5_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1, ISB_APP_DIGOUT_5_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_0, ISB_APP_DIGOUT_1_OBJ_1BIT_0, ISB_APP_DIGOUT_2_OBJ_1BIT_0, ISB_APP_DIGOUT_3_OBJ_1BIT_0, ISB_APP_DIGOUT_4_OBJ_1BIT_0, ISB_APP_DIGOUT_5_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_1, ISB_APP_DIGOUT_1_OBJ_1BIT_1, ISB_APP_DIGOUT_2_OBJ_1BIT_1, ISB_APP_DIGOUT_3_OBJ_1BIT_1, ISB_APP_DIGOUT_4_OBJ_1BIT_1, ISB_APP_DIGOUT_5_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_2, ISB_APP_DIGOUT_1_OBJ_1BIT_2, ISB_APP_DIGOUT_2_OBJ_1BIT_2, ISB_APP_DIGOUT_3_OBJ_1BIT_2, ISB_APP_DIGOUT_4_OBJ_1BIT_2, ISB_APP_DIGOUT_5_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_3, ISB_APP_DIGOUT_1_OBJ_1BIT_3, ISB_APP_DIGOUT_2_OBJ_1BIT_3, ISB_APP_DIGOUT_3_OBJ_1BIT_3, ISB_APP_DIGOUT_4_OBJ_1BIT_3, ISB_APP_DIGOUT_5_OBJ_1BIT_3 };
		#elif ISB_APP_DIGOUT_MAX == 7
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH, ISB_APP_DIGOUT_5_CH, ISB_APP_DIGOUT_6_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0, ISB_APP_DIGOUT_5_PIN0, ISB_APP_DIGOUT_6_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1, ISB_APP_DIGOUT_5_PIN1, ISB_APP_DIGOUT_6_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_0, ISB_APP_DIGOUT_1_OBJ_1BIT_0, ISB_APP_DIGOUT_2_OBJ_1BIT_0, ISB_APP_DIGOUT_3_OBJ_1BIT_0, ISB_APP_DIGOUT_4_OBJ_1BIT_0, ISB_APP_DIGOUT_5_OBJ_1BIT_0, ISB_APP_DIGOUT_6_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_1, ISB_APP_DIGOUT_1_OBJ_1BIT_1, ISB_APP_DIGOUT_2_OBJ_1BIT_1, ISB_APP_DIGOUT_3_OBJ_1BIT_1, ISB_APP_DIGOUT_4_OBJ_1BIT_1, ISB_APP_DIGOUT_5_OBJ_1BIT_1, ISB_APP_DIGOUT_6_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_2, ISB_APP_DIGOUT_1_OBJ_1BIT_2, ISB_APP_DIGOUT_2_OBJ_1BIT_2, ISB_APP_DIGOUT_3_OBJ_1BIT_2, ISB_APP_DIGOUT_4_OBJ_1BIT_2, ISB_APP_DIGOUT_5_OBJ_1BIT_2, ISB_APP_DIGOUT_6_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_3, ISB_APP_DIGOUT_1_OBJ_1BIT_3, ISB_APP_DIGOUT_2_OBJ_1BIT_3, ISB_APP_DIGOUT_3_OBJ_1BIT_3, ISB_APP_DIGOUT_4_OBJ_1BIT_3, ISB_APP_DIGOUT_5_OBJ_1BIT_3, ISB_APP_DIGOUT_6_OBJ_1BIT_3 };
		#elif ISB_APP_DIGOUT_MAX == 8
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH, ISB_APP_DIGOUT_5_CH, ISB_APP_DIGOUT_6_CH, ISB_APP_DIGOUT_7_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0, ISB_APP_DIGOUT_5_PIN0, ISB_APP_DIGOUT_6_PIN0, ISB_APP_DIGOUT_7_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1, ISB_APP_DIGOUT_5_PIN1, ISB_APP_DIGOUT_6_PIN1, ISB_APP_DIGOUT_7_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_0, ISB_APP_DIGOUT_1_OBJ_1BIT_0, ISB_APP_DIGOUT_2_OBJ_1BIT_0, ISB_APP_DIGOUT_3_OBJ_1BIT_0, ISB_APP_DIGOUT_4_OBJ_1BIT_0, ISB_APP_DIGOUT_5_OBJ_1BIT_0, ISB_APP_DIGOUT_6_OBJ_1BIT_0, ISB_APP_DIGOUT_7_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_1, ISB_APP_DIGOUT_1_OBJ_1BIT_1, ISB_APP_DIGOUT_2_OBJ_1BIT_1, ISB_APP_DIGOUT_3_OBJ_1BIT_1, ISB_APP_DIGOUT_4_OBJ_1BIT_1, ISB_APP_DIGOUT_5_OBJ_1BIT_1, ISB_APP_DIGOUT_6_OBJ_1BIT_1, ISB_APP_DIGOUT_7_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_2, ISB_APP_DIGOUT_1_OBJ_1BIT_2, ISB_APP_DIGOUT_2_OBJ_1BIT_2, ISB_APP_DIGOUT_3_OBJ_1BIT_2, ISB_APP_DIGOUT_4_OBJ_1BIT_2, ISB_APP_DIGOUT_5_OBJ_1BIT_2, ISB_APP_DIGOUT_6_OBJ_1BIT_2, ISB_APP_DIGOUT_7_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_3, ISB_APP_DIGOUT_1_OBJ_1BIT_3, ISB_APP_DIGOUT_2_OBJ_1BIT_3, ISB_APP_DIGOUT_3_OBJ_1BIT_3, ISB_APP_DIGOUT_4_OBJ_1BIT_3, ISB_APP_DIGOUT_5_OBJ_1BIT_3, ISB_APP_DIGOUT_6_OBJ_1BIT_3, ISB_APP_DIGOUT_7_OBJ_1BIT_3 };
		#elif ISB_APP_DIGOUT_MAX == 9
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH, ISB_APP_DIGOUT_5_CH, ISB_APP_DIGOUT_6_CH, ISB_APP_DIGOUT_7_CH, ISB_APP_DIGOUT_8_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0, ISB_APP_DIGOUT_5_PIN0, ISB_APP_DIGOUT_6_PIN0, ISB_APP_DIGOUT_7_PIN0, ISB_APP_DIGOUT_8_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1, ISB_APP_DIGOUT_5_PIN1, ISB_APP_DIGOUT_6_PIN1, ISB_APP_DIGOUT_7_PIN1, ISB_APP_DIGOUT_8_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_0, ISB_APP_DIGOUT_1_OBJ_1BIT_0, ISB_APP_DIGOUT_2_OBJ_1BIT_0, ISB_APP_DIGOUT_3_OBJ_1BIT_0, ISB_APP_DIGOUT_4_OBJ_1BIT_0, ISB_APP_DIGOUT_5_OBJ_1BIT_0, ISB_APP_DIGOUT_6_OBJ_1BIT_0, ISB_APP_DIGOUT_7_OBJ_1BIT_0, ISB_APP_DIGOUT_8_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_1, ISB_APP_DIGOUT_1_OBJ_1BIT_1, ISB_APP_DIGOUT_2_OBJ_1BIT_1, ISB_APP_DIGOUT_3_OBJ_1BIT_1, ISB_APP_DIGOUT_4_OBJ_1BIT_1, ISB_APP_DIGOUT_5_OBJ_1BIT_1, ISB_APP_DIGOUT_6_OBJ_1BIT_1, ISB_APP_DIGOUT_7_OBJ_1BIT_1, ISB_APP_DIGOUT_8_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_2, ISB_APP_DIGOUT_1_OBJ_1BIT_2, ISB_APP_DIGOUT_2_OBJ_1BIT_2, ISB_APP_DIGOUT_3_OBJ_1BIT_2, ISB_APP_DIGOUT_4_OBJ_1BIT_2, ISB_APP_DIGOUT_5_OBJ_1BIT_2, ISB_APP_DIGOUT_6_OBJ_1BIT_2, ISB_APP_DIGOUT_7_OBJ_1BIT_2, ISB_APP_DIGOUT_8_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_3, ISB_APP_DIGOUT_1_OBJ_1BIT_3, ISB_APP_DIGOUT_2_OBJ_1BIT_3, ISB_APP_DIGOUT_3_OBJ_1BIT_3, ISB_APP_DIGOUT_4_OBJ_1BIT_3, ISB_APP_DIGOUT_5_OBJ_1BIT_3, ISB_APP_DIGOUT_6_OBJ_1BIT_3, ISB_APP_DIGOUT_7_OBJ_1BIT_3, ISB_APP_DIGOUT_8_OBJ_1BIT_3 };
		#elif ISB_APP_DIGOUT_MAX == 10
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH, ISB_APP_DIGOUT_5_CH, ISB_APP_DIGOUT_6_CH, ISB_APP_DIGOUT_7_CH, ISB_APP_DIGOUT_8_CH, ISB_APP_DIGOUT_9_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0, ISB_APP_DIGOUT_5_PIN0, ISB_APP_DIGOUT_6_PIN0, ISB_APP_DIGOUT_7_PIN0, ISB_APP_DIGOUT_8_PIN0, ISB_APP_DIGOUT_9_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1, ISB_APP_DIGOUT_5_PIN1, ISB_APP_DIGOUT_6_PIN1, ISB_APP_DIGOUT_7_PIN1, ISB_APP_DIGOUT_8_PIN1, ISB_APP_DIGOUT_9_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_0, ISB_APP_DIGOUT_1_OBJ_1BIT_0, ISB_APP_DIGOUT_2_OBJ_1BIT_0, ISB_APP_DIGOUT_3_OBJ_1BIT_0, ISB_APP_DIGOUT_4_OBJ_1BIT_0, ISB_APP_DIGOUT_5_OBJ_1BIT_0, ISB_APP_DIGOUT_6_OBJ_1BIT_0, ISB_APP_DIGOUT_7_OBJ_1BIT_0, ISB_APP_DIGOUT_8_OBJ_1BIT_0, ISB_APP_DIGOUT_9_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_1, ISB_APP_DIGOUT_1_OBJ_1BIT_1, ISB_APP_DIGOUT_2_OBJ_1BIT_1, ISB_APP_DIGOUT_3_OBJ_1BIT_1, ISB_APP_DIGOUT_4_OBJ_1BIT_1, ISB_APP_DIGOUT_5_OBJ_1BIT_1, ISB_APP_DIGOUT_6_OBJ_1BIT_1, ISB_APP_DIGOUT_7_OBJ_1BIT_1, ISB_APP_DIGOUT_8_OBJ_1BIT_1, ISB_APP_DIGOUT_9_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_2, ISB_APP_DIGOUT_1_OBJ_1BIT_2, ISB_APP_DIGOUT_2_OBJ_1BIT_2, ISB_APP_DIGOUT_3_OBJ_1BIT_2, ISB_APP_DIGOUT_4_OBJ_1BIT_2, ISB_APP_DIGOUT_5_OBJ_1BIT_2, ISB_APP_DIGOUT_6_OBJ_1BIT_2, ISB_APP_DIGOUT_7_OBJ_1BIT_2, ISB_APP_DIGOUT_8_OBJ_1BIT_2, ISB_APP_DIGOUT_9_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_3, ISB_APP_DIGOUT_1_OBJ_1BIT_3, ISB_APP_DIGOUT_2_OBJ_1BIT_3, ISB_APP_DIGOUT_3_OBJ_1BIT_3, ISB_APP_DIGOUT_4_OBJ_1BIT_3, ISB_APP_DIGOUT_5_OBJ_1BIT_3, ISB_APP_DIGOUT_6_OBJ_1BIT_3, ISB_APP_DIGOUT_7_OBJ_1BIT_3, ISB_APP_DIGOUT_8_OBJ_1BIT_3, ISB_APP_DIGOUT_9_OBJ_1BIT_3 };
		#elif ISB_APP_DIGOUT_MAX == 11
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH, ISB_APP_DIGOUT_5_CH, ISB_APP_DIGOUT_6_CH, ISB_APP_DIGOUT_7_CH, ISB_APP_DIGOUT_8_CH, ISB_APP_DIGOUT_9_CH, ISB_APP_DIGOUT_10_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0, ISB_APP_DIGOUT_5_PIN0, ISB_APP_DIGOUT_6_PIN0, ISB_APP_DIGOUT_7_PIN0, ISB_APP_DIGOUT_8_PIN0, ISB_APP_DIGOUT_9_PIN0, ISB_APP_DIGOUT_10_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1, ISB_APP_DIGOUT_5_PIN1, ISB_APP_DIGOUT_6_PIN1, ISB_APP_DIGOUT_7_PIN1, ISB_APP_DIGOUT_8_PIN1, ISB_APP_DIGOUT_9_PIN1, ISB_APP_DIGOUT_10_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_0, ISB_APP_DIGOUT_1_OBJ_1BIT_0, ISB_APP_DIGOUT_2_OBJ_1BIT_0, ISB_APP_DIGOUT_3_OBJ_1BIT_0, ISB_APP_DIGOUT_4_OBJ_1BIT_0, ISB_APP_DIGOUT_5_OBJ_1BIT_0, ISB_APP_DIGOUT_6_OBJ_1BIT_0, ISB_APP_DIGOUT_7_OBJ_1BIT_0, ISB_APP_DIGOUT_8_OBJ_1BIT_0, ISB_APP_DIGOUT_9_OBJ_1BIT_0, ISB_APP_DIGOUT_10_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_1, ISB_APP_DIGOUT_1_OBJ_1BIT_1, ISB_APP_DIGOUT_2_OBJ_1BIT_1, ISB_APP_DIGOUT_3_OBJ_1BIT_1, ISB_APP_DIGOUT_4_OBJ_1BIT_1, ISB_APP_DIGOUT_5_OBJ_1BIT_1, ISB_APP_DIGOUT_6_OBJ_1BIT_1, ISB_APP_DIGOUT_7_OBJ_1BIT_1, ISB_APP_DIGOUT_8_OBJ_1BIT_1, ISB_APP_DIGOUT_9_OBJ_1BIT_1, ISB_APP_DIGOUT_10_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_2, ISB_APP_DIGOUT_1_OBJ_1BIT_2, ISB_APP_DIGOUT_2_OBJ_1BIT_2, ISB_APP_DIGOUT_3_OBJ_1BIT_2, ISB_APP_DIGOUT_4_OBJ_1BIT_2, ISB_APP_DIGOUT_5_OBJ_1BIT_2, ISB_APP_DIGOUT_6_OBJ_1BIT_2, ISB_APP_DIGOUT_7_OBJ_1BIT_2, ISB_APP_DIGOUT_8_OBJ_1BIT_2, ISB_APP_DIGOUT_9_OBJ_1BIT_2, ISB_APP_DIGOUT_10_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_3, ISB_APP_DIGOUT_1_OBJ_1BIT_3, ISB_APP_DIGOUT_2_OBJ_1BIT_3, ISB_APP_DIGOUT_3_OBJ_1BIT_3, ISB_APP_DIGOUT_4_OBJ_1BIT_3, ISB_APP_DIGOUT_5_OBJ_1BIT_3, ISB_APP_DIGOUT_6_OBJ_1BIT_3, ISB_APP_DIGOUT_7_OBJ_1BIT_3, ISB_APP_DIGOUT_8_OBJ_1BIT_3, ISB_APP_DIGOUT_9_OBJ_1BIT_3, ISB_APP_DIGOUT_10_OBJ_1BIT_3 };
		#elif ISB_APP_DIGOUT_MAX == 12
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH, ISB_APP_DIGOUT_5_CH, ISB_APP_DIGOUT_6_CH, ISB_APP_DIGOUT_7_CH, ISB_APP_DIGOUT_8_CH, ISB_APP_DIGOUT_9_CH, ISB_APP_DIGOUT_10_CH, ISB_APP_DIGOUT_11_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0, ISB_APP_DIGOUT_5_PIN0, ISB_APP_DIGOUT_6_PIN0, ISB_APP_DIGOUT_7_PIN0, ISB_APP_DIGOUT_8_PIN0, ISB_APP_DIGOUT_9_PIN0, ISB_APP_DIGOUT_10_PIN0, ISB_APP_DIGOUT_11_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1, ISB_APP_DIGOUT_5_PIN1, ISB_APP_DIGOUT_6_PIN1, ISB_APP_DIGOUT_7_PIN1, ISB_APP_DIGOUT_8_PIN1, ISB_APP_DIGOUT_9_PIN1, ISB_APP_DIGOUT_10_PIN1, ISB_APP_DIGOUT_11_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_0, ISB_APP_DIGOUT_1_OBJ_1BIT_0, ISB_APP_DIGOUT_2_OBJ_1BIT_0, ISB_APP_DIGOUT_3_OBJ_1BIT_0, ISB_APP_DIGOUT_4_OBJ_1BIT_0, ISB_APP_DIGOUT_5_OBJ_1BIT_0, ISB_APP_DIGOUT_6_OBJ_1BIT_0, ISB_APP_DIGOUT_7_OBJ_1BIT_0, ISB_APP_DIGOUT_8_OBJ_1BIT_0, ISB_APP_DIGOUT_9_OBJ_1BIT_0, ISB_APP_DIGOUT_10_OBJ_1BIT_0, ISB_APP_DIGOUT_11_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_1, ISB_APP_DIGOUT_1_OBJ_1BIT_1, ISB_APP_DIGOUT_2_OBJ_1BIT_1, ISB_APP_DIGOUT_3_OBJ_1BIT_1, ISB_APP_DIGOUT_4_OBJ_1BIT_1, ISB_APP_DIGOUT_5_OBJ_1BIT_1, ISB_APP_DIGOUT_6_OBJ_1BIT_1, ISB_APP_DIGOUT_7_OBJ_1BIT_1, ISB_APP_DIGOUT_8_OBJ_1BIT_1, ISB_APP_DIGOUT_9_OBJ_1BIT_1, ISB_APP_DIGOUT_10_OBJ_1BIT_1, ISB_APP_DIGOUT_11_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_2, ISB_APP_DIGOUT_1_OBJ_1BIT_2, ISB_APP_DIGOUT_2_OBJ_1BIT_2, ISB_APP_DIGOUT_3_OBJ_1BIT_2, ISB_APP_DIGOUT_4_OBJ_1BIT_2, ISB_APP_DIGOUT_5_OBJ_1BIT_2, ISB_APP_DIGOUT_6_OBJ_1BIT_2, ISB_APP_DIGOUT_7_OBJ_1BIT_2, ISB_APP_DIGOUT_8_OBJ_1BIT_2, ISB_APP_DIGOUT_9_OBJ_1BIT_2, ISB_APP_DIGOUT_10_OBJ_1BIT_2, ISB_APP_DIGOUT_11_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_3, ISB_APP_DIGOUT_1_OBJ_1BIT_3, ISB_APP_DIGOUT_2_OBJ_1BIT_3, ISB_APP_DIGOUT_3_OBJ_1BIT_3, ISB_APP_DIGOUT_4_OBJ_1BIT_3, ISB_APP_DIGOUT_5_OBJ_1BIT_3, ISB_APP_DIGOUT_6_OBJ_1BIT_3, ISB_APP_DIGOUT_7_OBJ_1BIT_3, ISB_APP_DIGOUT_8_OBJ_1BIT_3, ISB_APP_DIGOUT_9_OBJ_1BIT_3, ISB_APP_DIGOUT_10_OBJ_1BIT_3, ISB_APP_DIGOUT_11_OBJ_1BIT_3 };
		#elif ISB_APP_DIGOUT_MAX == 13
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH, ISB_APP_DIGOUT_5_CH, ISB_APP_DIGOUT_6_CH, ISB_APP_DIGOUT_7_CH, ISB_APP_DIGOUT_8_CH, ISB_APP_DIGOUT_9_CH, ISB_APP_DIGOUT_10_CH, ISB_APP_DIGOUT_11_CH, ISB_APP_DIGOUT_12_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0, ISB_APP_DIGOUT_5_PIN0, ISB_APP_DIGOUT_6_PIN0, ISB_APP_DIGOUT_7_PIN0, ISB_APP_DIGOUT_8_PIN0, ISB_APP_DIGOUT_9_PIN0, ISB_APP_DIGOUT_10_PIN0, ISB_APP_DIGOUT_11_PIN0, ISB_APP_DIGOUT_12_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1, ISB_APP_DIGOUT_5_PIN1, ISB_APP_DIGOUT_6_PIN1, ISB_APP_DIGOUT_7_PIN1, ISB_APP_DIGOUT_8_PIN1, ISB_APP_DIGOUT_9_PIN1, ISB_APP_DIGOUT_10_PIN1, ISB_APP_DIGOUT_11_PIN1, ISB_APP_DIGOUT_12_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_0, ISB_APP_DIGOUT_1_OBJ_1BIT_0, ISB_APP_DIGOUT_2_OBJ_1BIT_0, ISB_APP_DIGOUT_3_OBJ_1BIT_0, ISB_APP_DIGOUT_4_OBJ_1BIT_0, ISB_APP_DIGOUT_5_OBJ_1BIT_0, ISB_APP_DIGOUT_6_OBJ_1BIT_0, ISB_APP_DIGOUT_7_OBJ_1BIT_0, ISB_APP_DIGOUT_8_OBJ_1BIT_0, ISB_APP_DIGOUT_9_OBJ_1BIT_0, ISB_APP_DIGOUT_10_OBJ_1BIT_0, ISB_APP_DIGOUT_11_OBJ_1BIT_0, ISB_APP_DIGOUT_12_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_1, ISB_APP_DIGOUT_1_OBJ_1BIT_1, ISB_APP_DIGOUT_2_OBJ_1BIT_1, ISB_APP_DIGOUT_3_OBJ_1BIT_1, ISB_APP_DIGOUT_4_OBJ_1BIT_1, ISB_APP_DIGOUT_5_OBJ_1BIT_1, ISB_APP_DIGOUT_6_OBJ_1BIT_1, ISB_APP_DIGOUT_7_OBJ_1BIT_1, ISB_APP_DIGOUT_8_OBJ_1BIT_1, ISB_APP_DIGOUT_9_OBJ_1BIT_1, ISB_APP_DIGOUT_10_OBJ_1BIT_1, ISB_APP_DIGOUT_11_OBJ_1BIT_1, ISB_APP_DIGOUT_12_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_2, ISB_APP_DIGOUT_1_OBJ_1BIT_2, ISB_APP_DIGOUT_2_OBJ_1BIT_2, ISB_APP_DIGOUT_3_OBJ_1BIT_2, ISB_APP_DIGOUT_4_OBJ_1BIT_2, ISB_APP_DIGOUT_5_OBJ_1BIT_2, ISB_APP_DIGOUT_6_OBJ_1BIT_2, ISB_APP_DIGOUT_7_OBJ_1BIT_2, ISB_APP_DIGOUT_8_OBJ_1BIT_2, ISB_APP_DIGOUT_9_OBJ_1BIT_2, ISB_APP_DIGOUT_10_OBJ_1BIT_2, ISB_APP_DIGOUT_11_OBJ_1BIT_2, ISB_APP_DIGOUT_12_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_3, ISB_APP_DIGOUT_1_OBJ_1BIT_3, ISB_APP_DIGOUT_2_OBJ_1BIT_3, ISB_APP_DIGOUT_3_OBJ_1BIT_3, ISB_APP_DIGOUT_4_OBJ_1BIT_3, ISB_APP_DIGOUT_5_OBJ_1BIT_3, ISB_APP_DIGOUT_6_OBJ_1BIT_3, ISB_APP_DIGOUT_7_OBJ_1BIT_3, ISB_APP_DIGOUT_8_OBJ_1BIT_3, ISB_APP_DIGOUT_9_OBJ_1BIT_3, ISB_APP_DIGOUT_10_OBJ_1BIT_3, ISB_APP_DIGOUT_11_OBJ_1BIT_3, ISB_APP_DIGOUT_12_OBJ_1BIT_3 };
		#elif ISB_APP_DIGOUT_MAX == 14
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH, ISB_APP_DIGOUT_5_CH, ISB_APP_DIGOUT_6_CH, ISB_APP_DIGOUT_7_CH, ISB_APP_DIGOUT_8_CH, ISB_APP_DIGOUT_9_CH, ISB_APP_DIGOUT_10_CH, ISB_APP_DIGOUT_11_CH, ISB_APP_DIGOUT_12_CH, ISB_APP_DIGOUT_13_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0, ISB_APP_DIGOUT_5_PIN0, ISB_APP_DIGOUT_6_PIN0, ISB_APP_DIGOUT_7_PIN0, ISB_APP_DIGOUT_8_PIN0, ISB_APP_DIGOUT_9_PIN0, ISB_APP_DIGOUT_10_PIN0, ISB_APP_DIGOUT_11_PIN0, ISB_APP_DIGOUT_12_PIN0, ISB_APP_DIGOUT_13_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1, ISB_APP_DIGOUT_5_PIN1, ISB_APP_DIGOUT_6_PIN1, ISB_APP_DIGOUT_7_PIN1, ISB_APP_DIGOUT_8_PIN1, ISB_APP_DIGOUT_9_PIN1, ISB_APP_DIGOUT_10_PIN1, ISB_APP_DIGOUT_11_PIN1, ISB_APP_DIGOUT_12_PIN1, ISB_APP_DIGOUT_13_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_0, ISB_APP_DIGOUT_1_OBJ_1BIT_0, ISB_APP_DIGOUT_2_OBJ_1BIT_0, ISB_APP_DIGOUT_3_OBJ_1BIT_0, ISB_APP_DIGOUT_4_OBJ_1BIT_0, ISB_APP_DIGOUT_5_OBJ_1BIT_0, ISB_APP_DIGOUT_6_OBJ_1BIT_0, ISB_APP_DIGOUT_7_OBJ_1BIT_0, ISB_APP_DIGOUT_8_OBJ_1BIT_0, ISB_APP_DIGOUT_9_OBJ_1BIT_0, ISB_APP_DIGOUT_10_OBJ_1BIT_0, ISB_APP_DIGOUT_11_OBJ_1BIT_0, ISB_APP_DIGOUT_12_OBJ_1BIT_0, ISB_APP_DIGOUT_13_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_1, ISB_APP_DIGOUT_1_OBJ_1BIT_1, ISB_APP_DIGOUT_2_OBJ_1BIT_1, ISB_APP_DIGOUT_3_OBJ_1BIT_1, ISB_APP_DIGOUT_4_OBJ_1BIT_1, ISB_APP_DIGOUT_5_OBJ_1BIT_1, ISB_APP_DIGOUT_6_OBJ_1BIT_1, ISB_APP_DIGOUT_7_OBJ_1BIT_1, ISB_APP_DIGOUT_8_OBJ_1BIT_1, ISB_APP_DIGOUT_9_OBJ_1BIT_1, ISB_APP_DIGOUT_10_OBJ_1BIT_1, ISB_APP_DIGOUT_11_OBJ_1BIT_1, ISB_APP_DIGOUT_12_OBJ_1BIT_1, ISB_APP_DIGOUT_13_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_2, ISB_APP_DIGOUT_1_OBJ_1BIT_2, ISB_APP_DIGOUT_2_OBJ_1BIT_2, ISB_APP_DIGOUT_3_OBJ_1BIT_2, ISB_APP_DIGOUT_4_OBJ_1BIT_2, ISB_APP_DIGOUT_5_OBJ_1BIT_2, ISB_APP_DIGOUT_6_OBJ_1BIT_2, ISB_APP_DIGOUT_7_OBJ_1BIT_2, ISB_APP_DIGOUT_8_OBJ_1BIT_2, ISB_APP_DIGOUT_9_OBJ_1BIT_2, ISB_APP_DIGOUT_10_OBJ_1BIT_2, ISB_APP_DIGOUT_11_OBJ_1BIT_1, ISB_APP_DIGOUT_12_OBJ_1BIT_2, ISB_APP_DIGOUT_13_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_3, ISB_APP_DIGOUT_1_OBJ_1BIT_3, ISB_APP_DIGOUT_2_OBJ_1BIT_3, ISB_APP_DIGOUT_3_OBJ_1BIT_3, ISB_APP_DIGOUT_4_OBJ_1BIT_3, ISB_APP_DIGOUT_5_OBJ_1BIT_3, ISB_APP_DIGOUT_6_OBJ_1BIT_3, ISB_APP_DIGOUT_7_OBJ_1BIT_3, ISB_APP_DIGOUT_8_OBJ_1BIT_3, ISB_APP_DIGOUT_9_OBJ_1BIT_3, ISB_APP_DIGOUT_10_OBJ_1BIT_3, ISB_APP_DIGOUT_11_OBJ_1BIT_1, ISB_APP_DIGOUT_12_OBJ_1BIT_3, ISB_APP_DIGOUT_13_OBJ_1BIT_3 };
		#elif ISB_APP_DIGOUT_MAX == 15
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH, ISB_APP_DIGOUT_5_CH, ISB_APP_DIGOUT_6_CH, ISB_APP_DIGOUT_7_CH, ISB_APP_DIGOUT_8_CH, ISB_APP_DIGOUT_9_CH, ISB_APP_DIGOUT_10_CH, ISB_APP_DIGOUT_11_CH, ISB_APP_DIGOUT_12_CH, ISB_APP_DIGOUT_13_CH, ISB_APP_DIGOUT_14_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0, ISB_APP_DIGOUT_5_PIN0, ISB_APP_DIGOUT_6_PIN0, ISB_APP_DIGOUT_7_PIN0, ISB_APP_DIGOUT_8_PIN0, ISB_APP_DIGOUT_9_PIN0, ISB_APP_DIGOUT_10_PIN0, ISB_APP_DIGOUT_11_PIN0, ISB_APP_DIGOUT_12_PIN0, ISB_APP_DIGOUT_13_PIN0, ISB_APP_DIGOUT_14_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1, ISB_APP_DIGOUT_5_PIN1, ISB_APP_DIGOUT_6_PIN1, ISB_APP_DIGOUT_7_PIN1, ISB_APP_DIGOUT_8_PIN1, ISB_APP_DIGOUT_9_PIN1, ISB_APP_DIGOUT_10_PIN1, ISB_APP_DIGOUT_11_PIN1, ISB_APP_DIGOUT_12_PIN1, ISB_APP_DIGOUT_13_PIN1, ISB_APP_DIGOUT_14_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_0, ISB_APP_DIGOUT_1_OBJ_1BIT_0, ISB_APP_DIGOUT_2_OBJ_1BIT_0, ISB_APP_DIGOUT_3_OBJ_1BIT_0, ISB_APP_DIGOUT_4_OBJ_1BIT_0, ISB_APP_DIGOUT_5_OBJ_1BIT_0, ISB_APP_DIGOUT_6_OBJ_1BIT_0, ISB_APP_DIGOUT_7_OBJ_1BIT_0, ISB_APP_DIGOUT_8_OBJ_1BIT_0, ISB_APP_DIGOUT_9_OBJ_1BIT_0, ISB_APP_DIGOUT_10_OBJ_1BIT_0, ISB_APP_DIGOUT_11_OBJ_1BIT_0, ISB_APP_DIGOUT_12_OBJ_1BIT_0, ISB_APP_DIGOUT_13_OBJ_1BIT_0, ISB_APP_DIGOUT_14_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_1, ISB_APP_DIGOUT_1_OBJ_1BIT_1, ISB_APP_DIGOUT_2_OBJ_1BIT_1, ISB_APP_DIGOUT_3_OBJ_1BIT_1, ISB_APP_DIGOUT_4_OBJ_1BIT_1, ISB_APP_DIGOUT_5_OBJ_1BIT_1, ISB_APP_DIGOUT_6_OBJ_1BIT_1, ISB_APP_DIGOUT_7_OBJ_1BIT_1, ISB_APP_DIGOUT_8_OBJ_1BIT_1, ISB_APP_DIGOUT_9_OBJ_1BIT_1, ISB_APP_DIGOUT_10_OBJ_1BIT_1, ISB_APP_DIGOUT_11_OBJ_1BIT_1, ISB_APP_DIGOUT_12_OBJ_1BIT_1, ISB_APP_DIGOUT_13_OBJ_1BIT_1, ISB_APP_DIGOUT_14_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_2, ISB_APP_DIGOUT_1_OBJ_1BIT_2, ISB_APP_DIGOUT_2_OBJ_1BIT_2, ISB_APP_DIGOUT_3_OBJ_1BIT_2, ISB_APP_DIGOUT_4_OBJ_1BIT_2, ISB_APP_DIGOUT_5_OBJ_1BIT_2, ISB_APP_DIGOUT_6_OBJ_1BIT_2, ISB_APP_DIGOUT_7_OBJ_1BIT_2, ISB_APP_DIGOUT_8_OBJ_1BIT_2, ISB_APP_DIGOUT_9_OBJ_1BIT_2, ISB_APP_DIGOUT_10_OBJ_1BIT_2, ISB_APP_DIGOUT_11_OBJ_1BIT_1, ISB_APP_DIGOUT_12_OBJ_1BIT_2, ISB_APP_DIGOUT_13_OBJ_1BIT_2, ISB_APP_DIGOUT_14_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_3, ISB_APP_DIGOUT_1_OBJ_1BIT_3, ISB_APP_DIGOUT_2_OBJ_1BIT_3, ISB_APP_DIGOUT_3_OBJ_1BIT_3, ISB_APP_DIGOUT_4_OBJ_1BIT_3, ISB_APP_DIGOUT_5_OBJ_1BIT_3, ISB_APP_DIGOUT_6_OBJ_1BIT_3, ISB_APP_DIGOUT_7_OBJ_1BIT_3, ISB_APP_DIGOUT_8_OBJ_1BIT_3, ISB_APP_DIGOUT_9_OBJ_1BIT_3, ISB_APP_DIGOUT_10_OBJ_1BIT_3, ISB_APP_DIGOUT_11_OBJ_1BIT_1, ISB_APP_DIGOUT_12_OBJ_1BIT_3, ISB_APP_DIGOUT_13_OBJ_1BIT_3, ISB_APP_DIGOUT_14_OBJ_1BIT_3 };
		#elif ISB_APP_DIGOUT_MAX == 16
			static const uint8_t pgmIsb_App_DigOut_Ch_Array[] PROGMEM = { ISB_APP_DIGOUT_0_CH, ISB_APP_DIGOUT_1_CH, ISB_APP_DIGOUT_2_CH, ISB_APP_DIGOUT_3_CH, ISB_APP_DIGOUT_4_CH, ISB_APP_DIGOUT_5_CH, ISB_APP_DIGOUT_6_CH, ISB_APP_DIGOUT_7_CH, ISB_APP_DIGOUT_8_CH, ISB_APP_DIGOUT_9_CH, ISB_APP_DIGOUT_10_CH, ISB_APP_DIGOUT_11_CH, ISB_APP_DIGOUT_12_CH, ISB_APP_DIGOUT_13_CH, ISB_APP_DIGOUT_14_CH, ISB_APP_DIGOUT_15_CH };
			static const uint8_t pgmIsb_App_DigOut_Pin0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN0, ISB_APP_DIGOUT_1_PIN0, ISB_APP_DIGOUT_2_PIN0, ISB_APP_DIGOUT_3_PIN0, ISB_APP_DIGOUT_4_PIN0, ISB_APP_DIGOUT_5_PIN0, ISB_APP_DIGOUT_6_PIN0, ISB_APP_DIGOUT_7_PIN0, ISB_APP_DIGOUT_8_PIN0, ISB_APP_DIGOUT_9_PIN0, ISB_APP_DIGOUT_10_PIN0, ISB_APP_DIGOUT_11_PIN0, ISB_APP_DIGOUT_12_PIN0, ISB_APP_DIGOUT_13_PIN0, ISB_APP_DIGOUT_14_PIN0, ISB_APP_DIGOUT_15_PIN0 };
			static const uint8_t pgmIsb_App_DigOut_Pin1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_PIN1, ISB_APP_DIGOUT_1_PIN1, ISB_APP_DIGOUT_2_PIN1, ISB_APP_DIGOUT_3_PIN1, ISB_APP_DIGOUT_4_PIN1, ISB_APP_DIGOUT_5_PIN1, ISB_APP_DIGOUT_6_PIN1, ISB_APP_DIGOUT_7_PIN1, ISB_APP_DIGOUT_8_PIN1, ISB_APP_DIGOUT_9_PIN1, ISB_APP_DIGOUT_10_PIN1, ISB_APP_DIGOUT_11_PIN1, ISB_APP_DIGOUT_12_PIN1, ISB_APP_DIGOUT_13_PIN1, ISB_APP_DIGOUT_14_PIN1, ISB_APP_DIGOUT_15_PIN1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_0, ISB_APP_DIGOUT_1_OBJ_1BIT_0, ISB_APP_DIGOUT_2_OBJ_1BIT_0, ISB_APP_DIGOUT_3_OBJ_1BIT_0, ISB_APP_DIGOUT_4_OBJ_1BIT_0, ISB_APP_DIGOUT_5_OBJ_1BIT_0, ISB_APP_DIGOUT_6_OBJ_1BIT_0, ISB_APP_DIGOUT_7_OBJ_1BIT_0, ISB_APP_DIGOUT_8_OBJ_1BIT_0, ISB_APP_DIGOUT_9_OBJ_1BIT_0, ISB_APP_DIGOUT_10_OBJ_1BIT_0, ISB_APP_DIGOUT_11_OBJ_1BIT_0, ISB_APP_DIGOUT_12_OBJ_1BIT_0, ISB_APP_DIGOUT_13_OBJ_1BIT_0, ISB_APP_DIGOUT_14_OBJ_1BIT_0, ISB_APP_DIGOUT_15_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_1, ISB_APP_DIGOUT_1_OBJ_1BIT_1, ISB_APP_DIGOUT_2_OBJ_1BIT_1, ISB_APP_DIGOUT_3_OBJ_1BIT_1, ISB_APP_DIGOUT_4_OBJ_1BIT_1, ISB_APP_DIGOUT_5_OBJ_1BIT_1, ISB_APP_DIGOUT_6_OBJ_1BIT_1, ISB_APP_DIGOUT_7_OBJ_1BIT_1, ISB_APP_DIGOUT_8_OBJ_1BIT_1, ISB_APP_DIGOUT_9_OBJ_1BIT_1, ISB_APP_DIGOUT_10_OBJ_1BIT_1, ISB_APP_DIGOUT_11_OBJ_1BIT_1, ISB_APP_DIGOUT_12_OBJ_1BIT_1, ISB_APP_DIGOUT_13_OBJ_1BIT_1, ISB_APP_DIGOUT_14_OBJ_1BIT_1, ISB_APP_DIGOUT_15_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_2, ISB_APP_DIGOUT_1_OBJ_1BIT_2, ISB_APP_DIGOUT_2_OBJ_1BIT_2, ISB_APP_DIGOUT_3_OBJ_1BIT_2, ISB_APP_DIGOUT_4_OBJ_1BIT_2, ISB_APP_DIGOUT_5_OBJ_1BIT_2, ISB_APP_DIGOUT_6_OBJ_1BIT_2, ISB_APP_DIGOUT_7_OBJ_1BIT_2, ISB_APP_DIGOUT_8_OBJ_1BIT_2, ISB_APP_DIGOUT_9_OBJ_1BIT_2, ISB_APP_DIGOUT_10_OBJ_1BIT_2, ISB_APP_DIGOUT_11_OBJ_1BIT_1, ISB_APP_DIGOUT_12_OBJ_1BIT_2, ISB_APP_DIGOUT_13_OBJ_1BIT_2, ISB_APP_DIGOUT_14_OBJ_1BIT_2, ISB_APP_DIGOUT_15_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigOut_Obj_1Bit_3_Array[] PROGMEM = { ISB_APP_DIGOUT_0_OBJ_1BIT_3, ISB_APP_DIGOUT_1_OBJ_1BIT_3, ISB_APP_DIGOUT_2_OBJ_1BIT_3, ISB_APP_DIGOUT_3_OBJ_1BIT_3, ISB_APP_DIGOUT_4_OBJ_1BIT_3, ISB_APP_DIGOUT_5_OBJ_1BIT_3, ISB_APP_DIGOUT_6_OBJ_1BIT_3, ISB_APP_DIGOUT_7_OBJ_1BIT_3, ISB_APP_DIGOUT_8_OBJ_1BIT_3, ISB_APP_DIGOUT_9_OBJ_1BIT_3, ISB_APP_DIGOUT_10_OBJ_1BIT_3, ISB_APP_DIGOUT_11_OBJ_1BIT_1, ISB_APP_DIGOUT_12_OBJ_1BIT_3, ISB_APP_DIGOUT_13_OBJ_1BIT_3, ISB_APP_DIGOUT_14_OBJ_1BIT_3, ISB_APP_DIGOUT_15_OBJ_1BIT_3 };
		#else
			#error ISB_APP_DIGOUT_MAX
		#endif /* ISB_APP_DIGOUT_MAX == ? */

		typedef struct Isb_App_DigOut_t Isb_App_DigOut_t;

		struct Isb_App_DigOut_t {
			uint8_t Cfg0;
			uint8_t Cfg1;
			uint8_t Cfg2;
			uint8_t Cfg3;
			uint8_t Cfg4;
			uint8_t Cfg5;
			uint8_t Cfg6;
			uint8_t Cfg7;
			uint8_t Cfg8;
			uint8_t Cfg9;
			uint32_t TimeOnCount;
			uint32_t TimeOffCount;
			uint8_t LogicValue;
			uint8_t LogicIsChanged;
			uint8_t TimeValue;
			uint8_t TimeIsChanged;
			uint8_t SpecialValue;
			uint8_t SpecialIsChanged;
			uint8_t Value;
			uint8_t IsChanged;
		};

		uint8_t Isb_App_DigOut_Ctrl = 0;
		uint16_t Isb_App_DigOut_IrqExec = 0;
		Isb_App_DigOut_t Isb_App_DigOut[ISB_APP_DIGOUT_MAX];
		uint8_t Isb_App_DigOut_Ssr_Index = 0;
		uint8_t Isb_App_DigOut_Ssr_Counter = 0;

	#endif /* ISB_APP_DIGOUT_MAX */



	#if defined(ISB_APP_DIGIN_MAX)

		#if ISB_APP_DIGIN_MAX == 1
			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH };
			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigIn_Obj_4Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_4BIT_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_8Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_8BIT_0 };
		#elif ISB_APP_DIGIN_MAX == 2
			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH, ISB_APP_DIGIN_1_CH };
			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0, ISB_APP_DIGIN_1_PIN0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_0, ISB_APP_DIGIN_1_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_1, ISB_APP_DIGIN_1_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_2, ISB_APP_DIGIN_1_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigIn_Obj_4Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_4BIT_0, ISB_APP_DIGIN_1_OBJ_4BIT_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_8Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_8BIT_0, ISB_APP_DIGIN_1_OBJ_8BIT_0 };
		#elif ISB_APP_DIGIN_MAX == 3
			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH, ISB_APP_DIGIN_1_CH, ISB_APP_DIGIN_2_CH };
			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0, ISB_APP_DIGIN_1_PIN0, ISB_APP_DIGIN_2_PIN0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_0, ISB_APP_DIGIN_1_OBJ_1BIT_0, ISB_APP_DIGIN_2_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_1, ISB_APP_DIGIN_1_OBJ_1BIT_1, ISB_APP_DIGIN_2_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_2, ISB_APP_DIGIN_1_OBJ_1BIT_2, ISB_APP_DIGIN_2_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigIn_Obj_4Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_4BIT_0, ISB_APP_DIGIN_1_OBJ_4BIT_0, ISB_APP_DIGIN_2_OBJ_4BIT_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_8Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_8BIT_0, ISB_APP_DIGIN_1_OBJ_8BIT_0, ISB_APP_DIGIN_2_OBJ_8BIT_0 };
		#elif ISB_APP_DIGIN_MAX == 4
			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH, ISB_APP_DIGIN_1_CH, ISB_APP_DIGIN_2_CH, ISB_APP_DIGIN_3_CH };
			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0, ISB_APP_DIGIN_1_PIN0, ISB_APP_DIGIN_2_PIN0, ISB_APP_DIGIN_3_PIN0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_0, ISB_APP_DIGIN_1_OBJ_1BIT_0, ISB_APP_DIGIN_2_OBJ_1BIT_0, ISB_APP_DIGIN_3_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_1, ISB_APP_DIGIN_1_OBJ_1BIT_1, ISB_APP_DIGIN_2_OBJ_1BIT_1, ISB_APP_DIGIN_3_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_2, ISB_APP_DIGIN_1_OBJ_1BIT_2, ISB_APP_DIGIN_2_OBJ_1BIT_2, ISB_APP_DIGIN_3_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigIn_Obj_4Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_4BIT_0, ISB_APP_DIGIN_1_OBJ_4BIT_0, ISB_APP_DIGIN_2_OBJ_4BIT_0, ISB_APP_DIGIN_3_OBJ_4BIT_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_8Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_8BIT_0, ISB_APP_DIGIN_1_OBJ_8BIT_0, ISB_APP_DIGIN_2_OBJ_8BIT_0, ISB_APP_DIGIN_3_OBJ_8BIT_0 };
		#elif ISB_APP_DIGIN_MAX == 5
			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH, ISB_APP_DIGIN_1_CH, ISB_APP_DIGIN_2_CH, ISB_APP_DIGIN_3_CH, ISB_APP_DIGIN_4_CH };
			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0, ISB_APP_DIGIN_1_PIN0, ISB_APP_DIGIN_2_PIN0, ISB_APP_DIGIN_3_PIN0, ISB_APP_DIGIN_4_PIN0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_0, ISB_APP_DIGIN_1_OBJ_1BIT_0, ISB_APP_DIGIN_2_OBJ_1BIT_0, ISB_APP_DIGIN_3_OBJ_1BIT_0, ISB_APP_DIGIN_4_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_1, ISB_APP_DIGIN_1_OBJ_1BIT_1, ISB_APP_DIGIN_2_OBJ_1BIT_1, ISB_APP_DIGIN_3_OBJ_1BIT_1, ISB_APP_DIGIN_4_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_2, ISB_APP_DIGIN_1_OBJ_1BIT_2, ISB_APP_DIGIN_2_OBJ_1BIT_2, ISB_APP_DIGIN_3_OBJ_1BIT_2, ISB_APP_DIGIN_4_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigIn_Obj_4Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_4BIT_0, ISB_APP_DIGIN_1_OBJ_4BIT_0, ISB_APP_DIGIN_2_OBJ_4BIT_0, ISB_APP_DIGIN_3_OBJ_4BIT_0, ISB_APP_DIGIN_4_OBJ_4BIT_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_8Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_8BIT_0, ISB_APP_DIGIN_1_OBJ_8BIT_0, ISB_APP_DIGIN_2_OBJ_8BIT_0, ISB_APP_DIGIN_3_OBJ_8BIT_0, ISB_APP_DIGIN_4_OBJ_8BIT_0 };
		#elif ISB_APP_DIGIN_MAX == 6
			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH, ISB_APP_DIGIN_1_CH, ISB_APP_DIGIN_2_CH, ISB_APP_DIGIN_3_CH, ISB_APP_DIGIN_4_CH, ISB_APP_DIGIN_5_CH };
			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0, ISB_APP_DIGIN_1_PIN0, ISB_APP_DIGIN_2_PIN0, ISB_APP_DIGIN_3_PIN0, ISB_APP_DIGIN_4_PIN0, ISB_APP_DIGIN_5_PIN0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_0, ISB_APP_DIGIN_1_OBJ_1BIT_0, ISB_APP_DIGIN_2_OBJ_1BIT_0, ISB_APP_DIGIN_3_OBJ_1BIT_0, ISB_APP_DIGIN_4_OBJ_1BIT_0, ISB_APP_DIGIN_5_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_1, ISB_APP_DIGIN_1_OBJ_1BIT_1, ISB_APP_DIGIN_2_OBJ_1BIT_1, ISB_APP_DIGIN_3_OBJ_1BIT_1, ISB_APP_DIGIN_4_OBJ_1BIT_1, ISB_APP_DIGIN_5_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_2, ISB_APP_DIGIN_1_OBJ_1BIT_2, ISB_APP_DIGIN_2_OBJ_1BIT_2, ISB_APP_DIGIN_3_OBJ_1BIT_2, ISB_APP_DIGIN_4_OBJ_1BIT_2, ISB_APP_DIGIN_5_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigIn_Obj_4Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_4BIT_0, ISB_APP_DIGIN_1_OBJ_4BIT_0, ISB_APP_DIGIN_2_OBJ_4BIT_0, ISB_APP_DIGIN_3_OBJ_4BIT_0, ISB_APP_DIGIN_4_OBJ_4BIT_0, ISB_APP_DIGIN_5_OBJ_4BIT_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_8Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_8BIT_0, ISB_APP_DIGIN_1_OBJ_8BIT_0, ISB_APP_DIGIN_2_OBJ_8BIT_0, ISB_APP_DIGIN_3_OBJ_8BIT_0, ISB_APP_DIGIN_4_OBJ_8BIT_0, ISB_APP_DIGIN_5_OBJ_8BIT_0 };
		#elif ISB_APP_DIGIN_MAX == 7
			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH, ISB_APP_DIGIN_1_CH, ISB_APP_DIGIN_2_CH, ISB_APP_DIGIN_3_CH, ISB_APP_DIGIN_4_CH, ISB_APP_DIGIN_5_CH, ISB_APP_DIGIN_6_CH };
			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0, ISB_APP_DIGIN_1_PIN0, ISB_APP_DIGIN_2_PIN0, ISB_APP_DIGIN_3_PIN0, ISB_APP_DIGIN_4_PIN0, ISB_APP_DIGIN_5_PIN0, ISB_APP_DIGIN_6_PIN0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_0, ISB_APP_DIGIN_1_OBJ_1BIT_0, ISB_APP_DIGIN_2_OBJ_1BIT_0, ISB_APP_DIGIN_3_OBJ_1BIT_0, ISB_APP_DIGIN_4_OBJ_1BIT_0, ISB_APP_DIGIN_5_OBJ_1BIT_0, ISB_APP_DIGIN_6_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_1, ISB_APP_DIGIN_1_OBJ_1BIT_1, ISB_APP_DIGIN_2_OBJ_1BIT_1, ISB_APP_DIGIN_3_OBJ_1BIT_1, ISB_APP_DIGIN_4_OBJ_1BIT_1, ISB_APP_DIGIN_5_OBJ_1BIT_1, ISB_APP_DIGIN_6_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_2, ISB_APP_DIGIN_1_OBJ_1BIT_2, ISB_APP_DIGIN_2_OBJ_1BIT_2, ISB_APP_DIGIN_3_OBJ_1BIT_2, ISB_APP_DIGIN_4_OBJ_1BIT_2, ISB_APP_DIGIN_5_OBJ_1BIT_2, ISB_APP_DIGIN_6_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigIn_Obj_4Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_4BIT_0, ISB_APP_DIGIN_1_OBJ_4BIT_0, ISB_APP_DIGIN_2_OBJ_4BIT_0, ISB_APP_DIGIN_3_OBJ_4BIT_0, ISB_APP_DIGIN_4_OBJ_4BIT_0, ISB_APP_DIGIN_5_OBJ_4BIT_0, ISB_APP_DIGIN_6_OBJ_4BIT_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_8Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_8BIT_0, ISB_APP_DIGIN_1_OBJ_8BIT_0, ISB_APP_DIGIN_2_OBJ_8BIT_0, ISB_APP_DIGIN_3_OBJ_8BIT_0, ISB_APP_DIGIN_4_OBJ_8BIT_0, ISB_APP_DIGIN_5_OBJ_8BIT_0, ISB_APP_DIGIN_6_OBJ_8BIT_0 };
		#elif ISB_APP_DIGIN_MAX == 8
			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH, ISB_APP_DIGIN_1_CH, ISB_APP_DIGIN_2_CH, ISB_APP_DIGIN_3_CH, ISB_APP_DIGIN_4_CH, ISB_APP_DIGIN_5_CH, ISB_APP_DIGIN_6_CH, ISB_APP_DIGIN_7_CH };
			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0, ISB_APP_DIGIN_1_PIN0, ISB_APP_DIGIN_2_PIN0, ISB_APP_DIGIN_3_PIN0, ISB_APP_DIGIN_4_PIN0, ISB_APP_DIGIN_5_PIN0, ISB_APP_DIGIN_6_PIN0, ISB_APP_DIGIN_7_PIN0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_0, ISB_APP_DIGIN_1_OBJ_1BIT_0, ISB_APP_DIGIN_2_OBJ_1BIT_0, ISB_APP_DIGIN_3_OBJ_1BIT_0, ISB_APP_DIGIN_4_OBJ_1BIT_0, ISB_APP_DIGIN_5_OBJ_1BIT_0, ISB_APP_DIGIN_6_OBJ_1BIT_0, ISB_APP_DIGIN_7_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_1, ISB_APP_DIGIN_1_OBJ_1BIT_1, ISB_APP_DIGIN_2_OBJ_1BIT_1, ISB_APP_DIGIN_3_OBJ_1BIT_1, ISB_APP_DIGIN_4_OBJ_1BIT_1, ISB_APP_DIGIN_5_OBJ_1BIT_1, ISB_APP_DIGIN_6_OBJ_1BIT_1, ISB_APP_DIGIN_7_OBJ_1BIT_1 };
			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_2, ISB_APP_DIGIN_1_OBJ_1BIT_2, ISB_APP_DIGIN_2_OBJ_1BIT_2, ISB_APP_DIGIN_3_OBJ_1BIT_2, ISB_APP_DIGIN_4_OBJ_1BIT_2, ISB_APP_DIGIN_5_OBJ_1BIT_2, ISB_APP_DIGIN_6_OBJ_1BIT_2, ISB_APP_DIGIN_7_OBJ_1BIT_2 };
			static const uint8_t pgmIsb_App_DigIn_Obj_4Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_4BIT_0, ISB_APP_DIGIN_1_OBJ_4BIT_0, ISB_APP_DIGIN_2_OBJ_4BIT_0, ISB_APP_DIGIN_3_OBJ_4BIT_0, ISB_APP_DIGIN_4_OBJ_4BIT_0, ISB_APP_DIGIN_5_OBJ_4BIT_0, ISB_APP_DIGIN_6_OBJ_4BIT_0, ISB_APP_DIGIN_7_OBJ_4BIT_0 };
			static const uint8_t pgmIsb_App_DigIn_Obj_8Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_8BIT_0, ISB_APP_DIGIN_1_OBJ_8BIT_0, ISB_APP_DIGIN_2_OBJ_8BIT_0, ISB_APP_DIGIN_3_OBJ_8BIT_0, ISB_APP_DIGIN_4_OBJ_8BIT_0, ISB_APP_DIGIN_5_OBJ_8BIT_0, ISB_APP_DIGIN_6_OBJ_8BIT_0, ISB_APP_DIGIN_7_OBJ_8BIT_0 };
//		#elif ISB_APP_DIGIN_MAX == 9
//		#elif ISB_APP_DIGIN_MAX == 10
//		#elif ISB_APP_DIGIN_MAX == 11
//		#elif ISB_APP_DIGIN_MAX == 12
//		#elif ISB_APP_DIGIN_MAX == 13
//		#elif ISB_APP_DIGIN_MAX == 14
//		#elif ISB_APP_DIGIN_MAX == 15
//		#elif ISB_APP_DIGIN_MAX == 16
		#else
			#error ISB_APP_DIGIN_MAX
		#endif /* ISB_APP_DIGIN_MAX == ? */

		typedef struct Isb_App_DigIn_t Isb_App_DigIn_t;

		struct Isb_App_DigIn_t {
			uint8_t Cfg0;
			uint8_t Cfg1;
			uint8_t Cfg2;
			uint8_t Cfg3;
			uint8_t Value;
			uint8_t Event;
			uint8_t CountLow;
			uint8_t CountHigh;
		};

		uint8_t Isb_App_DigIn_Ctrl = 0;
		uint16_t Isb_App_DigIn_IrqExec = 0;
		Isb_App_DigIn_t Isb_App_DigIn[ISB_APP_DIGIN_MAX];

	#endif /* ISB_APP_DIGIN_MAX */



	#if defined(ISB_APP_ANAIN_MAX)

		#if ISB_APP_ANAIN_MAX == 1
			static const uint8_t pgmIsb_App_AnaIn_Ch_Array[] PROGMEM = { ISB_APP_ANAIN_0_CH };
//			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_Float_0_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_FLOAT_0 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_1BIT_0 };
			static const uint8_t pgmIsb_App_AnaIn_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_ANAIN_0_OBJ_1BIT_1 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_2 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_4Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_4BIT_0 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_8Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_8BIT_0 };
//		#elif ISB_APP_ANAIN_MAX == 2
//			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH, ISB_APP_DIGIN_1_CH };
//			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0, ISB_APP_DIGIN_1_PIN0 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_0, ISB_APP_DIGIN_1_OBJ_1BIT_0 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_1, ISB_APP_DIGIN_1_OBJ_1BIT_1 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_2, ISB_APP_DIGIN_1_OBJ_1BIT_2 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_4Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_4BIT_0, ISB_APP_DIGIN_1_OBJ_4BIT_0 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_8Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_8BIT_0, ISB_APP_DIGIN_1_OBJ_8BIT_0 };
//		#elif ISB_APP_ANAIN_MAX == 3
//			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH, ISB_APP_DIGIN_1_CH, ISB_APP_DIGIN_2_CH };
//			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0, ISB_APP_DIGIN_1_PIN0, ISB_APP_DIGIN_2_PIN0 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_0, ISB_APP_DIGIN_1_OBJ_1BIT_0, ISB_APP_DIGIN_2_OBJ_1BIT_0 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_1, ISB_APP_DIGIN_1_OBJ_1BIT_1, ISB_APP_DIGIN_2_OBJ_1BIT_1 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_2, ISB_APP_DIGIN_1_OBJ_1BIT_2, ISB_APP_DIGIN_2_OBJ_1BIT_2 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_4Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_4BIT_0, ISB_APP_DIGIN_1_OBJ_4BIT_0, ISB_APP_DIGIN_2_OBJ_4BIT_0 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_8Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_8BIT_0, ISB_APP_DIGIN_1_OBJ_8BIT_0, ISB_APP_DIGIN_2_OBJ_8BIT_0 };
//		#elif ISB_APP_ANAIN_MAX == 4
//			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH, ISB_APP_DIGIN_1_CH, ISB_APP_DIGIN_2_CH, ISB_APP_DIGIN_3_CH };
//			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0, ISB_APP_DIGIN_1_PIN0, ISB_APP_DIGIN_2_PIN0, ISB_APP_DIGIN_3_PIN0 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_0, ISB_APP_DIGIN_1_OBJ_1BIT_0, ISB_APP_DIGIN_2_OBJ_1BIT_0, ISB_APP_DIGIN_3_OBJ_1BIT_0 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_1, ISB_APP_DIGIN_1_OBJ_1BIT_1, ISB_APP_DIGIN_2_OBJ_1BIT_1, ISB_APP_DIGIN_3_OBJ_1BIT_1 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_2, ISB_APP_DIGIN_1_OBJ_1BIT_2, ISB_APP_DIGIN_2_OBJ_1BIT_2, ISB_APP_DIGIN_3_OBJ_1BIT_2 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_4Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_4BIT_0, ISB_APP_DIGIN_1_OBJ_4BIT_0, ISB_APP_DIGIN_2_OBJ_4BIT_0, ISB_APP_DIGIN_3_OBJ_4BIT_0 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_8Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_8BIT_0, ISB_APP_DIGIN_1_OBJ_8BIT_0, ISB_APP_DIGIN_2_OBJ_8BIT_0, ISB_APP_DIGIN_3_OBJ_8BIT_0 };
//		#elif ISB_APP_ANAIN_MAX == 5
//			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH, ISB_APP_DIGIN_1_CH, ISB_APP_DIGIN_2_CH, ISB_APP_DIGIN_3_CH, ISB_APP_DIGIN_4_CH };
//			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0, ISB_APP_DIGIN_1_PIN0, ISB_APP_DIGIN_2_PIN0, ISB_APP_DIGIN_3_PIN0, ISB_APP_DIGIN_4_PIN0 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_0, ISB_APP_DIGIN_1_OBJ_1BIT_0, ISB_APP_DIGIN_2_OBJ_1BIT_0, ISB_APP_DIGIN_3_OBJ_1BIT_0, ISB_APP_DIGIN_4_OBJ_1BIT_0 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_1, ISB_APP_DIGIN_1_OBJ_1BIT_1, ISB_APP_DIGIN_2_OBJ_1BIT_1, ISB_APP_DIGIN_3_OBJ_1BIT_1, ISB_APP_DIGIN_4_OBJ_1BIT_1 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_2, ISB_APP_DIGIN_1_OBJ_1BIT_2, ISB_APP_DIGIN_2_OBJ_1BIT_2, ISB_APP_DIGIN_3_OBJ_1BIT_2, ISB_APP_DIGIN_4_OBJ_1BIT_2 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_4Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_4BIT_0, ISB_APP_DIGIN_1_OBJ_4BIT_0, ISB_APP_DIGIN_2_OBJ_4BIT_0, ISB_APP_DIGIN_3_OBJ_4BIT_0, ISB_APP_DIGIN_4_OBJ_4BIT_0 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_8Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_8BIT_0, ISB_APP_DIGIN_1_OBJ_8BIT_0, ISB_APP_DIGIN_2_OBJ_8BIT_0, ISB_APP_DIGIN_3_OBJ_8BIT_0, ISB_APP_DIGIN_4_OBJ_8BIT_0 };
//		#elif ISB_APP_ANAIN_MAX == 6
//			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH, ISB_APP_DIGIN_1_CH, ISB_APP_DIGIN_2_CH, ISB_APP_DIGIN_3_CH, ISB_APP_DIGIN_4_CH, ISB_APP_DIGIN_5_CH };
//			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0, ISB_APP_DIGIN_1_PIN0, ISB_APP_DIGIN_2_PIN0, ISB_APP_DIGIN_3_PIN0, ISB_APP_DIGIN_4_PIN0, ISB_APP_DIGIN_5_PIN0 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_0, ISB_APP_DIGIN_1_OBJ_1BIT_0, ISB_APP_DIGIN_2_OBJ_1BIT_0, ISB_APP_DIGIN_3_OBJ_1BIT_0, ISB_APP_DIGIN_4_OBJ_1BIT_0, ISB_APP_DIGIN_5_OBJ_1BIT_0 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_1, ISB_APP_DIGIN_1_OBJ_1BIT_1, ISB_APP_DIGIN_2_OBJ_1BIT_1, ISB_APP_DIGIN_3_OBJ_1BIT_1, ISB_APP_DIGIN_4_OBJ_1BIT_1, ISB_APP_DIGIN_5_OBJ_1BIT_1 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_2, ISB_APP_DIGIN_1_OBJ_1BIT_2, ISB_APP_DIGIN_2_OBJ_1BIT_2, ISB_APP_DIGIN_3_OBJ_1BIT_2, ISB_APP_DIGIN_4_OBJ_1BIT_2, ISB_APP_DIGIN_5_OBJ_1BIT_2 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_4Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_4BIT_0, ISB_APP_DIGIN_1_OBJ_4BIT_0, ISB_APP_DIGIN_2_OBJ_4BIT_0, ISB_APP_DIGIN_3_OBJ_4BIT_0, ISB_APP_DIGIN_4_OBJ_4BIT_0, ISB_APP_DIGIN_5_OBJ_4BIT_0 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_8Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_8BIT_0, ISB_APP_DIGIN_1_OBJ_8BIT_0, ISB_APP_DIGIN_2_OBJ_8BIT_0, ISB_APP_DIGIN_3_OBJ_8BIT_0, ISB_APP_DIGIN_4_OBJ_8BIT_0, ISB_APP_DIGIN_5_OBJ_8BIT_0 };
//		#elif ISB_APP_ANAIN_MAX == 7
//			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH, ISB_APP_DIGIN_1_CH, ISB_APP_DIGIN_2_CH, ISB_APP_DIGIN_3_CH, ISB_APP_DIGIN_4_CH, ISB_APP_DIGIN_5_CH, ISB_APP_DIGIN_6_CH };
//			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0, ISB_APP_DIGIN_1_PIN0, ISB_APP_DIGIN_2_PIN0, ISB_APP_DIGIN_3_PIN0, ISB_APP_DIGIN_4_PIN0, ISB_APP_DIGIN_5_PIN0, ISB_APP_DIGIN_6_PIN0 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_0, ISB_APP_DIGIN_1_OBJ_1BIT_0, ISB_APP_DIGIN_2_OBJ_1BIT_0, ISB_APP_DIGIN_3_OBJ_1BIT_0, ISB_APP_DIGIN_4_OBJ_1BIT_0, ISB_APP_DIGIN_5_OBJ_1BIT_0, ISB_APP_DIGIN_6_OBJ_1BIT_0 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_1, ISB_APP_DIGIN_1_OBJ_1BIT_1, ISB_APP_DIGIN_2_OBJ_1BIT_1, ISB_APP_DIGIN_3_OBJ_1BIT_1, ISB_APP_DIGIN_4_OBJ_1BIT_1, ISB_APP_DIGIN_5_OBJ_1BIT_1, ISB_APP_DIGIN_6_OBJ_1BIT_1 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_2, ISB_APP_DIGIN_1_OBJ_1BIT_2, ISB_APP_DIGIN_2_OBJ_1BIT_2, ISB_APP_DIGIN_3_OBJ_1BIT_2, ISB_APP_DIGIN_4_OBJ_1BIT_2, ISB_APP_DIGIN_5_OBJ_1BIT_2, ISB_APP_DIGIN_6_OBJ_1BIT_2 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_4Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_4BIT_0, ISB_APP_DIGIN_1_OBJ_4BIT_0, ISB_APP_DIGIN_2_OBJ_4BIT_0, ISB_APP_DIGIN_3_OBJ_4BIT_0, ISB_APP_DIGIN_4_OBJ_4BIT_0, ISB_APP_DIGIN_5_OBJ_4BIT_0, ISB_APP_DIGIN_6_OBJ_4BIT_0 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_8Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_8BIT_0, ISB_APP_DIGIN_1_OBJ_8BIT_0, ISB_APP_DIGIN_2_OBJ_8BIT_0, ISB_APP_DIGIN_3_OBJ_8BIT_0, ISB_APP_DIGIN_4_OBJ_8BIT_0, ISB_APP_DIGIN_5_OBJ_8BIT_0, ISB_APP_DIGIN_6_OBJ_8BIT_0 };
//		#elif ISB_APP_ANAIN_MAX == 8
//			static const uint8_t pgmIsb_App_DigIn_Ch_Array[] PROGMEM = { ISB_APP_DIGIN_0_CH, ISB_APP_DIGIN_1_CH, ISB_APP_DIGIN_2_CH, ISB_APP_DIGIN_3_CH, ISB_APP_DIGIN_4_CH, ISB_APP_DIGIN_5_CH, ISB_APP_DIGIN_6_CH, ISB_APP_DIGIN_7_CH };
//			static const uint8_t pgmIsb_App_DigIn_Pin0_Array[] PROGMEM = { ISB_APP_DIGIN_0_PIN0, ISB_APP_DIGIN_1_PIN0, ISB_APP_DIGIN_2_PIN0, ISB_APP_DIGIN_3_PIN0, ISB_APP_DIGIN_4_PIN0, ISB_APP_DIGIN_5_PIN0, ISB_APP_DIGIN_6_PIN0, ISB_APP_DIGIN_7_PIN0 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_0, ISB_APP_DIGIN_1_OBJ_1BIT_0, ISB_APP_DIGIN_2_OBJ_1BIT_0, ISB_APP_DIGIN_3_OBJ_1BIT_0, ISB_APP_DIGIN_4_OBJ_1BIT_0, ISB_APP_DIGIN_5_OBJ_1BIT_0, ISB_APP_DIGIN_6_OBJ_1BIT_0, ISB_APP_DIGIN_7_OBJ_1BIT_0 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_1_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_1, ISB_APP_DIGIN_1_OBJ_1BIT_1, ISB_APP_DIGIN_2_OBJ_1BIT_1, ISB_APP_DIGIN_3_OBJ_1BIT_1, ISB_APP_DIGIN_4_OBJ_1BIT_1, ISB_APP_DIGIN_5_OBJ_1BIT_1, ISB_APP_DIGIN_6_OBJ_1BIT_1, ISB_APP_DIGIN_7_OBJ_1BIT_1 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_1Bit_2_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_1BIT_2, ISB_APP_DIGIN_1_OBJ_1BIT_2, ISB_APP_DIGIN_2_OBJ_1BIT_2, ISB_APP_DIGIN_3_OBJ_1BIT_2, ISB_APP_DIGIN_4_OBJ_1BIT_2, ISB_APP_DIGIN_5_OBJ_1BIT_2, ISB_APP_DIGIN_6_OBJ_1BIT_2, ISB_APP_DIGIN_7_OBJ_1BIT_2 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_4Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_4BIT_0, ISB_APP_DIGIN_1_OBJ_4BIT_0, ISB_APP_DIGIN_2_OBJ_4BIT_0, ISB_APP_DIGIN_3_OBJ_4BIT_0, ISB_APP_DIGIN_4_OBJ_4BIT_0, ISB_APP_DIGIN_5_OBJ_4BIT_0, ISB_APP_DIGIN_6_OBJ_4BIT_0, ISB_APP_DIGIN_7_OBJ_4BIT_0 };
//			static const uint8_t pgmIsb_App_DigIn_Obj_8Bit_0_Array[] PROGMEM = { ISB_APP_DIGIN_0_OBJ_8BIT_0, ISB_APP_DIGIN_1_OBJ_8BIT_0, ISB_APP_DIGIN_2_OBJ_8BIT_0, ISB_APP_DIGIN_3_OBJ_8BIT_0, ISB_APP_DIGIN_4_OBJ_8BIT_0, ISB_APP_DIGIN_5_OBJ_8BIT_0, ISB_APP_DIGIN_6_OBJ_8BIT_0, ISB_APP_DIGIN_7_OBJ_8BIT_0 };
//		#elif ISB_APP_ANAIN_MAX == 9
//		#elif ISB_APP_ANAIN_MAX == 10
//		#elif ISB_APP_ANAIN_MAX == 11
//		#elif ISB_APP_ANAIN_MAX == 12
//		#elif ISB_APP_ANAIN_MAX == 13
//		#elif ISB_APP_ANAIN_MAX == 14
//		#elif ISB_APP_ANAIN_MAX == 15
//		#elif ISB_APP_ANAIN_MAX == 16
		#else
			#error ISB_APP_ANAIN_MAX
		#endif /* ISB_APP_ANAIN_MAX == ? */

		typedef struct Isb_App_AnaIn_t Isb_App_AnaIn_t;

		struct Isb_App_AnaIn_t {
			uint16_t TimeCount;
			uint8_t Cfg0;
			uint8_t Cfg1;
			uint8_t Cfg2;
			uint16_t Value;
			uint16_t On1;
			uint16_t Off1;
			uint16_t On2;
			uint16_t Off2;
		};

		uint8_t Isb_App_AnaIn_Ctrl = 0;
		uint16_t Isb_App_AnaIn_IrqExec = 0;
		Isb_App_AnaIn_t Isb_App_AnaIn[ISB_APP_ANAIN_MAX];

	#endif /* ISB_APP_ANAIN_MAX */



	#if defined(ISB_APP_LCD_MAX)

		#if ISB_APP_LCD_MAX == 1
			static const uint8_t pgmIsb_App_Lcd_Ch_Array[] PROGMEM = { ISB_APP_LCD_0_CH };
		#else
			#error ISB_APP_LCD_MAX
		#endif /* ISB_APP_LCD_MAX == ? */

		typedef struct Isb_App_Lcd_t Isb_App_Lcd_t;

		struct Isb_App_Lcd_t {
//			uint8_t Ch;
//			uint8_t Obj_Sensor;
//			uint16_t TimeCount;
//			uint8_t Typ;
			uint8_t Cfg0;
			uint8_t Cfg1;
			uint8_t Cfg2;
//			uint16_t Min;
//			uint16_t Max;
			uint16_t Value;
		};

		uint8_t Isb_App_Lcd_Ctrl = 0;
		uint16_t Isb_App_Lcd_IrqExec = 0;
		Isb_App_Lcd_t Isb_App_Lcd[ISB_APP_LCD_MAX];

	#endif /* ISB_APP_LCD_MAX */



	void Isb_App_Init(void);
	void Isb_App_Exec(void);



#endif /* ISB_APP_H_ */
