/**
 * @file		fw/fw_40/trunk/main.c
 *
 * @brief		Firmware.
 *
 * This file includes the Firmware.
 *
 * @author		© Patrick Amrhein <trick-at-isysbus-dot-org> 01.05.2010.
 *
 * @date		$Date$
 *
 * @version		$Rev$
 *
 * @note
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http:*www.gnu.org/licenses.
 */





#include <stdio.h>



#define USE_AVRLIB_ISB



#include <trunk/core/isb_fw_app.h>



const uint8_t Isb_Firmware_Code[4] = { 0x28, 0x00, 0x00, 0x00 };



#define ISB_CH_MAX 4

#define ISB_CH_0 0
#if defined(ISB_CH_0)
	#define ISB_CH_0_EEADDR_CTRL 0x0000
	#define ISB_APP_ANAIN_0 0
	#define ISB_APP_ANAIN_0_CH 0
	#define ISB_APP_ANAIN_0_EEADDR_CFG0 0x0001
	#define ISB_APP_ANAIN_0_EEADDR_CFG1 0x0002
	#define ISB_APP_ANAIN_0_EEADDR_CFG2 0x0003
	#define ISB_APP_ANAIN_0_EEADDR_CFG_SWITCH1ON 0x0004
	#define ISB_APP_ANAIN_0_EEADDR_CFG_SWITCH1OFF 0x0006
	#define ISB_APP_ANAIN_0_EEADDR_CFG_SWITCH2ON 0x0008
	#define ISB_APP_ANAIN_0_EEADDR_CFG_SWITCH2OFF 0x000A
	#define ISB_APP_ANAIN_0_OBJ_0_EEADDR_CTRL 0x000C
	#define ISB_APP_ANAIN_0_OBJ_0_EEADDR_TOV 0x000D
	#define ISB_APP_ANAIN_0_OBJ_0_EEADDR_INITVALUE 0x000E
	#define ISB_APP_ANAIN_0_OBJ_1_EEADDR_CTRL 0x0013
	#define ISB_APP_ANAIN_0_OBJ_1_EEADDR_TOV 0x0014
	#define ISB_APP_ANAIN_0_OBJ_1_EEADDR_INITVALUE 0x0015
	#define ISB_APP_ANAIN_0_OBJ_2_EEADDR_CTRL 0x001A
	#define ISB_APP_ANAIN_0_OBJ_2_EEADDR_TOV 0x001B
	#define ISB_APP_ANAIN_0_OBJ_2_EEADDR_INITVALUE 0x001C
	#define ISB_APP_ANAIN_0_OBJ_0 0
	#define ISB_OBJ_0 0
	#define ISB_OBJ_0_CH 0
	#define ISB_APP_ANAIN_0_OBJ_1 1
	#define ISB_OBJ_1 1
	#define ISB_OBJ_1_CH 0
	#define ISB_APP_ANAIN_0_OBJ_2 2
	#define ISB_OBJ_2 2
	#define ISB_OBJ_2_CH 0
	#define ISB_CH_0_EEADDR_CRC 0x0021
#endif /* ISB_CH_0 */

#define ISB_CH_1 1
#if defined(ISB_CH_1)
	#define ISB_CH_1_EEADDR_CTRL 0x0022
	#define ISB_APP_CLOCK_0 0
	#define ISB_APP_CLOCK_0_CH 1
	#define ISB_APP_CLOCK_0_OBJ_0_EEADDR_CTRL 0x0023
	#define ISB_APP_CLOCK_0_OBJ_0_EEADDR_TOV 0x0024
	#define ISB_APP_CLOCK_0_OBJ_0_EEADDR_INITVALUE 0x0025
	#define ISB_APP_CLOCK_0_OBJ_1_EEADDR_CTRL 0x002A
	#define ISB_APP_CLOCK_0_OBJ_1_EEADDR_TOV 0x002B
	#define ISB_APP_CLOCK_0_OBJ_1_EEADDR_INITVALUE 0x002C
	#define ISB_APP_CLOCK_0_OBJ_0 3
	#define ISB_OBJ_3 3
	#define ISB_OBJ_3_CH 1
	#define ISB_APP_CLOCK_0_OBJ_1 4
	#define ISB_OBJ_4 4
	#define ISB_OBJ_4_CH 1
	#define ISB_CH_1_EEADDR_CRC 0x0031
#endif /* ISB_CH_1 */

#define ISB_CH_2 2
#if defined(ISB_CH_2)
	#define ISB_CH_2_EEADDR_CTRL 0x0032
	#define ISB_APP_DIGIN_0 0
	#define ISB_APP_DIGIN_0_CH 2
	#define ISB_APP_DIGIN_0_EEADDR_CFG0 0x0033
	#define ISB_APP_DIGIN_0_EEADDR_CFG1 0x0034
	#define ISB_APP_DIGIN_0_EEADDR_CFG2 0x0035
	#define ISB_APP_DIGIN_0_EEADDR_CFG3 0x0036
	#define ISB_APP_DIGIN_0_PIN0 B | 0 | PULLUP
	#define ISB_APP_DIGIN_0_OBJ_0_EEADDR_CTRL 0x0037
	#define ISB_APP_DIGIN_0_OBJ_0_EEADDR_TOV 0x0038
	#define ISB_APP_DIGIN_0_OBJ_0_EEADDR_INITVALUE 0x0039
	#define ISB_APP_DIGIN_0_OBJ_1_EEADDR_CTRL 0x003E
	#define ISB_APP_DIGIN_0_OBJ_1_EEADDR_TOV 0x003F
	#define ISB_APP_DIGIN_0_OBJ_1_EEADDR_INITVALUE 0x0040
	#define ISB_APP_DIGIN_0_OBJ_2_EEADDR_CTRL 0x0045
	#define ISB_APP_DIGIN_0_OBJ_2_EEADDR_TOV 0x0046
	#define ISB_APP_DIGIN_0_OBJ_2_EEADDR_INITVALUE 0x0047
	#define ISB_APP_DIGIN_0_OBJ_0 5
	#define ISB_OBJ_5 5
	#define ISB_OBJ_5_CH 2
	#define ISB_APP_DIGIN_0_OBJ_1 6
	#define ISB_OBJ_6 6
	#define ISB_OBJ_6_CH 2
	#define ISB_APP_DIGIN_0_OBJ_2 7
	#define ISB_OBJ_7 7
	#define ISB_OBJ_7_CH 2
	#define ISB_CH_2_EEADDR_CRC 0x004C
#endif /* ISB_CH_2 */

#define ISB_CH_3 3
#if defined(ISB_CH_3)
	#define ISB_CH_3_EEADDR_CTRL 0x004D
	#define ISB_APP_DIGOUT_0 0
	#define ISB_APP_DIGOUT_0_CH 3
	#define ISB_APP_DIGOUT_0_PIN0 C | 6
	#define ISB_APP_DIGOUT_0_PIN1 B | 0 | PULLUP
	#define ISB_APP_DIGOUT_0_EEADDR_CFG0 0x004E
	#define ISB_APP_DIGOUT_0_OBJ_0_EEADDR_CTRL 0x004F
	#define ISB_APP_DIGOUT_0_OBJ_0_EEADDR_TOV 0x0050
	#define ISB_APP_DIGOUT_0_OBJ_0_EEADDR_INITVALUE 0x0051
	#define ISB_APP_DIGOUT_0_OBJ_0 8
	#define ISB_OBJ_8 8
	#define ISB_OBJ_8_CH 3
	#define ISB_APP_DIGOUT_0_EEADDR_CFG1 0x0056
	#define ISB_APP_DIGOUT_0_OBJ_1_EEADDR_CTRL 0x0057
	#define ISB_APP_DIGOUT_0_OBJ_1_EEADDR_TOV 0x0058
	#define ISB_APP_DIGOUT_0_OBJ_1_EEADDR_INITVALUE 0x0059
	#define ISB_APP_DIGOUT_0_OBJ_1 9
	#define ISB_OBJ_9 9
	#define ISB_OBJ_9_CH 3
	#define ISB_APP_DIGOUT_0_EEADDR_CFG2 0x005E
	#define ISB_APP_DIGOUT_0_OBJ_2_EEADDR_CTRL 0x005F
	#define ISB_APP_DIGOUT_0_OBJ_2_EEADDR_TOV 0x0060
	#define ISB_APP_DIGOUT_0_OBJ_2_EEADDR_INITVALUE 0x0061
	#define ISB_APP_DIGOUT_0_OBJ_2 10
	#define ISB_OBJ_10 10
	#define ISB_OBJ_10_CH 3
	#define ISB_APP_DIGOUT_0_EEADDR_CFG3 0x0066
	#define ISB_APP_DIGOUT_0_EEADDR_CFG4 0x0067
	#define ISB_APP_DIGOUT_0_EEADDR_CFG5 0x0068
	#define ISB_APP_DIGOUT_0_EEADDR_CFG6 0x0069
	#define ISB_APP_DIGOUT_0_EEADDR_CFG7 0x006A
	#define ISB_APP_DIGOUT_0_EEADDR_CFG8 0x006B
	#define ISB_APP_DIGOUT_0_EEADDR_CFG9 0x006C
	#define ISB_CH_3_EEADDR_CRC 0x006D
#endif /* ISB_CH_3 */



#define ISB_APP_ANAIN_MAX 1
#define ISB_APP_ANAIN_EXECTIME 10
#define ISB_APP_ANAIN_SOURCE_FEATURE_DS1621 TRUE

#define ISB_APP_CLOCK_MAX 1
#define ISB_APP_CLOCK_EXECTIME 10

#define ISB_APP_DIGIN_MAX 1
#define ISB_APP_DIGIN_EXECTIME 10
#define ISB_APP_DIGIN_SOURCE_FEATURE_PIN TRUE
#define ISB_APP_DIGIN_SOURCE_FEATURE_SLAVE_USART0 TRUE
#define ISB_APP_DIGIN_SOURCE_FEATURE_SLAVE_USART1 TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_SWITCH TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_SWITCH_FUNCTION_1SOUKLOR TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_SWITCH_FUNCTION_1SOUKLMR TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_SWITCH_FUNCTION_2SMUKLOR TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_SWITCH_FUNCTION_2SMUKLMR TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_DIMMER FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_DIMMER_FUNCTION_DUS TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_DIMMER_FUNCTION_ND TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_1TBKLLF TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_1TBKFLL TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_1TBNFS TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_1SBNF TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_2TBKLLF TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_2TBNF TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_2TBNFS TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_2TBNL TRUE

#define ISB_APP_DIGOUT_MAX 1
#define ISB_APP_DIGOUT_EXECTIME 10
#define ISB_APP_DIGOUT_DESTINATION_FEATURE_RELAIS TRUE
#define ISB_APP_DIGOUT_DESTINATION_FEATURE_SSR FALSE
#define ISB_APP_DIGOUT_DESTINATION_FEATURE_SLAVE_USART0 FALSE
#define ISB_APP_DIGOUT_DESTINATION_FEATURE_SLAVE_USART1 FALSE
#define ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION TRUE
#define ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION_AND TRUE
#define ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION_OR TRUE
#define ISB_APP_DIGOUT_FEATURE_TIMEFUNCTION TRUE
#define ISB_APP_DIGOUT_FEATURE_TIMEFUNCTION_POWERUPDELAY FALSE
#define ISB_APP_DIGOUT_FEATURE_TIMEFUNCTION_POWERDOWNDELAY FALSE
#define ISB_APP_DIGOUT_FEATURE_TIMEFUNCTION_STAIRCASEFUNCTION FALSE
#define ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION FALSE
#define ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION_BLOCKING FALSE
#define ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION_BONDAGE FALSE
#define ISB_APP_DIGOUT_FEATURE_RESULT TRUE

#define ISB_OBJ_MAX 11
#define ISB_OBJ_EXECTIME 10

#define ISB_GRP_MAX 32
#define ISB_GRP_EEADDR_START 0x006E



#define LIB_DS1621



#include <trunk/core/isb_fw_app.c>
