/**
 * @file		fw/fw_26/trunk/main.c
 *
 * @brief		Firmware.
 *
 * This file includes the Firmware.
 *
 * @author		© Patrick Amrhein <trick-at-isysbus-dot-org> 01.05.2010.
 *
 * @date		$Date$
 *
 * @version		$Rev$
 *
 * @note
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http:*www.gnu.org/licenses.
 */





#include <stdio.h>



#define USE_AVRLIB_ISB



#include <trunk/core/isb_fw_app.h>



const uint8_t Isb_Firmware_Code[4] = { 0x1A, 0x00, 0x00, 0x00 };



#define ISB_INF_CAN0 TRUE
#if ISB_INF_CAN0 == TRUE
	#define ISB_INF_CAN0_CLOCK 4000000
	#define ISB_INF_CAN0_SPEED 50000
	#define ISB_INF_CAN0_SS PORTB_PIN2
	#define ISB_INF_CAN0_RS MCP2515_RX1BF
	#define ISB_INF_CAN0_INT INTERRUPT0
	#define ISB_INF_CAN0_MODE LIB_MCP2515_MODE_NORMAL
#endif /* ISB_INF_CAN0 == TRUE */



#define ISB_CH_MAX 16

#define ISB_CH_0 0
#if defined(ISB_CH_0)
	#define ISB_CH_0_EEADDR_CTRL 0x0000
	#define ISB_APP_DIGIN_0 0
	#define ISB_APP_DIGIN_0_CH 0
	#define ISB_APP_DIGIN_0_EEADDR_CFG0 0x0001
	#define ISB_APP_DIGIN_0_EEADDR_CFG1 0x0002
	#define ISB_APP_DIGIN_0_EEADDR_CFG2 0x0003
	#define ISB_APP_DIGIN_0_EEADDR_CFG3 0x0004
	#define ISB_APP_DIGIN_0_PIN0 C | 0 | PULLUP
	#define ISB_APP_DIGIN_0_OBJ_0_EEADDR_CTRL 0x0005
	#define ISB_APP_DIGIN_0_OBJ_0_EEADDR_TOV 0x0006
	#define ISB_APP_DIGIN_0_OBJ_0_EEADDR_INITVALUE 0x0007
	#define ISB_APP_DIGIN_0_OBJ_1_EEADDR_CTRL 0x000C
	#define ISB_APP_DIGIN_0_OBJ_1_EEADDR_TOV 0x000D
	#define ISB_APP_DIGIN_0_OBJ_1_EEADDR_INITVALUE 0x000E
	#define ISB_APP_DIGIN_0_OBJ_2_EEADDR_CTRL 0x0013
	#define ISB_APP_DIGIN_0_OBJ_2_EEADDR_TOV 0x0014
	#define ISB_APP_DIGIN_0_OBJ_2_EEADDR_INITVALUE 0x0015
	#define ISB_APP_DIGIN_0_OBJ_0 0
	#define ISB_OBJ_0 0
	#define ISB_OBJ_0_CH 0
	#define ISB_APP_DIGIN_0_OBJ_1 1
	#define ISB_OBJ_1 1
	#define ISB_OBJ_1_CH 0
	#define ISB_APP_DIGIN_0_OBJ_2 2
	#define ISB_OBJ_2 2
	#define ISB_OBJ_2_CH 0
	#define ISB_CH_0_EEADDR_CRC 0x001A
#endif /* ISB_CH_0 */

#define ISB_CH_1 1
#if defined(ISB_CH_1)
	#define ISB_CH_1_EEADDR_CTRL 0x001B
	#define ISB_APP_DIGIN_1 1
	#define ISB_APP_DIGIN_1_CH 1
	#define ISB_APP_DIGIN_1_EEADDR_CFG0 0x001C
	#define ISB_APP_DIGIN_1_EEADDR_CFG1 0x001D
	#define ISB_APP_DIGIN_1_EEADDR_CFG2 0x001E
	#define ISB_APP_DIGIN_1_EEADDR_CFG3 0x001F
	#define ISB_APP_DIGIN_1_PIN0 C | 1 | PULLUP
	#define ISB_APP_DIGIN_1_OBJ_0_EEADDR_CTRL 0x0020
	#define ISB_APP_DIGIN_1_OBJ_0_EEADDR_TOV 0x0021
	#define ISB_APP_DIGIN_1_OBJ_0_EEADDR_INITVALUE 0x0022
	#define ISB_APP_DIGIN_1_OBJ_1_EEADDR_CTRL 0x0027
	#define ISB_APP_DIGIN_1_OBJ_1_EEADDR_TOV 0x0028
	#define ISB_APP_DIGIN_1_OBJ_1_EEADDR_INITVALUE 0x0029
	#define ISB_APP_DIGIN_1_OBJ_2_EEADDR_CTRL 0x002E
	#define ISB_APP_DIGIN_1_OBJ_2_EEADDR_TOV 0x002F
	#define ISB_APP_DIGIN_1_OBJ_2_EEADDR_INITVALUE 0x0030
	#define ISB_APP_DIGIN_1_OBJ_0 3
	#define ISB_OBJ_3 3
	#define ISB_OBJ_3_CH 1
	#define ISB_APP_DIGIN_1_OBJ_1 4
	#define ISB_OBJ_4 4
	#define ISB_OBJ_4_CH 1
	#define ISB_APP_DIGIN_1_OBJ_2 5
	#define ISB_OBJ_5 5
	#define ISB_OBJ_5_CH 1
	#define ISB_CH_1_EEADDR_CRC 0x0035
#endif /* ISB_CH_1 */

#define ISB_CH_2 2
#if defined(ISB_CH_2)
	#define ISB_CH_2_EEADDR_CTRL 0x0036
	#define ISB_APP_DIGIN_2 2
	#define ISB_APP_DIGIN_2_CH 2
	#define ISB_APP_DIGIN_2_EEADDR_CFG0 0x0037
	#define ISB_APP_DIGIN_2_EEADDR_CFG1 0x0038
	#define ISB_APP_DIGIN_2_EEADDR_CFG2 0x0039
	#define ISB_APP_DIGIN_2_EEADDR_CFG3 0x003A
	#define ISB_APP_DIGIN_2_PIN0 C | 2 | PULLUP
	#define ISB_APP_DIGIN_2_OBJ_0_EEADDR_CTRL 0x003B
	#define ISB_APP_DIGIN_2_OBJ_0_EEADDR_TOV 0x003C
	#define ISB_APP_DIGIN_2_OBJ_0_EEADDR_INITVALUE 0x003D
	#define ISB_APP_DIGIN_2_OBJ_1_EEADDR_CTRL 0x0042
	#define ISB_APP_DIGIN_2_OBJ_1_EEADDR_TOV 0x0043
	#define ISB_APP_DIGIN_2_OBJ_1_EEADDR_INITVALUE 0x0044
	#define ISB_APP_DIGIN_2_OBJ_2_EEADDR_CTRL 0x0049
	#define ISB_APP_DIGIN_2_OBJ_2_EEADDR_TOV 0x004A
	#define ISB_APP_DIGIN_2_OBJ_2_EEADDR_INITVALUE 0x004B
	#define ISB_APP_DIGIN_2_OBJ_0 6
	#define ISB_OBJ_6 6
	#define ISB_OBJ_6_CH 2
	#define ISB_APP_DIGIN_2_OBJ_1 7
	#define ISB_OBJ_7 7
	#define ISB_OBJ_7_CH 2
	#define ISB_APP_DIGIN_2_OBJ_2 8
	#define ISB_OBJ_8 8
	#define ISB_OBJ_8_CH 2
	#define ISB_CH_2_EEADDR_CRC 0x0050
#endif /* ISB_CH_2 */

#define ISB_CH_3 3
#if defined(ISB_CH_3)
	#define ISB_CH_3_EEADDR_CTRL 0x0051
	#define ISB_APP_DIGIN_3 3
	#define ISB_APP_DIGIN_3_CH 3
	#define ISB_APP_DIGIN_3_EEADDR_CFG0 0x0052
	#define ISB_APP_DIGIN_3_EEADDR_CFG1 0x0053
	#define ISB_APP_DIGIN_3_EEADDR_CFG2 0x0054
	#define ISB_APP_DIGIN_3_EEADDR_CFG3 0x0055
	#define ISB_APP_DIGIN_3_PIN0 C | 3 | PULLUP
	#define ISB_APP_DIGIN_3_OBJ_0_EEADDR_CTRL 0x0056
	#define ISB_APP_DIGIN_3_OBJ_0_EEADDR_TOV 0x0057
	#define ISB_APP_DIGIN_3_OBJ_0_EEADDR_INITVALUE 0x0058
	#define ISB_APP_DIGIN_3_OBJ_1_EEADDR_CTRL 0x005D
	#define ISB_APP_DIGIN_3_OBJ_1_EEADDR_TOV 0x005E
	#define ISB_APP_DIGIN_3_OBJ_1_EEADDR_INITVALUE 0x005F
	#define ISB_APP_DIGIN_3_OBJ_2_EEADDR_CTRL 0x0064
	#define ISB_APP_DIGIN_3_OBJ_2_EEADDR_TOV 0x0065
	#define ISB_APP_DIGIN_3_OBJ_2_EEADDR_INITVALUE 0x0066
	#define ISB_APP_DIGIN_3_OBJ_0 9
	#define ISB_OBJ_9 9
	#define ISB_OBJ_9_CH 3
	#define ISB_APP_DIGIN_3_OBJ_1 10
	#define ISB_OBJ_10 10
	#define ISB_OBJ_10_CH 3
	#define ISB_APP_DIGIN_3_OBJ_2 11
	#define ISB_OBJ_11 11
	#define ISB_OBJ_11_CH 3
	#define ISB_CH_3_EEADDR_CRC 0x006B
#endif /* ISB_CH_3 */

#define ISB_CH_4 4
#if defined(ISB_CH_4)
	#define ISB_CH_4_EEADDR_CTRL 0x006C
	#define ISB_APP_DIGIN_4 4
	#define ISB_APP_DIGIN_4_CH 4
	#define ISB_APP_DIGIN_4_EEADDR_CFG0 0x006D
	#define ISB_APP_DIGIN_4_EEADDR_CFG1 0x006E
	#define ISB_APP_DIGIN_4_EEADDR_CFG2 0x006F
	#define ISB_APP_DIGIN_4_EEADDR_CFG3 0x0070
	#define ISB_APP_DIGIN_4_PIN0 C | 4 | PULLUP
	#define ISB_APP_DIGIN_4_OBJ_0_EEADDR_CTRL 0x0071
	#define ISB_APP_DIGIN_4_OBJ_0_EEADDR_TOV 0x0072
	#define ISB_APP_DIGIN_4_OBJ_0_EEADDR_INITVALUE 0x0073
	#define ISB_APP_DIGIN_4_OBJ_1_EEADDR_CTRL 0x0078
	#define ISB_APP_DIGIN_4_OBJ_1_EEADDR_TOV 0x0079
	#define ISB_APP_DIGIN_4_OBJ_1_EEADDR_INITVALUE 0x007A
	#define ISB_APP_DIGIN_4_OBJ_2_EEADDR_CTRL 0x007F
	#define ISB_APP_DIGIN_4_OBJ_2_EEADDR_TOV 0x0080
	#define ISB_APP_DIGIN_4_OBJ_2_EEADDR_INITVALUE 0x0081
	#define ISB_APP_DIGIN_4_OBJ_0 12
	#define ISB_OBJ_12 12
	#define ISB_OBJ_12_CH 4
	#define ISB_APP_DIGIN_4_OBJ_1 13
	#define ISB_OBJ_13 13
	#define ISB_OBJ_13_CH 4
	#define ISB_APP_DIGIN_4_OBJ_2 14
	#define ISB_OBJ_14 14
	#define ISB_OBJ_14_CH 4
	#define ISB_CH_4_EEADDR_CRC 0x0086
#endif /* ISB_CH_4 */

#define ISB_CH_5 5
#if defined(ISB_CH_5)
	#define ISB_CH_5_EEADDR_CTRL 0x0087
	#define ISB_APP_DIGIN_5 5
	#define ISB_APP_DIGIN_5_CH 5
	#define ISB_APP_DIGIN_5_EEADDR_CFG0 0x0088
	#define ISB_APP_DIGIN_5_EEADDR_CFG1 0x0089
	#define ISB_APP_DIGIN_5_EEADDR_CFG2 0x008A
	#define ISB_APP_DIGIN_5_EEADDR_CFG3 0x008B
	#define ISB_APP_DIGIN_5_PIN0 C | 5 | PULLUP
	#define ISB_APP_DIGIN_5_OBJ_0_EEADDR_CTRL 0x008C
	#define ISB_APP_DIGIN_5_OBJ_0_EEADDR_TOV 0x008D
	#define ISB_APP_DIGIN_5_OBJ_0_EEADDR_INITVALUE 0x008E
	#define ISB_APP_DIGIN_5_OBJ_1_EEADDR_CTRL 0x0093
	#define ISB_APP_DIGIN_5_OBJ_1_EEADDR_TOV 0x0094
	#define ISB_APP_DIGIN_5_OBJ_1_EEADDR_INITVALUE 0x0095
	#define ISB_APP_DIGIN_5_OBJ_2_EEADDR_CTRL 0x009A
	#define ISB_APP_DIGIN_5_OBJ_2_EEADDR_TOV 0x009B
	#define ISB_APP_DIGIN_5_OBJ_2_EEADDR_INITVALUE 0x009C
	#define ISB_APP_DIGIN_5_OBJ_0 15
	#define ISB_OBJ_15 15
	#define ISB_OBJ_15_CH 5
	#define ISB_APP_DIGIN_5_OBJ_1 16
	#define ISB_OBJ_16 16
	#define ISB_OBJ_16_CH 5
	#define ISB_APP_DIGIN_5_OBJ_2 17
	#define ISB_OBJ_17 17
	#define ISB_OBJ_17_CH 5
	#define ISB_CH_5_EEADDR_CRC 0x00A1
#endif /* ISB_CH_5 */

#define ISB_CH_6 6
#if defined(ISB_CH_6)
	#define ISB_CH_6_EEADDR_CTRL 0x00A2
	#define ISB_APP_DIGIN_6 6
	#define ISB_APP_DIGIN_6_CH 6
	#define ISB_APP_DIGIN_6_EEADDR_CFG0 0x00A3
	#define ISB_APP_DIGIN_6_EEADDR_CFG1 0x00A4
	#define ISB_APP_DIGIN_6_EEADDR_CFG2 0x00A5
	#define ISB_APP_DIGIN_6_EEADDR_CFG3 0x00A6
	#define ISB_APP_DIGIN_6_PIN0 D | 0 | PULLUP
	#define ISB_APP_DIGIN_6_OBJ_0_EEADDR_CTRL 0x00A7
	#define ISB_APP_DIGIN_6_OBJ_0_EEADDR_TOV 0x00A8
	#define ISB_APP_DIGIN_6_OBJ_0_EEADDR_INITVALUE 0x00A9
	#define ISB_APP_DIGIN_6_OBJ_1_EEADDR_CTRL 0x00AE
	#define ISB_APP_DIGIN_6_OBJ_1_EEADDR_TOV 0x00AF
	#define ISB_APP_DIGIN_6_OBJ_1_EEADDR_INITVALUE 0x00B0
	#define ISB_APP_DIGIN_6_OBJ_2_EEADDR_CTRL 0x00B5
	#define ISB_APP_DIGIN_6_OBJ_2_EEADDR_TOV 0x00B6
	#define ISB_APP_DIGIN_6_OBJ_2_EEADDR_INITVALUE 0x00B7
	#define ISB_APP_DIGIN_6_OBJ_0 18
	#define ISB_OBJ_18 18
	#define ISB_OBJ_18_CH 6
	#define ISB_APP_DIGIN_6_OBJ_1 19
	#define ISB_OBJ_19 19
	#define ISB_OBJ_19_CH 6
	#define ISB_APP_DIGIN_6_OBJ_2 20
	#define ISB_OBJ_20 20
	#define ISB_OBJ_20_CH 6
	#define ISB_CH_6_EEADDR_CRC 0x00BC
#endif /* ISB_CH_6 */

#define ISB_CH_7 7
#if defined(ISB_CH_7)
	#define ISB_CH_7_EEADDR_CTRL 0x00BD
	#define ISB_APP_DIGIN_7 7
	#define ISB_APP_DIGIN_7_CH 7
	#define ISB_APP_DIGIN_7_EEADDR_CFG0 0x00BE
	#define ISB_APP_DIGIN_7_EEADDR_CFG1 0x00BF
	#define ISB_APP_DIGIN_7_EEADDR_CFG2 0x00C0
	#define ISB_APP_DIGIN_7_EEADDR_CFG3 0x00C1
	#define ISB_APP_DIGIN_7_PIN0 D | 1 | PULLUP
	#define ISB_APP_DIGIN_7_OBJ_0_EEADDR_CTRL 0x00C2
	#define ISB_APP_DIGIN_7_OBJ_0_EEADDR_TOV 0x00C3
	#define ISB_APP_DIGIN_7_OBJ_0_EEADDR_INITVALUE 0x00C4
	#define ISB_APP_DIGIN_7_OBJ_1_EEADDR_CTRL 0x00C9
	#define ISB_APP_DIGIN_7_OBJ_1_EEADDR_TOV 0x00CA
	#define ISB_APP_DIGIN_7_OBJ_1_EEADDR_INITVALUE 0x00CB
	#define ISB_APP_DIGIN_7_OBJ_2_EEADDR_CTRL 0x00D0
	#define ISB_APP_DIGIN_7_OBJ_2_EEADDR_TOV 0x00D1
	#define ISB_APP_DIGIN_7_OBJ_2_EEADDR_INITVALUE 0x00D2
	#define ISB_APP_DIGIN_7_OBJ_0 21
	#define ISB_OBJ_21 21
	#define ISB_OBJ_21_CH 7
	#define ISB_APP_DIGIN_7_OBJ_1 22
	#define ISB_OBJ_22 22
	#define ISB_OBJ_22_CH 7
	#define ISB_APP_DIGIN_7_OBJ_2 23
	#define ISB_OBJ_23 23
	#define ISB_OBJ_23_CH 7
	#define ISB_CH_7_EEADDR_CRC 0x00D7
#endif /* ISB_CH_7 */

#define ISB_CH_8 8
#if defined(ISB_CH_8)
	#define ISB_CH_8_EEADDR_CTRL 0x00D8
	#define ISB_APP_DIGOUT_0 0
	#define ISB_APP_DIGOUT_0_CH 8
	#define ISB_APP_DIGOUT_0_PIN0 D | 3
	#define ISB_APP_DIGOUT_0_PIN1 C | 0 | PULLUP
	#define ISB_APP_DIGOUT_0_EEADDR_CFG0 0x00D9
	#define ISB_APP_DIGOUT_0_OBJ_0_EEADDR_CTRL 0x00DA
	#define ISB_APP_DIGOUT_0_OBJ_0_EEADDR_TOV 0x00DB
	#define ISB_APP_DIGOUT_0_OBJ_0_EEADDR_INITVALUE 0x00DC
	#define ISB_APP_DIGOUT_0_OBJ_0 24
	#define ISB_OBJ_24 24
	#define ISB_OBJ_24_CH 8
	#define ISB_CH_8_EEADDR_CRC 0x00E1
#endif /* ISB_CH_8 */

#define ISB_CH_9 9
#if defined(ISB_CH_9)
	#define ISB_CH_9_EEADDR_CTRL 0x00E2
	#define ISB_APP_DIGOUT_1 1
	#define ISB_APP_DIGOUT_1_CH 9
	#define ISB_APP_DIGOUT_1_PIN0 B | 1
	#define ISB_APP_DIGOUT_1_PIN1 C | 1 | PULLUP
	#define ISB_APP_DIGOUT_1_EEADDR_CFG0 0x00E3
	#define ISB_APP_DIGOUT_1_OBJ_0_EEADDR_CTRL 0x00E4
	#define ISB_APP_DIGOUT_1_OBJ_0_EEADDR_TOV 0x00E5
	#define ISB_APP_DIGOUT_1_OBJ_0_EEADDR_INITVALUE 0x00E6
	#define ISB_APP_DIGOUT_1_OBJ_0 25
	#define ISB_OBJ_25 25
	#define ISB_OBJ_25_CH 9
	#define ISB_CH_9_EEADDR_CRC 0x00EB
#endif /* ISB_CH_9 */

#define ISB_CH_10 10
#if defined(ISB_CH_10)
	#define ISB_CH_10_EEADDR_CTRL 0x00EC
	#define ISB_APP_DIGOUT_2 2
	#define ISB_APP_DIGOUT_2_CH 10
	#define ISB_APP_DIGOUT_2_PIN0 B | 0
	#define ISB_APP_DIGOUT_2_PIN1 C | 2 | PULLUP
	#define ISB_APP_DIGOUT_2_EEADDR_CFG0 0x00ED
	#define ISB_APP_DIGOUT_2_OBJ_0_EEADDR_CTRL 0x00EE
	#define ISB_APP_DIGOUT_2_OBJ_0_EEADDR_TOV 0x00EF
	#define ISB_APP_DIGOUT_2_OBJ_0_EEADDR_INITVALUE 0x00F0
	#define ISB_APP_DIGOUT_2_OBJ_0 26
	#define ISB_OBJ_26 26
	#define ISB_OBJ_26_CH 10
	#define ISB_CH_10_EEADDR_CRC 0x00F5
#endif /* ISB_CH_10 */

#define ISB_CH_11 11
#if defined(ISB_CH_11)
	#define ISB_CH_11_EEADDR_CTRL 0x00F6
	#define ISB_APP_DIGOUT_3 3
	#define ISB_APP_DIGOUT_3_CH 11
	#define ISB_APP_DIGOUT_3_PIN0 D | 7
	#define ISB_APP_DIGOUT_3_PIN1 C | 3 | PULLUP
	#define ISB_APP_DIGOUT_3_EEADDR_CFG0 0x00F7
	#define ISB_APP_DIGOUT_3_OBJ_0_EEADDR_CTRL 0x00F8
	#define ISB_APP_DIGOUT_3_OBJ_0_EEADDR_TOV 0x00F9
	#define ISB_APP_DIGOUT_3_OBJ_0_EEADDR_INITVALUE 0x00FA
	#define ISB_APP_DIGOUT_3_OBJ_0 27
	#define ISB_OBJ_27 27
	#define ISB_OBJ_27_CH 11
	#define ISB_CH_11_EEADDR_CRC 0x00FF
#endif /* ISB_CH_11 */

#define ISB_CH_12 12
#if defined(ISB_CH_12)
	#define ISB_CH_12_EEADDR_CTRL 0x0100
	#define ISB_APP_DIGOUT_4 4
	#define ISB_APP_DIGOUT_4_CH 12
	#define ISB_APP_DIGOUT_4_PIN0 D | 6
	#define ISB_APP_DIGOUT_4_PIN1 C | 4 | PULLUP
	#define ISB_APP_DIGOUT_4_EEADDR_CFG0 0x0101
	#define ISB_APP_DIGOUT_4_OBJ_0_EEADDR_CTRL 0x0102
	#define ISB_APP_DIGOUT_4_OBJ_0_EEADDR_TOV 0x0103
	#define ISB_APP_DIGOUT_4_OBJ_0_EEADDR_INITVALUE 0x0104
	#define ISB_APP_DIGOUT_4_OBJ_0 28
	#define ISB_OBJ_28 28
	#define ISB_OBJ_28_CH 12
	#define ISB_CH_12_EEADDR_CRC 0x0109
#endif /* ISB_CH_12 */

#define ISB_CH_13 13
#if defined(ISB_CH_13)
	#define ISB_CH_13_EEADDR_CTRL 0x010A
	#define ISB_APP_DIGOUT_5 5
	#define ISB_APP_DIGOUT_5_CH 13
	#define ISB_APP_DIGOUT_5_PIN0 D | 5
	#define ISB_APP_DIGOUT_5_PIN1 C | 5 | PULLUP
	#define ISB_APP_DIGOUT_5_EEADDR_CFG0 0x010B
	#define ISB_APP_DIGOUT_5_OBJ_0_EEADDR_CTRL 0x010C
	#define ISB_APP_DIGOUT_5_OBJ_0_EEADDR_TOV 0x010D
	#define ISB_APP_DIGOUT_5_OBJ_0_EEADDR_INITVALUE 0x010E
	#define ISB_APP_DIGOUT_5_OBJ_0 29
	#define ISB_OBJ_29 29
	#define ISB_OBJ_29_CH 13
	#define ISB_CH_13_EEADDR_CRC 0x0113
#endif /* ISB_CH_13 */

#define ISB_CH_14 14
#if defined(ISB_CH_14)
	#define ISB_CH_14_EEADDR_CTRL 0x0114
	#define ISB_APP_DIGOUT_6 6
	#define ISB_APP_DIGOUT_6_CH 14
	#define ISB_APP_DIGOUT_6_PIN0 D | 4
	#define ISB_APP_DIGOUT_6_PIN1 D | 0 | PULLUP
	#define ISB_APP_DIGOUT_6_EEADDR_CFG0 0x0115
	#define ISB_APP_DIGOUT_6_OBJ_0_EEADDR_CTRL 0x0116
	#define ISB_APP_DIGOUT_6_OBJ_0_EEADDR_TOV 0x0117
	#define ISB_APP_DIGOUT_6_OBJ_0_EEADDR_INITVALUE 0x0118
	#define ISB_APP_DIGOUT_6_OBJ_0 30
	#define ISB_OBJ_30 30
	#define ISB_OBJ_30_CH 14
	#define ISB_CH_14_EEADDR_CRC 0x011D
#endif /* ISB_CH_14 */

#define ISB_CH_15 15
#if defined(ISB_CH_15)
	#define ISB_CH_15_EEADDR_CTRL 0x011E
	#define ISB_APP_DIGOUT_7 7
	#define ISB_APP_DIGOUT_7_CH 15
	#define ISB_APP_DIGOUT_7_PIN0 B | 6
	#define ISB_APP_DIGOUT_7_PIN1 D | 1 | PULLUP
	#define ISB_APP_DIGOUT_7_EEADDR_CFG0 0x011F
	#define ISB_APP_DIGOUT_7_OBJ_0_EEADDR_CTRL 0x0120
	#define ISB_APP_DIGOUT_7_OBJ_0_EEADDR_TOV 0x0121
	#define ISB_APP_DIGOUT_7_OBJ_0_EEADDR_INITVALUE 0x0122
	#define ISB_APP_DIGOUT_7_OBJ_0 31
	#define ISB_OBJ_31 31
	#define ISB_OBJ_31_CH 15
	#define ISB_CH_15_EEADDR_CRC 0x0127
#endif /* ISB_CH_15 */



#define ISB_APP_DIGIN_MAX 8
#define ISB_APP_DIGIN_EXECTIME 10
#define ISB_APP_DIGIN_SOURCE_FEATURE_PIN TRUE
#define ISB_APP_DIGIN_SOURCE_FEATURE_SLAVE_USART0 FALSE
#define ISB_APP_DIGIN_SOURCE_FEATURE_SLAVE_USART1 FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_SWITCH TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_SWITCH_FUNCTION_1SOUKLOR TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_SWITCH_FUNCTION_1SOUKLMR TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_SWITCH_FUNCTION_2SMUKLOR TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_SWITCH_FUNCTION_2SMUKLMR TRUE
#define ISB_APP_DIGIN_MODE_FEATURE_DIMMER FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_DIMMER_FUNCTION_DUS FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_DIMMER_FUNCTION_ND FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_1TBKLLF FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_1TBKFLL FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_1TBNFS FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_1SBNF FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_2TBKLLF FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_2TBNF FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_2TBNFS FALSE
#define ISB_APP_DIGIN_MODE_FEATURE_JALOUSIE_FUNCTION_2TBNL FALSE

#define ISB_APP_DIGOUT_MAX 8
#define ISB_APP_DIGOUT_EXECTIME 10
#define ISB_APP_DIGOUT_DESTINATION_FEATURE_RELAIS TRUE
#define ISB_APP_DIGOUT_DESTINATION_FEATURE_SSR FALSE
#define ISB_APP_DIGOUT_DESTINATION_FEATURE_SLAVE_USART0 FALSE
#define ISB_APP_DIGOUT_DESTINATION_FEATURE_SLAVE_USART1 FALSE
#define ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION FALSE
#define ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION_AND FALSE
#define ISB_APP_DIGOUT_FEATURE_LOGICFUNCTION_OR FALSE
#define ISB_APP_DIGOUT_FEATURE_TIMEFUNCTION FALSE
#define ISB_APP_DIGOUT_FEATURE_TIMEFUNCTION_POWERUPDELAY FALSE
#define ISB_APP_DIGOUT_FEATURE_TIMEFUNCTION_POWERDOWNDELAY FALSE
#define ISB_APP_DIGOUT_FEATURE_TIMEFUNCTION_STAIRCASEFUNCTION FALSE
#define ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION FALSE
#define ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION_BLOCKING FALSE
#define ISB_APP_DIGOUT_FEATURE_SPECIALFUNCTION_BONDAGE FALSE
#define ISB_APP_DIGOUT_FEATURE_RESULT FALSE

#define ISB_OBJ_MAX 32
#define ISB_OBJ_EXECTIME 10

#define ISB_GRP_MAX 32
#define ISB_GRP_EEADDR_START 0x0128



#include <trunk/core/isb_fw_app.c>
